import os
import re
import glob

def translate_text(text):
    translations = {
        "Manji": "万吉",
        "Mr. Thunder": "雷霆先生",
        "Mr. Smith": "史密斯先生",
        "Winston": "温斯顿",
        "Ayan": "阿yan",
        "Sophia": "索菲亚",
        "Rooney": "鲁尼",
        "Flora the Fairy": "妖精弗洛拉",
        "Len the Fairy": "妖精伦",
        "Grendel the Really Old": "真正古老的格伦德尔",
        "Francois": "弗朗索瓦",
        "Shane": "沙恩",
        "Joel": "乔尔",
        "Cherry": "樱桃",
        "Arwen the Fairy": "妖精阿尔温",
        "Rowen the Fairy": "妖精罗恩",
        "Mar the Fairy": "妖精玛尔",
        "Wing the Fairy": "妖精温",
        "Nella": "内拉",
        "Icarus": "伊卡洛斯",
        
        "Repair Durability": "修复耐久度",
        "Blacksmith": "铁匠",
        "Station Clerk": "车站职员",
        "Cabin Crew": "乘务员",
        
        "Don't talk to me": "别跟我说话",
        "Leave now... Or you'll get hurt": "现在离开...否则你会受伤",
        "Anyone who dares to stand in my path will be punished...": "任何胆敢挡我路的人都会受到惩罚...",
        "Hah... I was wondering who was bothering me, and it's you. All right, I won't call you a nobody anymore...": "哈...我在想是谁在烦我，原来是你。好吧，我不会再叫你无名小卒了...",
        "You got to take care of your equipment. You need your Durability taken care of, come see me.": "你得好好照顾你的装备。你需要处理你的耐久度，来找我吧。",
        "Need some equipment repaired? Bring it on over!": "需要修理装备吗？拿过来吧！",
        "I'm Mr. Thunder's best student. I can make ANYTHING.": "我是雷霆先生最好的学生。我什么都能做。",
        "Mr. Thunder does the repairs. I make all the new weapons.": "雷霆先生负责修理。我负责制作所有新武器。",
        "I'm so busy these days! What to make next?": "我这些天太忙了！接下来做什么呢？",
        "If you need something made, just come see me.": "如果你需要做什么东西，尽管来找我。",
        "Fossils contain important information about the past.": "化石包含有关过去的重要信息。",
        "Do you think I can recover all the data I've lost?": "你认为我能找回所有丢失的数据吗？",
        "Look around the cliff and you may be able to find the fossils.": "在悬崖周围找找，你可能会发现化石。",
        "I'm Winston the archeologist.": "我是考古学家温斯顿。",
        "You're the one that helped me out the other day. Unfortunately I'm really busy right this minute. I'll talk to you later.": "你是前几天帮我的那个人。不幸的是我现在真的很忙。我稍后再跟你谈。",
        "My name is Ayan. Nice to meet you!": "我的名字是阿yan。很高兴认识你！",
        "I have been living in this town ever since I was rescued by the people here.": "自从被这里的人救了以后，我就一直住在这个镇上。",
        "Hi!": "嗨！",
        "You are the one who helped me the other day. Thank you!": "你是前几天帮我的那个人。谢谢！",
        "Okay... I'm ready to do business...": "好的...我准备好做生意了...",
        "It's so boring around here...": "这里好无聊...",
        "Is Maya getting better from her sickness?": "玛雅的病好些了吗？",
        "Not a bad day at work today!": "今天工作不错！",
        "Please don't bargain with me too much!": "请不要跟我讨价还价太多！",
        "Doesn't it look good today? I put great effort into today's stock.": "今天看起来不错吧？我为今天的库存付出了很大努力。",
        "Hey, you're back!": "嘿，你回来了！",
        "Isn't it just gorgeous out here today?": "今天这里的景色不是很美吗？",
        "Man, I want to travel around and stuff. I don't want to be stuck here working. This stinks! I'm stuck here making potions everyday thanks to my mom opening up a store. This is definitely NOT fun.": "天啊，我想去旅行什么的。我不想被困在这里工作。这太糟糕了！因为我妈妈开了一家店，我每天都被困在这里做药水。这绝对不好玩。",
        "What did you do with #b#t4031004##k? That's a coveted rock and all, but it requires so many items to make that you're the first one to actually gather them all up! Anyway, hope this is put to good use.": "你用#b#t4031004##k做了什么？那是一块令人垂涎的石头，但制作它需要这么多物品，你是第一个真正把它们都收集起来的人！无论如何，希望它能得到很好的利用。",
        "Did you hear about a town near Ellinia that's covered in snow?": "你听说过艾琳尼亚附近有一个被雪覆盖的城镇吗？",
        "Don't you wanna check out the town that's covered in snow?": "你不想去看看那个被雪覆盖的城镇吗？",
        "Hello there. I'm Rooney.": "你好。我是鲁尼。",
        "Something urgent must be happening at Happyville.": "快乐镇一定发生了紧急事情。",
        "Welcome to Ellinia!": "欢迎来到艾琳尼亚！",
        "We have lots of Magician weapons! Take a look!": "我们有很多魔法师武器！来看看！",
        "Do you need potions by any chance? I have plenty in stock...": "你碰巧需要药水吗？我库存很多...",
        "If you want to return to Ellinia at will, then try buying the return scroll to this place.": "如果你想随意返回艾琳尼亚，那就试试买一张返回这里的卷轴。",
        "To all who seek to become magicians... Speak to me...": "所有想成为魔法师的人...跟我说话...",
        "Heh heh heh...": "嘿嘿嘿...",
        "My dear Pygmy, here's a tasty treat.": "我亲爱的矮人，这是一份美味的点心。",
        "Grendel the Really Old can scold me all he wants, but he can't stop my brilliant research!": "真正古老的格伦德尔可以随便骂我，但他阻止不了我出色的研究！",
        "Are you here at the request of Sabitrama?": "你是应萨比特拉玛的要求来的吗？",
        "I heard there's an incredible herb that can be found in here... But I can't just let you by so easily...": "我听说这里有一种不可思议的草药...但我不能就这么轻易让你通过...",
        "Do you want to enter this place? I'm sure you've heard of the rare herbs in here, but I can't let some stranger like you enter my property. I'm sorry, but you'll have to leave.": "你想进入这个地方吗？我相信你听说过这里的稀有草药，但我不能让像你这样的陌生人进入我的领地。对不起，你必须离开。",
        "Not just anyone can enter this place!": "不是任何人都能进入这个地方！",
        "You can board the ship headed for Orbis Station.": "你可以登上前往奥比斯站的船。",
        "Talk to Cherry if you want to get on board!": "如果你想上船，就跟樱桃谈谈！",
        "If you want to get on board the ship headed for Orbis Station, please give me the ticket.": "如果你想登上前往奥比斯站的船，请把票给我。",
        "This ship has a limited capacity, so please get on right now... It'll be leaving shortly.": "这艘船容量有限，所以请现在上船...它很快就要离开了。",
        "The ship is about to embark. Please wait a moment.": "船即将出发。请稍等片刻。",
        "So many humans in the village these days...": "这些天村里有这么多人...",
        "Grendel the Really Old is not a bad person, but his students...": "真正古老的格伦德尔不是坏人，但他的学生们...",
        "It's such a burden being friends with humans. They're so rude! So violent!": "和人类做朋友真是一种负担。他们太粗鲁了！太暴力了！",
        "There are SOME good humans out there. But how does one pick them out of the crowd?": "外面确实有一些好人。但怎么从人群中分辨出来呢？",
        "Welcome to Ellinia, the village of the Fairies.": "欢迎来到妖精村艾琳尼亚。",
        "It's time we Fairies opened ourselves up to the world.": "是我们妖精向世界开放的时候了。",
        "My friend Arwen is still pretty uncomfortable around humans.": "我的朋友阿尔温在人类周围仍然很不自在。",
        "Welcome to Ellinia, village of the Fairies. Ever since Grendel the Really Old moved here, the village has been filled with his pupils. It might as well be a human village these days.": "欢迎来到妖精村艾琳尼亚。自从真正古老的格伦德尔搬到这里后，村子里就挤满了他的学生。现在这里几乎可以算是一个人类村庄了。",
        "You seem like a good human. We could use more of your kind here in Ellinia.": "你看起来是个好人。艾琳尼亚这里可以多一些像你这样的人。",
        "Please love and take care of your pets. They are our valued friends.": "请爱护并照顾你的宠物。它们是我们宝贵的朋友。",
        "Has your pet turned back into a doll by any chance?": "你的宠物碰巧变回玩偶了吗？",
        "If you have an unmoving pet with you, please take it to me.": "如果你有一只不动的宠物，请把它带给我。",
        "So much homework... And so much studying to do... Man, I'm swamped...": "这么多作业...还有这么多学习要做...天啊，我忙死了...",
        "I'm busy, so bug off!": "我很忙，走开！",
        "Why do all these humans want to be my friend?": "为什么这些人类都想和我做朋友？",
        "Man, I'm sooo busy! Anyone around here willing to help?": "天啊，我太忙了！这附近有人愿意帮忙吗？",
        "Lots of strangers passing by today.": "今天有很多陌生人经过。",
        "I got so many requests from the townspeople today! I need help here...": "今天我收到了很多村民的请求！我需要帮助...",
        "Didn't you help me take care of #b#p1051000##k's request? He should be at home fixing himself a hearty dinner right about now. Unfortunately, I haven't gotten any new requests today. Come talk to me some other time, all right?": "你不是帮我处理了#b#p1051000##k的请求吗？他现在应该在家给自己做一顿丰盛的晚餐。不幸的是，我今天没有收到任何新请求。改天再来跟我谈，好吗？",
        "Look... The sky...": "看...天空...",
        "Someday... Someday... I will fly...": "总有一天...总有一天...我会飞...",
        
        "Magician Instructor": "魔法师导师",
        "Magician weapons": "魔法师武器",
        "Archeologist": "考古学家",
        "Ellinia": "艾琳尼亚",
        "Orbis Station": "奥比斯站",
        "Happyville": "快乐镇",
        "Fairies": "妖精",
        "Pygmy": "矮人",
        "herbs": "草药",
        "fossils": "化石",
        "potions": "药水",
        "equipment": "装备",
        "weapons": "武器",
        "scroll": "卷轴",
        "ticket": "票",
        "ship": "船",
        "village": "村庄",
        "town": "城镇",
        "cliff": "悬崖",
        "property": "领地",
        "research": "研究",
        "homework": "作业",
        "capacity": "容量",
        "burden": "负担",
        "request": "请求",
        "stock": "库存",
        "business": "生意",
        "student": "学生",
        "friend": "朋友",
        "human": "人类",
        "pupil": "学生",
        "stranger": "陌生人",
        "repairs": "修理",
        "treat": "点心",
        "data": "数据",
        "brilliant": "出色的",
        "incredible": "不可思议的",
        "rare": "稀有的",
        "urgent": "紧急的",
        "coveted": "令人垂涎的",
        "gorgeous": "美丽的",
        "violent": "暴力的",
        "rude": "粗鲁的",
        "hearty": "丰盛的",
        "limited": "有限的",
        "shortly": "很快",
        "embark": "出发",
        "swamped": "忙死了",
        "bug off": "走开",
        "uncomfortable": "不自在的",
        "valuable": "宝贵的",
        "unmoving": "不动的",
        "rescued": "被救的",
        "covered": "覆盖的",
        "snow": "雪",
        "sickness": "病",
        "tasty": "美味的",
        "brilliant": "出色的",
        "scold": "责骂",
        "capacity": "容量",
        "equipment": "装备",
        "durable": "耐久的",
        "durability": "耐久度",
        "repair": "修理",
        "blacksmith": "铁匠",
        "station": "车站",
        "clerk": "职员",
        "cabin": "船舱",
        "crew": "乘务员",
        "archeologist": "考古学家",
        "fossil": "化石",
        "herb": "草药",
        "magician": "魔法师",
        "weapon": "武器",
        "potion": "药水",
        "scroll": "卷轴",
        "pet": "宠物",
        "doll": "玩偶",
        "homework": "作业",
        "study": "学习",
        "research": "研究",
        "request": "请求",
        "stock": "库存",
        "business": "生意",
        "student": "学生",
        "friend": "朋友",
        "human": "人类",
        "pupil": "学生",
        "stranger": "陌生人",
        "repair": "修理",
        "treat": "点心",
        "data": "数据",
        "brilliant": "出色的",
        "incredible": "不可思议的",
        "rare": "稀有的",
        "urgent": "紧急的",
        "coveted": "令人垂涎的",
        "gorgeous": "美丽的",
        "violent": "暴力的",
        "rude": "粗鲁的",
        "hearty": "丰盛的",
        "limited": "有限的",
        "shortly": "很快",
        "embark": "出发",
        "swamped": "忙死了",
        "bug off": "走开",
        "uncomfortable": "不自在的",
        "valuable": "宝贵的",
        "unmoving": "不动的",
        "rescued": "被救的",
        "covered": "覆盖的",
        "snow": "雪",
        "sickness": "病",
        "tasty": "美味的",
        "scold": "责骂",
        "capacity": "容量",
        
        "Welcome": "欢迎",
        "Hello": "你好",
        "Hi": "嗨",
        "Goodbye": "再见",
        "Thank you": "谢谢",
        "Please": "请",
        "Sorry": "对不起",
        "Excuse me": "打扰一下",
        "Yes": "是",
        "No": "不",
        "Okay": "好的",
        "Man": "天啊",
        "Hey": "嘿",
        "Wow": "哇",
        "Oh": "哦",
        "Ah": "啊",
        "Hmm": "嗯",
        "Haha": "哈哈",
        "Hehe": "呵呵",
        "Hah": "哈",
        "Whoa": "哇哦",
        "Crap": "该死",
        "Oops": "哎呀",
        "Oh no": "哦不",
        "Hey there": "嘿",
        "There": "那里",
        "Here": "这里",
        "Now": "现在",
        "Today": "今天",
        "Tomorrow": "明天",
        "Yesterday": "昨天",
        "Soon": "很快",
        "Always": "总是",
        "Never": "从不",
        "Maybe": "也许",
        "Please": "请",
        "Can": "能",
        "Will": "将",
        "Would": "会",
        "Could": "可以",
        "Should": "应该",
        "Must": "必须",
        "Need": "需要",
        "Want": "想要",
        "Like": "喜欢",
        "Love": "爱",
        "Hate": "讨厌",
        "Help": "帮助",
        "Talk": "谈话",
        "Speak": "说话",
        "Tell": "告诉",
        "Ask": "问",
        "Answer": "回答",
        "Say": "说",
        "Listen": "听",
        "Look": "看",
        "See": "看见",
        "Find": "找到",
        "Get": "得到",
        "Give": "给",
        "Take": "拿",
        "Make": "制作",
        "Do": "做",
        "Go": "去",
        "Come": "来",
        "Leave": "离开",
        "Stay": "停留",
        "Run": "跑",
        "Walk": "走",
        "Fly": "飞",
        "Swim": "游泳",
        "Eat": "吃",
        "Drink": "喝",
        "Sleep": "睡觉",
        "Work": "工作",
        "Play": "玩",
        "Study": "学习",
        "Read": "读",
        "Write": "写",
        "Think": "想",
        "Know": "知道",
        "Learn": "学习",
        "Remember": "记住",
        "Forget": "忘记",
        "Understand": "理解",
        "Believe": "相信",
        "Hope": "希望",
        "Wish": "愿望",
        "Dream": "梦想",
        "Try": "尝试",
        "Start": "开始",
        "Finish": "完成",
        "Stop": "停止",
        "Continue": "继续",
        "Begin": "开始",
        "End": "结束",
        "Create": "创造",
        "Build": "建造",
        "Destroy": "破坏",
        "Fix": "修复",
        "Break": "打破",
        "Buy": "买",
        "Sell": "卖",
        "Trade": "交易",
        "Bargain": "讨价还价",
        "Pay": "支付",
        "Cost": "花费",
        "Money": "钱",
        "Gold": "金币",
        "Item": "物品",
        "Thing": "东西",
        "Place": "地方",
        "Time": "时间",
        "Day": "天",
        "Night": "夜",
        "Hour": "小时",
        "Minute": "分钟",
        "Second": "秒",
        "Year": "年",
        "Month": "月",
        "Week": "周",
        "Age": "年龄",
        "Life": "生命",
        "Death": "死亡",
        "World": "世界",
        "Land": "土地",
        "Sea": "海",
        "Sky": "天空",
        "Sun": "太阳",
        "Moon": "月亮",
        "Star": "星星",
        "Rain": "雨",
        "Snow": "雪",
        "Wind": "风",
        "Fire": "火",
        "Water": "水",
        "Earth": "土",
        "Tree": "树",
        "Flower": "花",
        "Plant": "植物",
        "Animal": "动物",
        "Bird": "鸟",
        "Fish": "鱼",
        "Dog": "狗",
        "Cat": "猫",
        "Horse": "马",
        "Dragon": "龙",
        "Monster": "怪物",
        "Boss": "BOSS",
        "Enemy": "敌人",
        "Friend": "朋友",
        "Family": "家族",
        "Parent": "父母",
        "Child": "孩子",
        "Son": "儿子",
        "Daughter": "女儿",
        "Brother": "兄弟",
        "Sister": "姐妹",
        "Father": "父亲",
        "Mother": "母亲",
        "Grandfather": "祖父",
        "Grandmother": "祖母",
        "Uncle": "叔叔",
        "Aunt": "阿姨",
        "Cousin": "堂兄弟/表兄弟",
        "Nephew": "侄子",
        "Niece": "侄女",
        "King": "国王",
        "Queen": "女王",
        "Prince": "王子",
        "Princess": "公主",
        "Knight": "骑士",
        "Soldier": "士兵",
        "Warrior": "战士",
        "Mage": "法师",
        "Priest": "牧师",
        "Ninja": "忍者",
        "Assassin": "刺客",
        "Thief": "盗贼",
        "Archer": "弓箭手",
        "Pirate": "海盗",
        "Doctor": "医生",
        "Teacher": "老师",
        "Student": "学生",
        "Merchant": "商人",
        "Shopkeeper": "店主",
        "Farmer": "农夫",
        "Fisherman": "渔夫",
        "Hunter": "猎人",
        "Artist": "艺术家",
        "Musician": "音乐家",
        "Scientist": "科学家",
        "Engineer": "工程师",
        "Worker": "工人",
        "Boss": "老板",
        "Manager": "经理",
        "Leader": "领袖",
        "Hero": "英雄",
        "Villain": "恶棍",
        "Legend": "传说",
        "Myth": "神话",
        "Story": "故事",
        "Tale": "传说",
        "History": "历史",
        "Quest": "任务",
        "Adventure": "冒险",
        "Journey": "旅程",
        "Trip": "旅行",
        "Travel": "旅行",
        "Explore": "探索",
        "Discover": "发现",
        "Secret": "秘密",
        "Magic": "魔法",
        "Power": "力量",
        "Strength": "力量",
        "Weakness": "弱点",
        "Skill": "技能",
        "Ability": "能力",
        "Talent": "天赋",
        "Knowledge": "知识",
        "Wisdom": "智慧",
        "Courage": "勇气",
        "Bravery": "勇敢",
        "Fear": "恐惧",
        "Anger": "愤怒",
        "Joy": "快乐",
        "Sadness": "悲伤",
        "Love": "爱",
        "Hate": "恨",
        "Hope": "希望",
        "Despair": "绝望",
        "Faith": "信仰",
        "Trust": "信任",
        "Loyalty": "忠诚",
        "Honesty": "诚实",
        "Truth": "真相",
        "Lie": "谎言",
        "Friendship": "友谊",
        "Peace": "和平",
        "War": "战争",
        "Battle": "战斗",
        "Fight": "战斗",
        "Victory": "胜利",
        "Defeat": "失败",
        "Win": "赢",
        "Lose": "输",
        "Kill": "杀",
        "Die": "死",
        "Live": "活",
        "Survive": "生存",
        "Save": "拯救",
        "Protect": "保护",
        "Defend": "防御",
        "Attack": "攻击",
        "Hit": "打",
        "Damage": "伤害",
        "Heal": "治愈",
        "Cure": "治愈",
        "Poison": "毒药",
        "Burn": "燃烧",
        "Freeze": "冻结",
        "Stun": "眩晕",
        "Silence": "沉默",
        "Blind": "失明",
        "Confuse": "混乱",
        "Fear": "恐惧",
        "Sleep": "睡眠",
        "Slow": "减速",
        "Speed": "加速",
        "Buff": "增益",
        "Debuff": "减益",
        "Level": "等级",
        "Exp": "经验",
        "HP": "生命值",
        "MP": "魔法值",
        "SP": "技能点",
        "AP": "能力点",
        "Mesos": "金币",
        "Item": "物品",
        "Equip": "装备",
        "Weapon": "武器",
        "Armor": "防具",
        "Helmet": "头盔",
        "Armor": "铠甲",
        "Pants": "裤子",
        "Shoes": "鞋子",
        "Gloves": "手套",
        "Shield": "盾牌",
        "Cape": "披风",
        "Accessory": "饰品",
        "Ring": "戒指",
        "Earring": "耳环",
        "Necklace": "项链",
        "Belt": "腰带",
        "Scroll": "卷轴",
        "Potion": "药水",
        "Elixir": "药剂",
        "Food": "食物",
        "Herb": "草药",
        "Ore": "矿石",
        "Crystal": "水晶",
        "Gem": "宝石",
        "Enchant": "附魔",
        "Upgrade": "升级",
        "Enhance": "强化",
        "Refine": "精炼",
        "Craft": "制作",
        "Forge": "锻造",
        "Smelt": "熔炼",
        "Alchemy": "炼金术",
        "Cooking": "烹饪",
        "Fishing": "钓鱼",
        "Mining": "采矿",
        "Woodcutting": "伐木",
        "Farming": " farming",
        "Pet": "宠物",
        "Mount": "坐骑",
        "Familiar": "精灵",
        "Summon": "召唤",
        "Mercenary": "雇佣兵",
        "Guild": "公会",
        "Party": "组队",
        "Friend": "好友",
        "Enemy": "敌人",
        "Target": "目标",
        "Map": "地图",
        "Dungeon": "地牢",
        "Boss": "BOSS",
        "Field": "野外",
        "Town": "城镇",
        "Village": "村庄",
        "City": "城市",
        "Castle": "城堡",
        "Tower": "塔",
        "Temple": "神殿",
        "Cave": "洞穴",
        "Forest": "森林",
        "Mountain": "山",
        "Beach": "海滩",
        "Ocean": "海洋",
        "River": "河",
        "Lake": "湖",
        "Island": "岛",
        "Volcano": "火山",
        "Desert": "沙漠",
        "Snowfield": "雪原",
        "Glacier": "冰川",
        "Swamp": "沼泽",
        "Jungle": "丛林",
        "Garden": "花园",
        "Park": "公园",
        "Market": "市场",
        "Shop": "商店",
        "Bank": "银行",
        "Storage": "仓库",
        "Hospital": "医院",
        "School": "学校",
        "Library": "图书馆",
        "Museum": "博物馆",
        "Theater": "剧院",
        "Arena": "竞技场",
        "Coliseum": "角斗场",
        "Training": "训练",
        "Academy": "学院",
        "Laboratory": "实验室",
        "Factory": "工厂",
        "Workshop": "工坊",
        "Forge": "锻造厂",
        "Kitchen": "厨房",
        "Bar": "酒吧",
        "Inn": "旅馆",
        "Restaurant": "餐厅",
        "Cafe": "咖啡馆",
        "Hotel": "酒店",
        "Ship": "船",
        "Airship": "飞艇",
        "Train": "火车",
        "Car": "汽车",
        "Bike": "自行车",
        "Boat": "小船",
        "Plane": "飞机",
        "Teleport": "传送",
        "Portal": "传送门",
        "Warp": "瞬移",
        "Scroll": "卷轴",
        "Key": "钥匙",
        "Lock": "锁",
        "Door": "门",
        "Window": "窗户",
        "Wall": "墙",
        "Floor": "地板",
        "Roof": "屋顶",
        "Ceiling": "天花板",
        "Stair": "楼梯",
        "Elevator": "电梯",
        "Escalator": "自动扶梯",
        "Bridge": "桥",
        "Road": "路",
        "Path": "小路",
        "Street": "街道",
        "Avenue": "大道",
        "Square": "广场",
        "Garden": "花园",
        "Park": "公园",
        "Playground": "游乐场",
        "Beach": "海滩",
        "Pool": "游泳池",
        "Fountain": "喷泉",
        "Statue": "雕像",
        "Monument": "纪念碑",
        "Shrine": "神社",
        "Altar": "祭坛",
        "Chapel": "小教堂",
        "Church": "教堂",
        "Mosque": "清真寺",
        "Temple": "寺庙",
        "Pagoda": "宝塔",
        "Pyramid": "金字塔",
        "Ruins": "废墟",
        "Cemetery": "墓地",
        "Graveyard": "墓地",
        "Crypt": "墓穴",
        "Dungeon": "地牢",
        "Labyrinth": "迷宫",
        "Maze": "迷宫",
        "Tunnel": "隧道",
        "Cave": "洞穴",
        "Mine": "矿井",
        "Well": "井",
        "Spring": "泉水",
        "Waterfall": "瀑布",
        "Lava": "熔岩",
        "Fire": "火",
        "Ice": "冰",
        "Snow": "雪",
        "Rain": "雨",
        "Storm": "风暴",
        "Thunder": "雷",
        "Lightning": "闪电",
        "Sun": "太阳",
        "Moon": "月亮",
        "Star": "星星",
        "Cloud": "云",
        "Sky": "天空",
        "Rainbow": "彩虹",
        "Raindrop": "雨滴",
        "Snowflake": "雪花",
        "Wind": "风",
        "Breeze": "微风",
        "Tornado": "龙卷风",
        "Hurricane": "飓风",
        "Earthquake": "地震",
        "Tsunami": "海啸",
        "Volcano": "火山",
        "Eruption": "喷发",
        "Ash": "灰",
        "Smoke": "烟",
        "Fog": "雾",
        "Mist": "薄雾",
        "Haze": "霾",
        "Dust": "灰尘",
        "Sand": "沙",
        "Rock": "石头",
        "Mountain": "山",
        "Hill": "小山",
        "Valley": "山谷",
        "Plateau": "高原",
        "Plain": "平原",
        "Desert": "沙漠",
        "Jungle": "丛林",
        "Forest": "森林",
        "Woods": "树林",
        "Thicket": "灌木丛",
        "Bush": "灌木",
        "Tree": "树",
        "Flower": "花",
        "Plant": "植物",
        "Grass": "草",
        "Leaf": "叶子",
        "Root": "根",
        "Branch": "树枝",
        "Trunk": "树干",
        "Bark": "树皮",
        "Fruit": "水果",
        "Seed": "种子",
        "Vegetable": "蔬菜",
        "Herb": "草药",
        "Mushroom": "蘑菇",
        "Algae": "藻类",
        "Seaweed": "海藻",
        "Coral": "珊瑚",
        "Shell": "贝壳",
        "Fish": "鱼",
        "Shark": "鲨鱼",
        "Whale": "鲸鱼",
        "Dolphin": "海豚",
        "Octopus": "章鱼",
        "Squid": "鱿鱼",
        "Crab": "螃蟹",
        "Shrimp": "虾",
        "Lobster": "龙虾",
        "Jellyfish": "水母",
        "Starfish": "海星",
        "Turtle": "海龟",
        "Frog": "青蛙",
        "Snake": "蛇",
        "Lizard": "蜥蜴",
        "Crocodile": "鳄鱼",
        "Alligator": "短吻鳄",
        "Turtle": "乌龟",
        "Bird": "鸟",
        "Eagle": "鹰",
        "Hawk": "鹰",
        "Owl": "猫头鹰",
        "Parrot": "鹦鹉",
        "Sparrow": "麻雀",
        "Pigeon": "鸽子",
        "Crow": "乌鸦",
        "Raven": "渡鸦",
        "Peacock": "孔雀",
        "Penguin": "企鹅",
        "Duck": "鸭子",
        "Goose": "鹅",
        "Chicken": "鸡",
        "Rooster": "公鸡",
        "Turkey": "火鸡",
        "Ostrich": "鸵鸟",
        "Emu": "鸸鹋",
        "Seagull": "海鸥",
        "Swallow": "燕子",
        "Swan": "天鹅",
        "Crane": "鹤",
        "Flamingo": "火烈鸟",
        "Heron": "苍鹭",
        "Egret": "白鹭",
        "Vulture": "秃鹫",
        "Eagle": "鹰",
        "Hawk": "鹰",
        "Falcon": "猎鹰",
        "Kite": "风筝",
        "Hummingbird": "蜂鸟",
        "Woodpecker": "啄木鸟",
        "Kingfisher": "翠鸟",
        "Osprey": "鱼鹰",
        "Pelican": "鹈鹕",
        "Stork": "鹳",
        "Ibis": "朱鹭",
        "Spoonbill": "琵鹭",
        "Vulture": "秃鹫",
        "Condor": "秃鹰",
        "Albatross": "信天翁",
        "Petrel": "海燕",
        "Gull": "海鸥",
        "Tern": "燕鸥",
        "Auk": "海雀",
        "Puffin": "海鹦",
        "Guillemot": "海鸠",
        "Murre": "海鸦",
        "Dove": "鸽子",
        "Pigeon": "鸽子",
        "Quail": "鹌鹑",
        "Partridge": "鹧鸪",
        "Grouse": "松鸡",
        "Ptarmigan": "雷鸟",
        "Turkey": "火鸡",
        "Pheasant": "雉鸡",
        "Peacock": "孔雀",
        "Guinea fowl": "珍珠鸡",
        "Numidian": "努米底亚",
        "Ostrich": "鸵鸟",
        "Emu": "鸸鹋",
        "Cassowary": "食火鸡",
        "Rhea": "美洲鸵",
        "Kiwi": "几维鸟",
        "Penguin": "企鹅",
        "Dodo": "渡渡鸟",
        "Moas": "恐鸟",
        "Elephant bird": "象鸟",
        "Lion": "狮子",
        "Tiger": "老虎",
        "Leopard": "豹",
        "Cheetah": "猎豹",
        "Jaguar": "美洲豹",
        "Panther": "黑豹",
        "Cougar": "美洲狮",
        "Bobcat": "山猫",
        "Lynx": "猞猁",
        "Ocelot": "豹猫",
        "Serval": "薮猫",
        "Caracal": "狞猫",
        "African wildcat": "非洲野猫",
        "European wildcat": "欧洲野猫",
        "Domestic cat": "家猫",
        "Dog": "狗",
        "Wolf": "狼",
        "Coyote": "郊狼",
        "Jackal": "豺",
        "Fox": "狐狸",
        "Dingo": "澳洲野狗",
        "African wild dog": "非洲野犬",
        "Hyena": "鬣狗",
        "Aardwolf": "土狼",
        "Bear": "熊",
        "Grizzly bear": "灰熊",
        "Polar bear": "北极熊",
        "Black bear": "黑熊",
        "Brown bear": "棕熊",
        "Sloth bear": "懒熊",
        "Sun bear": "马来熊",
        "Panda": "熊猫",
        "Raccoon": "浣熊",
        "Red panda": "小熊猫",
        "Skunk": "臭鼬",
        "Weasel": "鼬",
        "Ferret": "雪貂",
        "Mink": "水貂",
        "Otter": "水獭",
        "Badger": "獾",
        "Wolverine": "狼獾",
        "Honey badger": "蜜獾",
        "Mongoose": "mongoose",
        "Meerkat": "狐獴",
        "Civet": "灵猫",
        "Genet": "麝猫",
        "African palm civet": "非洲棕榈灵猫",
        "Asian palm civet": "亚洲棕榈灵猫",
        "Binturong": "熊狸",
        "Numbat": "袋食蚁兽",
        "Anteater": "食蚁兽",
        "Giant anteater": "大食蚁兽",
        "Tamandua": "小食蚁兽",
        "Silky anteater": "丝毛食蚁兽",
        "Sloth": "树懒",
        "Two-toed sloth": "二趾树懒",
        "Three-toed sloth": "三趾树懒",
        "Armadillo": "犰狳",
        "Nine-banded armadillo": "九带犰狳",
        "Giant armadillo": "大犰狳",
        "Pangolin": "穿山甲",
        "Aardvark": "土豚",
        "Hippopotamus": "河马",
        "Pygmy hippopotamus": "侏儒河马",
        "Rhinoceros": "犀牛",
        "White rhinoceros": "白犀牛",
        "Black rhinoceros": "黑犀牛",
        "Indian rhinoceros": "印度犀牛",
        "Javan rhinoceros": "爪哇犀牛",
        "Sumatran rhinoceros": "苏门答腊犀牛",
        "Elephant": "大象",
        "African bush elephant": "非洲草原象",
        "African forest elephant": "非洲森林象",
        "Asian elephant": "亚洲象",
        "Manatee": "海牛",
        "Dugong": "儒艮",
        "Walrus": "海象",
        "Seal": "海豹",
        "Sea lion": "海狮",
        "Fur seal": "海狗",
        "Monkey": "猴子",
        "Ape": "猿",
        "Chimpanzee": "黑猩猩",
        "Bonobo": "倭黑猩猩",
        "Gorilla": "大猩猩",
        "Orangutan": "猩猩",
        "Gibbon": "长臂猿",
        "Baboon": "狒狒",
        "Mandrill": "山魈",
        "Macaque": "猕猴",
        "Langur": "叶猴",
        "Colobus": "疣猴",
        "Howler monkey": "吼猴",
        "Spider monkey": "蜘蛛猴",
        "Capuchin": "卷尾猴",
        "Squirrel monkey": "松鼠猴",
        "Tamarin": "狨猴",
        "Marmoset": "狨",
        "Lemur": "狐猴",
        "Ring-tailed lemur": "环尾狐猴",
        "Indri": "大狐猴",
        "Aye-aye": "指猴",
        "Slender loris": "瘦猴",
        "Slow loris": "懒猴",
        "Galago": "婴猴",
        "Tree shrew": "树鼩",
        "Flying squirrel": "飞鼠",
        "Squirrel": "松鼠",
        "Chipmunk": "花栗鼠",
        "Mouse": "老鼠",
        "Rat": "大鼠",
        "Hamster": "仓鼠",
        "Gerbil": "沙鼠",
        "Guinea pig": "豚鼠",
        "Chinchilla": "龙猫",
        "Porcupine": "豪猪",
        "Hedgehog": "刺猬",
        "Mole": "鼹鼠",
        "Shrew": "鼩鼱",
        "Mole rat": "鼹鼠",
        "Naked mole rat": "裸鼹鼠",
        "Dormouse": "睡鼠",
        "Jerboa": "跳鼠",
        "Kangaroo": "袋鼠",
        "Wallaby": "沙袋鼠",
        "Koala": "考拉",
        "Wombat": "袋熊",
        "Tasmanian devil": "袋獾",
        "Platypus": "鸭嘴兽",
        "Echidna": "针鼹",
        "Bat": "蝙蝠",
        "Flying fox": "果蝠",
        "Vampire bat": "吸血蝙蝠",
        "Rabbit": "兔子",
        "Hare": "野兔",
        "Pika": "鼠兔",
        "Deer": "鹿",
        "Moose": "驼鹿",
        "Elk": "麋鹿",
        "Caribou": "驯鹿",
        "Reindeer": "驯鹿",
        "Giraffe": "长颈鹿",
        "Okapi": "霍加狓",
        "Camel": "骆驼",
        "Dromedary": "单峰驼",
        "Bactrian camel": "双峰驼",
        "Llama": "羊驼",
        "Alpaca": "羊驼",
        "Vicuna": "骆马",
        "Guanaco": "原驼",
        "Horse": "马",
        "Donkey": "驴",
        "Mule": "骡子",
        "Zebra": "斑马",
        "Ass": "驴",
        "Onager": "野驴",
        "Przewalski's horse": "普氏野马",
        "Cow": "牛",
        "Bull": "公牛",
        "Ox": "牛",
        "Buffalo": "水牛",
        "Bison": "野牛",
        "Yak": "牦牛",
        "Gaur": "野牛",
        "Gayal": "大额牛",
        "Sheep": "羊",
        "Goat": "山羊",
        "Ram": "公羊",
        "Ewe": "母羊",
        "Lamb": "羔羊",
        "Kid": "小山羊",
        "Ibex": "羱羊",
        "Markhor": "捻角山羊",
        "Mouflon": "盘羊",
        "Argali": "盘羊",
        "Antelope": "羚羊",
        "Gazelle": "瞪羚",
        "Springbok": "跳羚",
        "Impala": "黑斑羚",
        "Kudu": "捻角羚",
        "Nyala": "尼亚拉",
        "Bongo": "紫羚",
        "Eland": "大羚羊",
        "Oryx": "大羚羊",
        "Addax": "旋角羚",
        "Saiga": "赛加羚羊",
        "Musk deer": "麝",
        "Water deer": "水鹿",
        "Fallow deer": "黇鹿",
        "Roe deer": "狍",
        "Muntjac": "麂",
        "Pudu": "普度鹿",
        "Mouse deer": "鼷鹿",
        "Tiger": "老虎",
        "Lion": "狮子",
        "Leopard": "豹",
        "Cheetah": "猎豹",
        "Jaguar": "美洲豹",
        "Panther": "黑豹",
        "Cougar": "美洲狮",
        "Bobcat": "山猫",
        "Lynx": "猞猁",
        "Ocelot": "豹猫",
        "Serval": "薮猫",
        "Caracal": "狞猫",
        "African wildcat": "非洲野猫",
        "European wildcat": "欧洲野猫",
        "Domestic cat": "家猫",
        "Dog": "狗",
        "Wolf": "狼",
        "Coyote": "郊狼",
        "Jackal": "豺",
        "Fox": "狐狸",
        "Dingo": "澳洲野狗",
        "African wild dog": "非洲野犬",
        "Hyena": "鬣狗",
        "Aardwolf": "土狼",
        "Bear": "熊",
        "Grizzly bear": "灰熊",
        "Polar bear": "北极熊",
        "Black bear": "黑熊",
        "Brown bear": "棕熊",
        "Sloth bear": "懒熊",
        "Sun bear": "马来熊",
        "Panda": "熊猫",
        "Raccoon": "浣熊",
        "Red panda": "小熊猫",
        "Skunk": "臭鼬",
        "Weasel": "鼬",
        "Ferret": "雪貂",
        "Mink": "水貂",
        "Otter": "水獭",
        "Badger": "獾",
        "Wolverine": "狼獾",
        "Honey badger": "蜜獾",
        "Mongoose": "mongoose",
        "Meerkat": "狐獴",
        "Civet": "灵猫",
        "Genet": "麝猫",
        "African palm civet": "非洲棕榈灵猫",
        "Asian palm civet": "亚洲棕榈灵猫",
        "Binturong": "熊狸",
        "Numbat": "袋食蚁兽",
        "Anteater": "食蚁兽",
        "Giant anteater": "大食蚁兽",
        "Tamandua": "小食蚁兽",
        "Silky anteater": "丝毛食蚁兽",
        "Sloth": "树懒",
        "Two-toed sloth": "二趾树懒",
        "Three-toed sloth": "三趾树懒",
        "Armadillo": "犰狳",
        "Nine-banded armadillo": "九带犰狳",
        "Giant armadillo": "大犰狳",
        "Pangolin": "穿山甲",
        "Aardvark": "土豚",
        "Hippopotamus": "河马",
        "Pygmy hippopotamus": "侏儒河马",
        "Rhinoceros": "犀牛",
        "White rhinoceros": "白犀牛",
        "Black rhinoceros": "黑犀牛",
        "Indian rhinoceros": "印度犀牛",
        "Javan rhinoceros": "爪哇犀牛",
        "Sumatran rhinoceros": "苏门答腊犀牛",
        "Elephant": "大象",
        "African bush elephant": "非洲草原象",
        "African forest elephant": "非洲森林象",
        "Asian elephant": "亚洲象",
        "Manatee": "海牛",
        "Dugong": "儒艮",
        "Walrus": "海象",
        "Seal": "海豹",
        "Sea lion": "海狮",
        "Fur seal": "海狗",
        "Monkey": "猴子",
        "Ape": "猿",
        "Chimpanzee": "黑猩猩",
        "Bonobo": "倭黑猩猩",
        "Gorilla": "大猩猩",
        "Orangutan": "猩猩",
        "Gibbon": "长臂猿",
        "Baboon": "狒狒",
        "Mandrill": "山魈",
        "Macaque": "猕猴",
        "Langur": "叶猴",
        "Colobus": "疣猴",
        "Howler monkey": "吼猴",
        "Spider monkey": "蜘蛛猴",
        "Capuchin": "卷尾猴",
        "Squirrel monkey": "松鼠猴",
        "Tamarin": "狨猴",
        "Marmoset": "狨",
        "Lemur": "狐猴",
        "Ring-tailed lemur": "环尾狐猴",
        "Indri": "大狐猴",
        "Aye-aye": "指猴",
        "Slender loris": "瘦猴",
        "Slow loris": "懒猴",
        "Galago": "婴猴",
        "Tree shrew": "树鼩",
        "Flying squirrel": "飞鼠",
        "Squirrel": "松鼠",
        "Chipmunk": "花栗鼠",
        "Mouse": "老鼠",
        "Rat": "大鼠",
        "Hamster": "仓鼠",
        "Gerbil": "沙鼠",
        "Guinea pig": "豚鼠",
        "Chinchilla": "龙猫",
        "Porcupine": "豪猪",
        "Hedgehog": "刺猬",
        "Mole": "鼹鼠",
        "Shrew": "鼩鼱",
        "Mole rat": "鼹鼠",
        "Naked mole rat": "裸鼹鼠",
        "Dormouse": "睡鼠",
        "Jerboa": "跳鼠",
        "Kangaroo": "袋鼠",
        "Wallaby": "沙袋鼠",
        "Koala": "考拉",
        "Wombat": "袋熊",
        "Tasmanian devil": "袋獾",
        "Platypus": "鸭嘴兽",
        "Echidna": "针鼹",
        "Bat": "蝙蝠",
        "Flying fox": "果蝠",
        "Vampire bat": "吸血蝙蝠",
        "Rabbit": "兔子",
        "Hare": "野兔",
        "Pika": "鼠兔",
        "Deer": "鹿",
        "Moose": "驼鹿",
        "Elk": "麋鹿",
        "Caribou": "驯鹿",
        "Reindeer": "驯鹿",
        "Giraffe": "长颈鹿",
        "Okapi": "霍加狓",
        "Camel": "骆驼",
        "Dromedary": "单峰驼",
        "Bactrian camel": "双峰驼",
        "Llama": "羊驼",
        "Alpaca": "羊驼",
        "Vicuna": "骆马",
        "Guanaco": "原驼",
        "Horse": "马",
        "Donkey": "驴",
        "Mule": "骡子",
        "Zebra": "斑马",
        "Ass": "驴",
        "Onager": "野驴",
        "Przewalski's horse": "普氏野马",
        "Cow": "牛",
        "Bull": "公牛",
        "Ox": "牛",
        "Buffalo": "水牛",
        "Bison": "野牛",
        "Yak": "牦牛",
        "Gaur": "野牛",
        "Gayal": "大额牛",
        "Sheep": "羊",
        "Goat": "山羊",
        "Ram": "公羊",
        "Ewe": "母羊",
        "Lamb": "羔羊",
        "Kid": "小山羊",
        "Ibex": "羱羊",
        "Markhor": "捻角山羊",
        "Mouflon": "盘羊",
        "Argali": "盘羊",
        "Antelope": "羚羊",
        "Gazelle": "瞪羚",
        "Springbok": "跳羚",
        "Impala": "黑斑羚",
        "Kudu": "捻角羚",
        "Nyala": "尼亚拉",
        "Bongo": "紫羚",
        "Eland": "大羚羊",
        "Oryx": "大羚羊",
        "Addax": "旋角羚",
        "Saiga": "赛加羚羊",
        "Musk deer": "麝",
        "Water deer": "水鹿",
        "Fallow deer": "黇鹿",
        "Roe deer": "狍",
        "Muntjac": "麂",
        "Pudu": "普度鹿",
        "Mouse deer": "鼷鹿",
        
        "Zakum": "扎昆",
        "Horntail": "黑龙",
        "Dragon": "龙",
        "Balrog": "巴洛格",
        "Lupin": "卢平",
        "Zombie": "僵尸",
        "Mushroom": "蘑菇",
        "Golem": "魔像",
        "Fairy": "妖精",
        "Spirit": "灵魂",
        "Ghost": "幽灵",
        "Skeleton": "骷髅",
        "Golem": "魔像",
        "Demon": "恶魔",
        "Angel": "天使",
        "Devil": "魔鬼",
        "God": "神",
        "Goddess": "女神",
        "Hero": "英雄",
        "Villain": "恶棍",
        "Legend": "传说",
        "Myth": "神话",
        "Story": "故事",
        "Tale": "传说",
        "History": "历史",
        "Quest": "任务",
        "Adventure": "冒险",
        "Journey": "旅程",
        "Trip": "旅行",
        "Travel": "旅行",
        "Explore": "探索",
        "Discover": "发现",
        "Secret": "秘密",
        "Magic": "魔法",
        "Power": "力量",
        "Strength": "力量",
        "Weakness": "弱点",
        "Skill": "技能",
        "Ability": "能力",
        "Talent": "天赋",
        "Knowledge": "知识",
        "Wisdom": "智慧",
        "Courage": "勇气",
        "Bravery": "勇敢",
        "Fear": "恐惧",
        "Anger": "愤怒",
        "Joy": "快乐",
        "Sadness": "悲伤",
        "Love": "爱",
        "Hate": "恨",
        "Hope": "希望",
        "Despair": "绝望",
        "Faith": "信仰",
        "Trust": "信任",
        "Loyalty": "忠诚",
        "Honesty": "诚实",
        "Truth": "真相",
        "Lie": "谎言",
        "Friendship": "友谊",
        "Peace": "和平",
        "War": "战争",
        "Battle": "战斗",
        "Fight": "战斗",
        "Victory": "胜利",
        "Defeat": "失败",
        "Win": "赢",
        "Lose": "输",
        "Kill": "杀",
        "Die": "死",
        "Live": "活",
        "Survive": "生存",
        "Save": "拯救",
        "Protect": "保护",
        "Defend": "防御",
        "Attack": "攻击",
        "Hit": "打",
        "Damage": "伤害",
        "Heal": "治愈",
        "Cure": "治愈",
        "Poison": "毒药",
        "Burn": "燃烧",
        "Freeze": "冻结",
        "Stun": "眩晕",
        "Silence": "沉默",
        "Blind": "失明",
        "Confuse": "混乱",
        "Fear": "恐惧",
        "Sleep": "睡眠",
        "Slow": "减速",
        "Speed": "加速",
        "Buff": "增益",
        "Debuff": "减益",
        "Level": "等级",
        "Exp": "经验",
        "HP": "生命值",
        "MP": "魔法值",
        "SP": "技能点",
        "AP": "能力点",
        "Mesos": "金币",
        "Item": "物品",
        "Equip": "装备",
        "Weapon": "武器",
        "Armor": "防具",
        "Helmet": "头盔",
        "Armor": "铠甲",
        "Pants": "裤子",
        "Shoes": "鞋子",
        "Gloves": "手套",
        "Shield": "盾牌",
        "Cape": "披风",
        "Accessory": "饰品",
        "Ring": "戒指",
        "Earring": "耳环",
        "Necklace": "项链",
        "Belt": "腰带",
        "Scroll": "卷轴",
        "Potion": "药水",
        "Elixir": "药剂",
        "Food": "食物",
        "Herb": "草药",
        "Ore": "矿石",
        "Crystal": "水晶",
        "Gem": "宝石",
        "Enchant": "附魔",
        "Upgrade": "升级",
        "Enhance": "强化",
        "Refine": "精炼",
        "Craft": "制作",
        "Forge": "锻造",
        "Smelt": "熔炼",
        "Alchemy": "炼金术",
        "Cooking": "烹饪",
        "Fishing": "钓鱼",
        "Mining": "采矿",
        "Woodcutting": "伐木",
        "Farming": " farming",
        "Pet": "宠物",
        "Mount": "坐骑",
        "Familiar": "精灵",
        "Summon": "召唤",
        "Mercenary": "雇佣兵",
        "Guild": "公会",
        "Party": "组队",
        "Friend": "好友",
        "Enemy": "敌人",
        "Target": "目标",
        "Map": "地图",
        "Dungeon": "地牢",
        "Boss": "BOSS",
        "Field": "野外",
        "Town": "城镇",
        "Village": "村庄",
        "City": "城市",
        "Castle": "城堡",
        "Tower": "塔",
        "Temple": "神殿",
        "Cave": "洞穴",
        "Forest": "森林",
        "Mountain": "山",
        "Beach": "海滩",
        "Ocean": "海洋",
        "River": "河",
        "Lake": "湖",
        "Island": "岛",
        "Volcano": "火山",
        "Desert": "沙漠",
        "Snowfield": "雪原",
        "Glacier": "冰川",
        "Swamp": "沼泽",
        "Jungle": "丛林",
        "Garden": "花园",
        "Park": "公园",
        "Market": "市场",
        "Shop": "商店",
        "Bank": "银行",
        "Storage": "仓库",
        "Hospital": "医院",
        "School": "学校",
        "Library": "图书馆",
        "Museum": "博物馆",
        "Theater": "剧院",
        "Arena": "竞技场",
        "Coliseum": "角斗场",
        "Training": "训练",
        "Academy": "学院",
        "Laboratory": "实验室",
        "Factory": "工厂",
        "Workshop": "工坊",
        "Forge": "锻造厂",
        "Kitchen": "厨房",
        "Bar": "酒吧",
        "Inn": "旅馆",
        "Restaurant": "餐厅",
        "Cafe": "咖啡馆",
        "Hotel": "酒店",
        "Ship": "船",
        "Airship": "飞艇",
        "Train": "火车",
        "Car": "汽车",
        "Bike": "自行车",
        "Boat": "小船",
        "Plane": "飞机",
        "Teleport": "传送",
        "Portal": "传送门",
        "Warp": "瞬移",
        "Scroll": "卷轴",
        "Key": "钥匙",
        "Lock": "锁",
        "Door": "门",
        "Window": "窗户",
        "Wall": "墙",
        "Floor": "地板",
        "Roof": "屋顶",
        "Ceiling": "天花板",
        "Stair": "楼梯",
        "Elevator": "电梯",
        "Escalator": "自动扶梯",
        "Bridge": "桥",
        "Road": "路",
        "Path": "小路",
        "Street": "街道",
        "Avenue": "大道",
        "Square": "广场",
        "Garden": "花园",
        "Park": "公园",
        "Playground": "游乐场",
        "Beach": "海滩",
        "Pool": "游泳池",
        "Fountain": "喷泉",
        "Statue": "雕像",
        "Monument": "纪念碑",
        "Shrine": "神社",
        "Altar": "祭坛",
        "Chapel": "小教堂",
        "Church": "教堂",
        "Mosque": "清真寺",
        "Temple": "寺庙",
        "Pagoda": "宝塔",
        "Pyramid": "金字塔",
        "Ruins": "废墟",
        "Cemetery": "墓地",
        "Graveyard": "墓地",
        "Crypt": "墓穴",
        "Dungeon": "地牢",
        "Labyrinth": "迷宫",
        "Maze": "迷宫",
        "Tunnel": "隧道",
        "Cave": "洞穴",
        "Mine": "矿井",
        "Well": "井",
        "Spring": "泉水",
        "Waterfall": "瀑布",
        "Lava": "熔岩",
        "Fire": "火",
        "Ice": "冰",
        "Snow": "雪",
        "Rain": "雨",
        "Storm": "风暴",
        "Thunder": "雷",
        "Lightning": "闪电",
        "Sun": "太阳",
        "Moon": "月亮",
        "Star": "星星",
        "Cloud": "云",
        "Sky": "天空",
        "Rainbow": "彩虹",
        "Raindrop": "雨滴",
        "Snowflake": "雪花",
        "Wind": "风",
        "Breeze": "微风",
        "Tornado": "龙卷风",
        "Hurricane": "飓风",
        "Earthquake": "地震",
        "Tsunami": "海啸",
        "Volcano": "火山",
        "Eruption": "喷发",
        "Ash": "灰",
        "Smoke": "烟",
        "Fog": "雾",
        "Mist": "薄雾",
        "Haze": "霾",
        "Dust": "灰尘",
        "Sand": "沙",
        "Rock": "石头",
        "Mountain": "山",
        "Hill": "小山",
        "Valley": "山谷",
        "Plateau": "高原",
        "Plain": "平原",
        "Desert": "沙漠",
        "Jungle": "丛林",
        "Forest": "森林",
        "Woods": "树林",
        "Thicket": "灌木丛",
        "Bush": "灌木",
        "Tree": "树",
        "Flower": "花",
        "Plant": "植物",
        "Grass": "草",
        "Leaf": "叶子",
        "Root": "根",
        "Branch": "树枝",
        "Trunk": "树干",
        "Bark": "树皮",
        "Fruit": "水果",
        "Seed": "种子",
        "Vegetable": "蔬菜",
        "Herb": "草药",
        "Mushroom": "蘑菇",
        "Algae": "藻类",
        "Seaweed": "海藻",
        "Coral": "珊瑚",
        "Shell": "贝壳",
        "Fish": "鱼",
        "Shark": "鲨鱼",
        "Whale": "鲸鱼",
        "Dolphin": "海豚",
        "Octopus": "章鱼",
        "Squid": "鱿鱼",
        "Crab": "螃蟹",
        "Shrimp": "虾",
        "Lobster": "龙虾",
        "Jellyfish": "水母",
        "Starfish": "海星",
        "Turtle": "海龟",
        "Frog": "青蛙",
        "Snake": "蛇",
        "Lizard": "蜥蜴",
        "Crocodile": "鳄鱼",
        "Alligator": "短吻鳄",
        "Turtle": "乌龟",
        "Bird": "鸟",
        "Eagle": "鹰",
        "Hawk": "鹰",
        "Owl": "猫头鹰",
        "Parrot": "鹦鹉",
