import os
import re
import glob

def translate_value(text):
    translations = {
        "Silver": "西尔弗",
        "Weapon Seller": "武器商人",
        "Sale! Sale! Crazy prices!": "大甩卖！大甩卖！疯狂低价！",
        "Come check out my goods! Hahaha!": "快来看看我的商品！哈哈哈！",
        "Natasha": "娜塔莎",
        "Armor Seller": "防具商人",
        "Anyone that steals from me shall face my wrath!": "谁偷我的东西就要面对我的怒火！",
        "Let's see... I'm ready for business.": "让我看看...我准备好做生意了。",
        "Welcome all! I've got goods you'll definitely want to take a look at!": "欢迎光临！我有你绝对想看看的商品！",
        "Mina": "米娜",
        "Merchant": "商人",
        "Whoa there. Don't even think of stealing from me.": "哇哦。别想偷我的东西。",
        "Grab some potions before you continue your journey.": "在你继续旅程前拿些药水吧。",
        "Low prices! Really looow!": "低价！真的很低！",
        "Phil": "菲尔",
        "Open your Item Inventory and you'll find the Equip, Use, Set-up, Etc, and Cash tabs.": "打开你的物品栏，你会发现装备、消耗、设置、其他和现金标签。",
        "Items you pick up are automatically stored in the appropriate item tab. Convenient, eh?": "你拾取的物品会自动存放到相应的物品标签中。很方便吧？",
        "Double-click an item in the Item Inventory to use it.": "双击物品栏中的物品即可使用。",
        "Teo": "特奥",
        "Hey, have you seen a whale around here? Hmmm. Where'd it go?": "嘿，你在这附近看到鲸鱼了吗？嗯...它去哪了？",
        "I heard that #p1012101# is sick again. Tragic...": "我听说#p1012101#又生病了。真悲剧...",
        "Oh. You delivered the #b#t4031006##k to #p1012101#! Thanks. Now #p1012101# can get better. Wow, this #t4031004# is beautiful.": "哦。你把#b#t4031006##k交给#p1012101#了！谢谢。现在#p1012101#可以康复了。哇，这个#t4031004#真漂亮。",
        "Haven't been able to shave in months. My chin itches like crazy!": "几个月没刮胡子了。我的下巴痒得要命！",
        "Nothing compares to sailing along a beautiful coast... That's the life, I tell ya!": "没有什么能比得上沿着美丽海岸航行...这才是生活，我跟你说！",
        "Pason": "帕森",
        "Tour Guide": "导游",
        "There's a gorgeous beach called Florina Beach near Victoria Island...": "维多利亚岛附近有一个美丽的海滩叫弗洛里纳海滩...",
        "Do you want to head to Florina Beach?": "你想去弗洛里纳海滩吗？",
        "Mr. Goldstein": "戈尔茨坦先生",
        "Buddy List Admin": "好友列表管理员",
        "Hey, there! Is your buddy list full?": "嘿！你的好友列表满了吗？",
        "If you need to expand your buddy list, do some business with me! Harharhar!": "如果你需要扩展好友列表，跟我做笔交易吧！哈哈哈！",
        "VIP Cab": "VIP出租车",
        "Mr. Kim": "金先生",
        "Storage Keeper": "仓库管理员",
        "Need a place to store your items and mesos? Talk to me!": "需要地方存放你的物品和金币吗？跟我谈谈！",
        "My storage is safe and secure, so you can sleep easy at night.": "我的仓库安全可靠，所以你晚上可以安心睡觉。",
        "Chef": "厨师",
        "Who am I? Well... Who AM I?": "我是谁？嗯...我到底是谁？",
        "If you have a secret scroll, would you mind showing it to me?": "如果你有秘密卷轴，介意给我看看吗？",
        "What are you here for? Attracted to my ravishing good looks?": "你来这里做什么？被我迷人的外表吸引了？",
        "If you're done, I suggest you leave. I'm a very busy person...": "如果你完事了，我建议你离开。我是个很忙的人...",
        "Jane": "简",
        "I wanna travel, too...": "我也想去旅行...",
        "Why won't my dad let me travel around the world?": "为什么我爸爸不让我环游世界？",
        "It's you! Thanks for the materials earlier. If you need something, please let me know.": "是你！谢谢你之前的材料。如果你需要什么，请告诉我。",
        "My dream is to travel the world, just like you. But my father won't let me.": "我的梦想是像你一样环游世界。但我爸爸不让。",
        "Am I cute? Hee hee!": "我可爱吗？嘻嘻！",
        "Captain Al": "阿尔船长",
        "Family Guide": "家族向导",
        "Try being in a Family. You'll realize how much easier life can get with a supportive family...": "试着加入一个家族吧。你会发现有一个支持你的家族生活会变得多么轻松...",
        "Hello there, I'm Captain Al. I've been acting as the leader of a Family for 30 years now. Do you have any questions about the Family?": "你好，我是阿尔船长。我担任家族领袖已经30年了。你有关于家族的问题吗？",
        "Rina": "莉娜",
        "Evan, when did you get so strong? Haha, you're as mighty as a real adventurer!": "埃文，你什么时候变得这么强了？哈哈，你就像一个真正的冒险家一样强大！",
        "Evan, you saved Camila? That's great! I'd hate to think what would have happened to her if you weren't there...": "埃文，你救了卡米拉？太棒了！真不敢想象如果你不在那里会发生什么...",
        "Can't anyone get me some Blue Mushroom Caps? There must be someone nice enough. Oh Evan, I wasn't talking to you... Please don't try anything foolish!": "没人能给我拿些蓝蘑菇帽吗？一定有好心人。哦埃文，我不是在跟你说话...请别做傻事！",
        "If you want to become a bowman, please go see Athena Pierce, who resides in the inner part of the park.": "如果你想成为弓箭手，请去见住在公园内部的雅典娜·皮尔斯。",
        "Have you met with Athena Pierce, the one who watches over and takes care of our town?": "你见过守护我们城镇的雅典娜·皮尔斯吗？",
        "Hmm... Is Ronnie all right? I can't find him... I was thinking of fixing him a nice plate of Unagi.": "嗯...罗尼还好吗？我找不到他...我本来想给他做一份美味的鳗鱼饭。",
        "Oh... You're the one who gave the stuff back? So what's up? Is #p1012102 doing fine? If you get to #m100000000# someday, please say hello to #p1012102# for me.": "哦...是你把东西还回来的？怎么了？#p1012102还好吗？如果你某天到#m100000000#，请替我向#p1012102#问好。",
        "This town was founded by bowmen. If you want to become a bowman, please meet with #r#p1012100##k... She will help you. What? You don't know #r#p1012100##k? She saved our town from monsters long ago. Of course, it's safe now. She's our town's hero.": "这个城镇是由弓箭手建立的。如果你想成为弓箭手，请去见#r#p1012100##k...她会帮助你。什么？你不认识#r#p1012100##k？她很久以前从怪物手中拯救了我们的城镇。当然，现在安全了。她是我们城镇的英雄。",
        "Karl": "卡尔",
        "Check out my cheap prices!": "看看我的便宜价格！",
        "Come check it out! Ahahahah!": "快来看看！哈哈哈！",
        "Sam": "山姆",
        "Hmm...I'm ready for business now...": "嗯...我现在准备好做生意了...",
        "Ahem! I only deal with the finest of items...": "咳！我只经营最好的物品...",
        "Regular Cab in Victoria": "维多利亚普通出租车",
        "Dr. Squint": "斯奎因特医生",
        "Doctor w/o License": "无证医生",
        "I've been wearing these for so long, I can barely see what's in front of me...": "我戴这些太久了，几乎看不清眼前的东西...",
        "Ah, you want to get your face done? *Cough, cough.*": "啊，你想做面部整形？*咳咳。*",
        "Plastic surgery... Let me take care of it... Haha. Wait, where's your face?": "整形手术...让我来处理...哈哈。等等，你的脸在哪？",
        "Vicious": "维瑟斯",
        "Item Maker": "物品制作师",
        "You need something?": "你需要什么？",
        "Chief Stan": "斯坦酋长",
        "What an obedient child. I'm jealous of Gustav. You're so unlike Alex. Where could that kid have gone?": "多么听话的孩子。我嫉妒古斯塔夫。你和亚历克斯完全不同。那孩子能去哪里呢？",
        "I'm sorry if you don't like the Training Center I recommended. Unfortunately, it's the only one around... ": "如果你不喜欢我推荐的训练中心，我很抱歉。不幸的是，这是附近唯一的一个...",
        "Hmm... I didn't think you would actually get the Fairy's Tentacles...": "嗯...我没想到你真的拿到了妖精的触手...",
        "I thought Nella was sharp and reliable. Could I have been wrong? Hmm...": "我以为内拉聪明可靠。难道我错了？嗯...",
        "This is getting more and more complicated. Who would want to hurt a small town like ours?": "事情变得越来越复杂了。谁会想伤害我们这样的小镇？",
        "I'm relieved that Camila is okay.": "卡米拉没事，我松了一口气。",
        "Thank you so much. Forget defeating Zakum or Horntail. You're the true hero, defender of Henesys!": "非常感谢你。忘了击败扎昆或黑龙吧。你才是真正的英雄，赫尼斯的守护者！",
        "Where did my son go...?": "我的儿子去哪了...？",
        "Hey, you! I strongly suggest you don't do anything stupid in town...": "嘿，你！我强烈建议你不要在镇上做任何傻事...",
        "My Son...! That ungrateful kid... He just ran out without listening to me. I'll never ever forgive him...! He can never come back here again...! ": "我的儿子...！那个忘恩负义的孩子...他不听我的话就跑出去了。我永远不会原谅他...！他永远不能再回到这里...！",
        "Did you give the gold watch to Alex? I feel so lonely without him... Please tell him that I forgive him and he can come home now.": "你把金表交给亚历克斯了吗？没有他我感到很孤独...请告诉他我原谅他了，他现在可以回家了。",
        "Doofus": "笨蛋",
        "Pet Food Merchant": "宠物食品商人",
        "Pet food for your precious pet! On sale!": "给你珍贵宠物的宠物食品！特价！",
        "Do you need some food for your pet?": "你需要给宠物买些食物吗？",
        "Cloy": "克洛伊",
        "Pet Master": "宠物大师",
        "Do you have any questions about pets? Ask me anything you want...": "你有关于宠物的问题吗？尽管问我...",
        "Are you raising a pet? If you have any questions, feel free to ask.": "你在养宠物吗？如果你有任何问题，请随时问。",
        "Trainer Bartos": "训练师巴托斯",
        "Pet Trainer": "宠物训练师",
        "What? Your pet turned into a doll? Of course... It was originally a doll that came to life through a special magic.": "什么？你的宠物变成玩偶了？当然...它本来就是一个通过特殊魔法活过来的玩偶。",
        "Heheheh... If you need to train your pet, I'll take care of it...": "嘿嘿嘿...如果你需要训练你的宠物，我来处理...",
        "Mr. Lee": "李先生",
        "You need a place to store your items and mesos? This is just the place for you!": "需要地方存放你的物品和金币吗？这里正是你需要的地方！",
        "My storage is safe and secure, so no worries!": "我的仓库安全可靠，所以不用担心！",
        "Natalie": "娜塔莉",
        "Hair Salon Owner": "美发沙龙老板",
        "Do you like my hairstyle? We hairdressers have to keep up with the latest trends!": "你喜欢我的发型吗？我们美发师必须跟上最新潮流！",
        "Tired of your hairdo? Here, let me make it look nice and pretty for you...": "厌倦你的发型了？来，让我帮你打扮得漂漂亮亮的...",
        "Anne": "安妮",
        "Is mom busy...?": "妈妈忙吗...？",
        "I can only do this by myself for so long...": "我只能自己做这么久...",
        "I'm Anne, the daughter of Dr. Betty": "我是安妮，贝蒂医生的女儿",
        "Hey, you wanna hang out with me?": "嘿，你想和我一起玩吗？",
        "Hmmm...": "嗯...",
        "Henesys Forest": "赫尼斯森林",
        "Regular Cab": "普通出租车",
        "Mr. Wang": "王先生",
        "Burnt Sword": "烧焦的剑",
        "(There's a burnt sword...)": "（有一把烧焦的剑...）",
        "...": "...",
        "The Excavator Board": "挖掘机公告板",
        "Any form of advertisement attached to this board without the consent of the Excavator Camp will be fined 3,000,000 mesos.": "未经挖掘机营地同意在本公告板上张贴任何形式的广告将被罚款300万金币。",
        "Fountain Statue": "喷泉雕像",
        "Serabi the Fairy": "妖精塞拉比",
        "We sell various kinds of armors here...": "我们这里卖各种防具...",
        "Come take a look.": "来看看吧。",
        "Louis": "路易斯",
        "If you want to leave this place, come talk to me.": "如果你想离开这里，来跟我谈谈。",
        "Mr. Park": "朴先生",
        "Purin": "布丁",
        "Crewmember": "船员",
        "Is anything bothering you on this trip? I hope you enjoy the ride.": "这次旅行有什么困扰你吗？希望你旅途愉快。",
        "Anyone that wants to leave the ship and return to the starting point, please come talk to me.": "任何想离开船并返回起点的人，请过来跟我谈谈。",
        "The ship is about to leave. Please wait one moment.": "船即将离开。请稍等片刻。",
        "El Moth": "埃尔莫斯",
        "Scroll Seller": "卷轴商人",
        "I can make scrolls easily!": "我可以轻松制作卷轴！",
        "I know exactly what kind of scrolls you want.": "我确切知道你想要什么样的卷轴。",
        "Betty": "贝蒂",
        "Lots of work, not enough help...": "工作很多，帮手不够...",
        "Hey, if you got some time, can you help me out here?": "嘿，如果你有时间，能来帮我一下吗？",
        "I'm Betty the biologist. There are so many things to work on, but I'm always lacking time.": "我是生物学家贝蒂。有很多事情要做，但我总是没时间。",
        "Thank you so much for your help! Couldn't have come at a better time!": "非常感谢你的帮助！来得正是时候！",
        "Estelle": "埃斯特尔",
        "It's not easy to make a new sauce.": "制作新酱汁不容易。",
        "No, this is not it! I need a distinctive flavor.": "不，不是这个！我需要一种独特的味道。",
        "I'm Estelle, and I love to cook!": "我是埃斯特尔，我喜欢烹饪！",
        "Did you like the sauce I made the other day? Did it help you on your cooking?": "你喜欢我前几天做的酱汁吗？对你的烹饪有帮助吗？",
        "Man...": "真是...",
        "Reef": "里夫",
        "...may you be cursed...": "...愿你被诅咒...",
        "I can't see... But darkness.": "我看不见...只有黑暗。",
        "...Don't know when... But I am now...  Getting used to committing sin...": "...不知道什么时候...但我现在...习惯了犯罪...",
        "If I apologize... Will it be accepted?": "如果我道歉...会被接受吗？",
        "Corner of the Magic Library": "魔法图书馆角落",
        "Small Tree Stump": "小树桩",
        "Luke": "卢克",
        "Hey, it's you! Am I falling asleep again? Well, I was actually called out the other day for doing that, so I've been trying NOT to these days. It's dangerous around here, so please be careful.": "嘿，是你！我又睡着了吗？嗯，前几天我因为这样被说了，所以这些天我一直努力不这样做。这附近很危险，所以请小心。",
        "Zzz...": "呼噜...",
        "... ... ... Zzz...": "... ... ...呼噜...",
        "This is the way to the...dun...geon... zzzzzzzz ...": "这是去...地... dungeon...呼噜呼噜...",
        "Okay, who just woke me up?! I hate anyone that wakes me up from my nap... Huh? What am I doing? What do you think I'm doing? Of course I'm guarding the entrance! This is the entrance to the #bVictoria Island : Center Dungeon#k. You have to be careful in there; the monsters you've faced don't even compare to the ones you're about to face in here. I suggest you don't go in there unless you can protect yourself. Okay, nap time!": "好吧，谁刚才叫醒我了？！我讨厌任何在我午睡时叫醒我的人...哈？我在做什么？你以为我在做什么？我当然在守卫入口！这是#b维多利亚岛：中央地牢#k的入口。你在里面必须小心；你面对过的怪物甚至无法与你即将在这里面对的怪物相比。除非你能保护自己，否则我建议你不要进去。好了，午睡时间！",
        "Mike": "迈克",
        "I found this old document the other day and it had something about this mythical item. #b#t4021009##k and #b#t4003002##k seem like items that have something to do with the fairies at Ellinia. Maybe #t4001005# has to do with the Golems that the old mages made. #b#t4001006##k reminds me of a flaming dragon...": "前几天我发现了这份旧文件，里面有关于这个神秘物品的内容。#b#t4021009##k和#b#t4003002##k似乎与艾琳尼亚的妖精有关。也许#t4001005#与古老法师制造的魔像有关。#b#t4001006##k让我想起了一条燃烧的龙...",
        "... ... ...Zzz...": "... ... ...呼噜...",
        "Fanzy": "范齐",
        "Meooow!": "喵！",
        "Mrow!": "喵呜！",
        "Meoooow!": "喵~！",
        "Meow": "喵",
        "If you want to get out of here, talk to me. Meow!": "如果你想离开这里，跟我谈谈。喵！",
        "You can do it.": "你能做到的。",
        "Meooooow": "喵~~~~",
        "Luvar": "卢瓦尔",
        "If this continues, all the Lupins will become zombies!": "如果这样继续下去，所有的卢平都会变成僵尸！",
        "We must do something...": "我们必须做点什么...",
        "I am Luvar, a disciple of Grendel the Really Old.": "我是卢瓦尔，真正古老的格伦德尔的弟子。",
        "a pile of flowers": "一堆花",
        "a pile of herbs": "一堆草药",
        "Cutthroat Manny": "杀手曼尼",
        "You need a weapon? Our store specializes in weapons for thieves...": "你需要武器吗？我们商店专门经营盗贼武器...",
        "All right! Take your pick!": "好的！随便选！",
        "Don Hwang": "黄老板",
        "Hello there, do you need something?": "你好，你需要什么吗？",
        "There's no way you're going to overpay for an item here!": "在这里你绝不会为一件物品多付钱！",
        "Dr. Faymus": "费穆斯医生",
        "Pharmacist": "药剂师",
        "You need potions? Here you go... I have PLENTY!": "你需要药水吗？给你...我有很多！",
        "Here! Take your pick!": "来！随便选！",
        "Alex": "亚历克斯",
        "Ah... I'm bored ...": "啊...我好无聊...",
        "It's been a months since I ran away from home, and frankly I'm sick of wandering around strange places now. But I feel weird about going back home...": "我离家出走已经一个月了，说实话我现在厌倦了在陌生的地方游荡。但我对回家感到奇怪...",
        "Thanks for the help the other day. I'd love to go back home, but I have to at least say my goodbyes to everyone that helped me out here. These people will actually miss me, you know...": "谢谢你前几天的帮助。我很想回家，但我至少要向所有在这里帮助过我的人道别。这些人真的会想念我的，你知道...",
        "Dark Lord": "黑暗领主",
        "Thief Instructor": "盗贼导师",
        "Those who want to become a thief, come...": "想成为盗贼的人，来吧...",
        "JM From tha Streetz": "街头JM",
        "Item Creator": "物品创造者",
        "Hmm... Can I see you for a sec...?": "嗯...我能见你一下吗...？",
        "Hmm... the items you need... I have them all.": "嗯...你需要的物品...我都有。",
        "Got some secret business to take care of? You've come to the right place... Kerning City's the place to be for dangerous transactions.": "有秘密生意要处理？你来对地方了...凯宁市是进行危险交易的地方。",
        "Chris": "克里斯",
        "Ore Refiner": "矿石精炼师",
        "Do you have any raw ore or jewels by any chance? Allow me to take care of the rest...": "你碰巧有原矿或宝石吗？让我来处理剩下的...",
        "Whew... I'm tired. I'll take a break for now.": "呼...我累了。我先休息一下。",
        "Denma the Owner": "老板丹玛",
        "Plastic Surgeon": "整形外科医生",
        "Do you want to have plastic surgery? Let me take care of you, then...": "你想做整形手术吗？那让我来照顾你...",
        "It's not a bad idea to change your face up every once in a while.": "偶尔换个脸也不错。",
        "Dr. Feeble": "费布尔医生",
        "I've been wearing these for so long, I can barely see what's in front of me now...": "我戴这些太久了，现在几乎看不清眼前的东西...",
        "Ah... Want some plastic surgery? *Cough cough.*": "啊...想要整形手术吗？*咳咳。*",
        "Plastic surgery...? Allow me... Haha... By the way, where is your face...?": "整形手术...？让我来...哈哈...顺便问一下，你的脸在哪...？",
        "Jake": "杰克",
        "Subway Worker": "地铁工人",
        "Do you want in? Then please purchase a ticket here.": "你想进去吗？那么请在这里买票。",
        "No one is allowed in without a ticket.": "没有票不准进入。",
        "Monster who like darkness often find their ways into the Subway, so be careful!": "喜欢黑暗的怪物经常进入地铁，所以要小心！",
        "The Ticket Gate": "检票口",
        "Treasure Chest": "宝箱",
        "Exit": "出口",
        "Mong from Kong": "来自孔的蒙",
        "Internet Cafe Worker": "网吧工作人员",
        "Hey... Are you logging in from an internet cafe? Come on in...": "嘿...你是从网吧登录的吗？进来吧...",
        "There's an Internet Cafe here, but not everyone can go in...": "这里有一个网吧，但不是每个人都能进去...",
        "Computer": "电脑",
        "Vending Machine": "自动售货机",
        "Billy": "比利",
        "Internet Cafe Owner": "网吧老板",
        "Is the game not working? Ahhh... Try restarting the computer.": "游戏不工作了吗？啊...试着重启电脑。",
        "Do you keep seeing a blue screen? Ahhh... Try restarting the computer.": "你一直看到蓝屏吗？啊...试着重启电脑。",
        "Mr. Hong": "洪先生",
        "You need a place to store your items and mesos? Here it is!": "需要地方存放你的物品和金币吗？这里就是！",
        "Don Giovanni": "唐·乔瓦尼",
        "Hahahah! Welcome to my hair salon! Have a seat!": "哈哈哈！欢迎来到我的美发沙龙！请坐！",
        "Don't you feel super powerful when you have POWERFUL-looking hair?": "当你有一头看起来很强大的头发时，你不觉得自己超级强大吗？",
        "Hey, you! You seem to be having a bad-hair day... How about letting me take care of it?": "嘿，你！你今天头发看起来很糟糕...让我来帮你打理一下怎么样？",
        "Andre": "安德烈",
        "Hair Salon Assistant": "美发沙龙助理",
        "Oh no no no no no! YOU need a haircut!": "哦不不不不！你需要理发！",
        "I may not be as good as the Don, but I'm close enough!": "我可能不如唐厉害，但我已经很接近了！",
        "Shumi": "舒米",
        "Oh no... Where could it be...?": "哦不...它能在哪里...？",
        "Crap! I lost my money!": "该死！我丢了钱！",
        "I hope someone can help me out...": "我希望有人能帮我...",
        "Oh my gosh... I lost the coin that my friend lent me... I can't find it!": "哦天哪...我丢了朋友借给我的硬币...我找不到它了！",
        "You helped me out before! I can't thank you enough for getting me out of trouble. I mean, you helped me out three times! I've been much more careful these days. Is that an improvement or what?": "你之前帮过我！我无法感谢你足够让我摆脱困境。我的意思是，你帮了我三次！这些天我更加小心了。这是不是一种进步？",
        "Tulcus": "图尔库斯",
        "If you need any scrolls, come talk to me.": "如果你需要任何卷轴，来跟我谈谈。",
        "It's a piece of cake for me to make scrolls, you know.": "你知道，制作卷轴对我来说是小菜一碟。",
        "Jane Doe": "无名氏",
        "I need to get these bandages off, but where's Dr. Naora?": "我需要把这些绷带取下来，但娜奥拉医生在哪里？",
        "Something's not right. Hey you... You know anything?": "有些不对劲。嘿你...你知道什么吗？",
        "It's... So... Cold": "好...冷...",
        "Well... Where should I go now...? What do I do?": "嗯...我现在该去哪里...？我该怎么办？",
        "Small Street Light": "小街灯",
        "Knocked Trash Can": "被撞倒的垃圾桶",
        "(A trash can that has been knocked down. Contains a piece of paper or two mixed with dirt.)": "（一个被撞倒的垃圾桶。里面有一两张纸混着泥土。）",
        "Subway Trash Can": "地铁垃圾桶",
        "(A trash can in the subway. It is almost overflowing with trash and drinks. Not something you'd like your hands on.)": "（地铁里的垃圾桶。几乎装满了垃圾和饮料。不是你想碰的东西。）",
        "Chrishrama": "克里什拉玛",
        "It's been years and years since Sabitrama and I first came to this place. Yet we still have not discovered the truth...": "我和萨比特拉玛第一次来到这里已经很多年了。但我们仍然没有发现真相...",
        "24 Hr Mobile Store": "24小时移动商店",
        "We have everything except for what we don't have!": "我们什么都有，除了我们没有的！",
        "All right, everyone come check it out!": "好的，大家快来看看！",
        "Mr. Sweatbottom": "斯韦特博顿先生",
        "Sauna Manager": "桑拿经理",
        "A few minutes in the sauna, and you'll feel much better. What do you think? Already working for you?": "在桑拿房里待几分钟，你会感觉好多了。你觉得呢？已经对你起作用了吗？",
        "If you need an item, I have some available, so take a look...": "如果你需要物品，我有一些可用的，来看看...",
        "Mr. Wetbottom": "韦特博顿先生",
        "Ah... You're using the VIP sauna. What do you think? Do you want to make a deal with me?": "啊...你在用VIP桑拿。你觉得怎么样？你想和我做笔交易吗？",
        "Welcome to the VIP sauna of the #m105040300# Hotel. Actually, I need some help here...": "欢迎来到#m105040300#酒店的VIP桑拿。实际上，我这里需要一些帮助...",
        "I'm so glad I got this book back safely. It's my number one treasure, you know. Am I not worried about #p1061004#? The fairies are taking care of him all right, so I'm not worried one bit.": "我很高兴安全找回了这本书。你知道，这是我的头号宝藏。我不担心#p1061004#吗？妖精们把他照顾得很好，所以我一点也不担心。",
        "Sabitrama": "萨比特拉玛",
        "I'm collecting herbs...": "我在收集草药...",
        "Lots of medicinal herbs in this forest. Nothing makes me happier than finding new herbs here!": "这片森林里有很多药材。没有什么比在这里找到新草药更让我开心的了！",
        "It's you! Thanks to the herbs you got me, the medicine is well on its way. It should be done pretty soon. Thanks again for your help.": "是你！多亏了你给我的草药，药已经快好了。应该很快就完成了。再次感谢你的帮助。",
        "Mysterious Statue": "神秘雕像",
        "(A strange statue. You can't tell whether it is laughing or crying.)": "（一尊奇怪的雕像。你分不清它是在笑还是在哭。）",
        "Crumbling Statue": " crumbling雕像",
        "Door of Dimension": "次元门",
        "Sparkling Crystal": "闪闪发光的水晶",
        "The Rememberer": "记忆者",
        "The road to training is long and arduous.": "训练之路漫长而艰巨。",
        "I'm mentally training right now.": "我现在正在进行心理训练。",
        "To train mentally, I need to concentrate 100%.": "要进行心理训练，我需要100%集中注意力。",
        "If you study long enough, you'll be able to float on air.": "如果你学习足够久，你就能在空中漂浮。",
        "Gwin": "格温",
        "...ouch...": "...哎哟...",
        "Mu Young": "穆扬",
        "Master will be worried...": "师父会担心的...",
        "Will I be able to do this alone...?": "我能独自做到吗...？",
        "Never thought I'd run into another person in a place like this! I'm Mu Young, the apprentice of master Manji.  ": "没想到会在这样的地方遇到另一个人！我是穆扬，万吉大师的徒弟。",
        "The revival of Balrog must be stopped at all costs. Please help me. ": "必须不惜一切代价阻止巴洛格的复活。请帮助我。",
        "Suspicious Man": "可疑男子",
        "How are you?": "你好吗？",
        "How long have I been here...that is...": "我在这里多久了...那是...",
        "I am a bit hungry.": "我有点饿了。",
        "Nice weather today!": "今天天气真好！",
        "Tristan's Spirit": "特里斯坦的灵魂",
        "Ugh...": "呃...",
        "a pile of pink flowers": "一堆粉色的花",
        "a pile of blue flowers": "一堆蓝色的花",
        "a pile of white flowers": "一堆白色的花",
        "Wanted : G. Mushroom": "通缉：G.蘑菇",
        "Are you strong enough to defeat these?": "你足够强大来击败这些吗？",
        "No matter how many you defeat, their numbers don't decrease...": "无论你击败多少，它们的数量都不会减少...",
        "Wanted : Curse Eye": "通缉：诅咒之眼",
        "Wanted : Evil Eye": "通缉：邪恶之眼",
        "Wanted : Cold Eye": "通缉：冷眼",
        "Wanted : Z. Mushroom": "通缉：Z.蘑菇",
        "Wanted : H. Mushroom": "通缉：H.蘑菇",
        "Wanted : Jr. Boogie": "通缉：小布吉",
        "Wanted : Drake": "通缉：德雷克",
        "Cave Wall of Evil Eye": "邪恶之眼洞壁",
        "Shaman Rock": "萨满岩石",
        "Mysterious Piece of Paper": "神秘纸片",
        "Underground Temple Entrance": "地下神殿入口",
        "Strange Looking Statue ": "长相奇怪的雕像",
        "Monstrous Looking Statue ": "长相怪异的雕像",
        "Stands With Bulls": "与公牛并肩",
        "Be ever vigilant! I will protect Perion with my own hands.": "永远保持警惕！我将用自己的双手保护佩里昂。",
        "It's dangerous going ahead. Be careful.": "前面很危险。小心。",
        "The burning grounds are dangerous, so be careful.": "燃烧之地很危险，所以要小心。",
        "A Warrior of Perion must always train himself.": "佩里昂的战士必须不断训练自己。",
        "Magician Job Instructor": "魔法师职业导师",
        "Do you want to make your 2nd job advancement as a magician? Go see Grendel the Really Old in Ellinia.": "你想作为魔法师进行第二次转职吗？去艾琳尼亚见真正古老的格伦德尔。",
        "Only those who pass my test can make the 2nd job advancement as a magician.": "只有通过我的测试的人才能作为魔法师进行第二次转职。",
        "Bowman Job Instructor": "弓箭手职业导师",
        "Do you want to make your 2nd job advancement as a bowman? Go see Athena Pierce in Henesys.": "你想作为弓箭手进行第二次转职吗？去赫尼斯见雅典娜·皮尔斯。",
        "Only those who pass my test can make the 2nd job advancement as a bowman.": "只有通过我的测试的人才能作为弓箭手进行第二次转职。",
        "Thief Job Instructor": "盗贼职业导师",
        "Do you want to make your 2nd job advancement as a thief? Go see Dark Lord in Kerning City.": "你想作为盗贼进行第二次转职吗？去凯宁市见黑暗领主。",
        "Only those who pass my test can make the 2nd job advancement as a thief.": "只有通过我的测试的人才能作为盗贼进行第二次转职。",
        "Warrior Job Instructor": "战士职业导师",
        "Do you want to make your 2nd job advancement as a warrior? Go see Dances with Balrog in Perion.": "你想作为战士进行第二次转职吗？去佩里昂见与巴洛格共舞。",
        "Only those who pass my test can make the 2nd job advancement as a warrior.": "只有通过我的测试的人才能作为战士进行第二次转职。",
        "Only those who pass my test can make the 2nd job advancement as a thief": "只有通过我的测试的人才能作为盗贼进行第二次转职",
        "Kyrin": "麒麟",
        "Pirate Instructor": "海盗导师",
        "Ahoy! If you want to become a Pirate, you must show me your strength! ": "喂！如果你想成为海盗，你必须向我展示你的力量！",
        "You'll have to pass my test to make the 2nd job advancement for the Pirate class! ": "你必须通过我的测试才能进行海盗职业的第二次转职！",
        "Valen": "瓦伦",
        "On a hot day like this, a Very Special Sundae is the way to go!": "在这样炎热的日子里，一份非常特别的圣代是最好的选择！",
        "Here you go! Delicious food, fresh and homemade!": "给你！美味的食物，新鲜自制！",
        "Pison": "皮森",
        "This is Florina Beach!": "这是弗洛里纳海滩！",
        "If you want to head back to where you were before, feel free to talk to me.": "如果你想回到之前的地方，随时跟我谈谈。",
        "Morgan": "摩根",
        "Arrr! If you need any weapons, why don't you come this way and take a look?": "啊！如果你需要任何武器，为什么不来这边看看？",
        "A Pirate's best friend is a trusty weapon!": "海盗最好的朋友是一把可靠的武器！",
        "Rodos": "罗多斯",
        "Nothing like a good set of Pirate digs, mates!": "没有什么比一套好的海盗装备更好的了，伙计们！",
        "This message has been brought to you by the letter 'ARRR!'": "这条消息由字母'ARRR!'带给你！",
        "Gali": "加利",
        "If it weren't for me, who'd supply all the medicine 'round here.. *Cough cough...*": "如果不是我，谁会供应这里所有的药品呢..*咳咳...*",
        "*Cough... Cough...* Nothing a shot of Nautilus brew won't cure!": "*咳...咳...*没有什么是一杯鹦鹉螺啤酒治愈不了的！",
        "Serryl": "塞里尔",
        "Feels nice to get some fresh air after so much time below deck.": "在甲板下待了这么久，呼吸新鲜空气感觉真好。",
        "I'd love to take a break, but then we'd all starve.": "我很想休息一下，但那样我们都会饿死。",
        "It's hard keeping the crew of the Nautilus fed. They eat so much!": "很难让鹦鹉螺号的船员吃饱。他们吃得太多了！",
        "This Pig Farm is associated with Gustav at Utah's Pig Farm.": "这个养猪场与犹他养猪场的古斯塔夫有关联。",
        "Dondlass": "唐德拉斯",
        "You should know that it is I who guards all of Nautilus' goods.": "你应该知道是我守护着鹦鹉螺号的所有货物。",
        "Come on, the Nautilus isn't going to sink just because there's a lot of cargo on it!": "来吧，鹦鹉螺号不会因为装载了很多货物就沉没的！",
        "Mrs. Reade": "里德夫人",
        "A clean environment puts you in a good mood. That's why it's so important to keep your surroundings clean!": "干净的环境能让你心情愉快。这就是为什么保持周围环境清洁如此重要！",
        "Oh, the Nautilus is becoming a cleaner place with your help, youngster!": "哦，在你的帮助下，鹦鹉螺号变得更干净了，年轻人！",
        "Ho ho ho! Now I can start my day all nice and clean. ": "呵呵呵！现在我可以开始我干净整洁的一天了。",
        "Ho ho ho! Hey you, I just cleaned over there so don't make go dirtying it up. Ho ho ho ho ho!": "呵呵呵！嘿你，我刚在那边打扫过，别把它弄脏了。呵呵呵呵呵！",
        "Bartol": "巴托尔",
        "I am Bartol, beloved student of Mr. Pickall from Kerning City!": "我是巴托尔，来自凯宁市的皮克尔先生心爱的学生！",
        "I wonder if there's anything more interesting to do.": "我想知道有没有更有趣的事情可做。",
        "ZzZzzZzz": "呼噜呼噜",
        "Whoa, I dozed off.": "哇，我打瞌睡了。",
        "Grandpa Tom": "汤姆爷爷",
        "The winds are cool, the sun is warm, and I need a nap!": "风很凉爽，太阳很温暖，我需要午睡！",
        "Welcome aboard the Nautilus.": "欢迎登上鹦鹉螺号。",
        "How are you feeling?": "你感觉怎么样？",
        "Vicky": "维姬",
        "Stalinko": "斯塔林科",
        "Maple Administrator": "冒险岛管理员",
        "Hello! Welcome to Maple World!": "你好！欢迎来到冒险岛世界！",
        "Are you enjoying the sights of Maple World?": "你喜欢冒险岛世界的风景吗？",
        "Feel free to talk to me anytime if you need my help.": "如果你需要我的帮助，随时跟我谈谈。",
        "Hello there! Hope you're have a great time playing MapleStory! I'll see you at the next great event!": "你好！希望你在玩冒险岛时玩得开心！下次盛大活动见！",
        "Cassandra": "卡桑德拉",
        "I know a fun activity or two. Interested?": "我知道一两个有趣的活动。有兴趣吗？",
        "You must be bored. I have something that should pique your interest. Wanna check it out?": "你一定很无聊。我有一些东西应该能引起你的兴趣。想看看吗？",
        "Of course! You're looking for something to do! I know everything, you know.": "当然！你在找事情做！你知道，我什么都知道。",
        "Did you like the story I told you the other day?": "你喜欢我前几天给你讲的故事吗？",
        "You want me to tell you what I saw in my crystal ball?": "你想让我告诉你我在水晶球里看到了什么吗？",
        "Gaga": "嘎嘎",
        "Are you enjoying the event?": "你喜欢这个活动吗？",
        "I hope that you will enjoy the event!": "我希望你会喜欢这个活动！",
        "Finally, the Artifact Hunt has begun!": "终于，神器狩猎开始了！",
        "Did you enjoy the event?": "你喜欢这个活动吗？",
    }
    
    if text in translations:
        return translations[text]
    return text

def translate_xml_files(input_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    
    xml_files = sorted(glob.glob(os.path.join(input_dir, "*.xml")))
    
    for xml_file in xml_files:
        with open(xml_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        def replace_value(match):
            key = match.group(1)
            translated = translate_value(key)
            return f'value="{translated}"'
        
        translated_content = re.sub(r'value="([^"]+)"', replace_value, content)
        
        base_name = os.path.basename(xml_file)
        name_without_ext = os.path.splitext(base_name)[0]
        output_file = os.path.join(output_dir, f"{name_without_ext}_c.xml")
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(translated_content)
        
        print(f"Translated: {xml_file} -> {output_file}")

if __name__ == "__main__":
    input_dir = r"wz\String.wz\npc\split"
    output_dir = r"wz\String.wz\npc\translated"
    
    translate_xml_files(input_dir, output_dir)