ip=127.0.0.1
logOps=false
adminOnly=false
antiSniff=false
#经验倍率
expRate=6
#金币倍率
mesoRate=1
#掉落倍率
dropRate=2
#频道数量
channelCount=1
#sql
sql_port=3306
sql_user=root
sql_password=root
sql_db=v146

wzpath=wz