# -*- coding: utf-8 -*-
import re
import sys

sys.stdout.reconfigure(encoding='utf-8')

BASE = 'E:/github/MapleStoryV146/Service/SpiritMS/wz/String.wz/map'

# ========== streetName translations ==========
STREET = {
    "Orbis": "天空之城",
    "Orbis Park": "天空之城公园",
    "Aqua Road": "水之路",
    "Aquarium": "水族馆",
    "Ludibrium": "玩具城",
    "Korean Folk Town": "童话村",
    "Omega Sector": "地球防御本部",
    "Leafre": "神木村",
    "Mu Lung": "武陵",
    "Herb Town": "百草堂",
    "Ariant": "阿里安特",
    "Town of Ariant": "阿里安特",
    "Ariant Castle": "阿里安特城堡",
    "Magatia": "马加提亚",
    "Alcadno Laboratory": "阿尔卡诺实验室",
    "Alcadno Research Institute": "阿尔卡诺研究所",
    "Zenumist Laboratory": "杰尼斯托实验室",
    "Zenumist Research Institute": "杰尼斯托研究所",
    "Hidden Street": "隐藏街道",
    "Mini Dungeon": "迷你地下城",
    "Dead Mine": "死亡矿坑",
    "Cave of Life": "生命之穴",
    "Temple of Time": "时间神殿",
    "Dark Temple of Time": "黑暗时间神殿",
    "Deep Inside the Temple": "神殿深处",
    "Deep Place of Temple": "神殿深部",
    "Gate to the Future": "通往未来之门",
    "Henesys Ruins": "射手村废墟",
    "Dark Ereve": "黑暗圣地",
    "Knight Stronghold": "骑士要塞",
    "Twilight Perion": "黄昏勇士部落",
    "Ravaged Forest": "荒废森林",
    "Singing Mushroom Forest Ruins": "蘑菇歌唱森林废墟",
    "The Burning Road": "燃烧之路",
    "The Burning Sands": "灼热沙漠",
    "Sunset Road": "日落之路",
    "Colossus Road": "巨人之路",
    "Stone Colossus Body": "石巨人之躯",
    "Stone Colossus Exploration Site": "石巨人探索地",
    "Stone Colossus Innards": "石巨人体内",
    "Floating Island of Chryse": "克瑞塞浮岛",
    "Fantasy Theme World": "梦幻主题世界",
    "Fantasy Theme Park": "梦幻主题公园",
    "Haunted Mansion": "鬼屋",
    "Happy Village": "幸福村",
    "Golden Temple": "黄金寺院",
    "Crumbling Zakum": "崩塌的扎昆",
    "Adobis's Mission I": "阿多比斯的任务I",
    "Dimensional Schism": "次元裂缝",
    "Kritias": "克里提亚斯",
    "Azwan": "阿兹万",
    "Hilla's Tower": "希拉之塔",
    "Final Mission": "最终任务",
    "Last Mission": "最后任务",
    "Research Command": "研究所指挥室",
    "Snow Island": "雪岛",
    "Empress' Road": "女皇之路",
    "Kingdom Road": "王国之路",
    "Leafre of Past": "过去的神木村",
    "Old Leafre": "旧神木村",
    "Lion King's Castle": "狮王之城",
    "The Lion King's Castle": "狮王之城",
    "On Voyage": "航行途中",
    "In Flight": "飞行中",
    "Flying": "飞行中",
    "on the move": "移动中",
    "Olaf's Voyage": "奥拉夫的航行",
    "Memory Keeper": "记忆守护者",
    "Neo City": "新城市",
    "Neo City &lt;Year 2099&gt;": "新城市 &lt;2099年&gt;",
    "Forest of Coke Golem": "可乐石人森林",
    "Sakura Castle": "樱花城",
    "Tera Forest  ": "泰拉森林",
}

# ========== mapName translations ==========
MAPNAME = {
    # === Sky City (Orbis) ===
    "Orbis": "天空之城",
    "Orbis Weapon Store": "天空之城武器店",
    "Orbis General Store": "天空之城杂货店",
    "Orbis Station Entrance": "天空之城售票口",
    "Station Passageway &lt;Victoria Bound&gt;": "站台通道 &lt;开往维多利亚岛&gt;",
    "Station &lt;Victoria Bound&gt;": "站台 &lt;开往维多利亚岛&gt;",
    "Pre-Departure &lt;Victoria Bound&gt;": "出发等候室 &lt;开往维多利亚岛&gt;",
    "Station Pathway&lt;Ludibrium&gt;": "站台通道&lt;玩具城方向&gt;",
    "Station&lt;Ludibrium&gt;": "站台&lt;玩具城方向&gt;",
    "Before the Departure &lt;Ludibrium&gt;": "出发等候室 &lt;玩具城方向&gt;",
    "Cabin Path &lt;To Leafre&gt;": "飞龙之路 &lt;神木村方向&gt;",
    "Cabin &lt;To Leafre&gt;": "飞龙船舱 &lt;神木村方向&gt;",
    "Station &lt;To Ereve&gt;": "站台 &lt;开往圣地&gt;",
    "Station &lt;Edelstein Bound&gt;": "站台 &lt;开往埃德尔斯坦&gt;",
    "Cloud Terrace&lt;1&gt;": "云朵露台&lt;1&gt;",
    "Cloud Terrace&lt;2&gt;": "云朵露台&lt;2&gt;",
    "Cloud Terrace&lt;3&gt;": "云朵露台&lt;3&gt;",
    "Cloud Terrace&lt;4&gt;": "云朵露台&lt;4&gt;",
    "Cloud Terrace&lt;5&gt;": "云朵露台&lt;5&gt;",
    "Sky Terrace&lt;1&gt;": "天空露台&lt;1&gt;",
    "Sky Terrace&lt;2&gt;": "天空露台&lt;2&gt;",
    "Sky Terrace&lt;3&gt;": "天空露台&lt;3&gt;",
    "Sky Terrace&lt;4&gt;": "天空露台&lt;4&gt;",
    "Sky Terrace&lt;5&gt;": "天空露台&lt;5&gt;",
    "Cloud Balcony": "云朵阳台",
    "Sky Balcony": "天空阳台",
    "Stairway to the Sky I": "通天阶梯I",
    "Stairway to the Sky II": "通天阶梯II",
    "Orbis Park": "天空之城公园",
    "Orbis Tower &lt;Secret Room&gt;": "天空之塔 &lt;密室&gt;",
    "Orbis Tower 1st Floor": "天空之塔1层",
    "Orbis Tower 2nd Floor": "天空之塔2层",
    "Orbis Tower 3rd Floor": "天空之塔3层",
    "Orbis Tower 4th Floor": "天空之塔4层",
    "Orbis Tower 5th Floor": "天空之塔5层",
    "Orbis Tower 6th Floor": "天空之塔6层",
    "Orbis Tower 7th Floor": "天空之塔7层",
    "Orbis Tower 8th Floor": "天空之塔8层",
    "Orbis Tower 9th Floor": "天空之塔9层",
    "Orbis Tower 10th Floor": "天空之塔10层",
    "Orbis Tower 11th Floor": "天空之塔11层",
    "Orbis Tower 12th Floor": "天空之塔12层",
    "Orbis Tower 13th Floor": "天空之塔13层",
    "Orbis Tower 14th Floor": "天空之塔14层",
    "Orbis Tower 15th Floor": "天空之塔15层",
    "Orbis Tower 16th Floor": "天空之塔16层",
    "Orbis Tower 17th Floor": "天空之塔17层",
    "Orbis Tower 18th Floor": "天空之塔18层",
    "Orbis Tower 19th Floor": "天空之塔19层",
    "Orbis Tower 20th Floor": "天空之塔20层",
    "The Garden of Colors": "色彩花园",
    "The Road to the Garden of Colors": "色彩花园之路",
    "Eliza's Garden": "艾利莎的庭院",
    "Free Market Entrance": "自由市场入口",
    "Free Market&lt;1&gt;": "自由市场&lt;1&gt;",
    "Free Market&lt;2&gt;": "自由市场&lt;2&gt;",
    "Free Market&lt;3&gt;": "自由市场&lt;3&gt;",
    "Free Market&lt;4&gt;": "自由市场&lt;4&gt;",
    "Free Market&lt;5&gt;": "自由市场&lt;5&gt;",
    "Free Market&lt;6&gt;": "自由市场&lt;6&gt;",
    "Free Market&lt;7&gt;": "自由市场&lt;7&gt;",
    "Free Market&lt;8&gt;": "自由市场&lt;8&gt;",
    "Free Market&lt;9&gt;": "自由市场&lt;9&gt;",
    "Orbis Bound": "开往天空之城",
    "Victoria Bound": "开往维多利亚岛",
    "Victoria Island Bound": "开往维多利亚岛",
    "Edelstein Bound": "开往埃德尔斯坦",
    "Before Takeoff &lt;To Orbis&gt;": "起飞前 &lt;开往天空之城&gt;",
    "Before the Departure &lt;Orbis&gt;": "出发前 &lt;开往天空之城&gt;",
    "&lt;To Victoria&gt;": "&lt;前往维多利亚岛&gt;",
    "&lt;To Orbis&gt;": "&lt;前往天空之城&gt;",
    "&lt;To Ludibrium&gt;": "&lt;前往玩具城&gt;",
    "&lt;To Leafre&gt;": "&lt;前往神木村&gt;",
    "&lt;To Erev&gt;": "&lt;前往圣地&gt;",
    "&lt;To Ariant&gt;": "&lt;前往阿里安特&gt;",
    "&lt;To Edelstein&gt;": "&lt;前往埃德尔斯坦&gt;",
    "&lt;To Mu Lung&gt;": "&lt;前往武陵&gt;",
    "To Orbis": "前往天空之城",
    "To Lith Harbor": "前往明珠港",
    "To Ereve": "前往圣地",
    "To Rien": "前往里恩",
    "On the ship": "船上",
    "Cabin &lt;To Leafre&gt;": "船舱 &lt;前往神木村&gt;",
    "Station": "站台",
    "Station&lt;Orbis&gt;": "站台&lt;天空之城&gt;",
    "Station Hall": "站台大厅",

    # === Sea/Aqua ===
    "Aquarium": "水族馆",
    "Penguin's Playground": "企鹅游乐场",
    "The Seaweed Tower": "海藻塔",
    "Blue Seaweed Road": "蓝色海藻路",
    "Red Coral Forest": "红色珊瑚森林",
    "Mushroom Coral Hill": "蘑菇珊瑚丘",
    "Turban Shell Hill": "海螺壳山丘",
    "The Grave of a Wrecked Ship": "沉船之墓",
    "A Small Wrecked Ship": "小型沉船",
    "The Cave of Pianus": "皮亚努斯之穴",
    "Ocean I.C": "海洋IC",
    "Deep Sea Gorge I": "深海峡谷I",
    "Deep Sea Gorge II": "深海峡谷II",
    "Dangerous Sea Gorge I": "危险海沟I",
    "Dangerous Sea Gorge II": "危险海沟II",
    "Big Fish Valley": "大鱼山谷",
    "Fish Resting Spot": "鱼群休息处",
    "Around the Pond": "池塘周围",
    "Pond": "池塘",
    "Bellflower Valley": "金钟花谷",
    "Carta's Cave": "卡尔塔之穴",
    "Tae Gong's Ferry": "太公渡口",
    "Snowy Whale's Island": "雪鲸之岛",
    "Peach Farm 1": "桃木农场1",
    "Peach Farm 2": "桃木农场2",
    "Peach Farm 3": "桃木农场3",
    "The Hidden Town": "隐藏的村庄",
    "Cave of Darkness": "黑暗洞穴",
    "Cave of Light": "光明洞穴",
    "A Small Cave": "小洞穴",
    "A Small Well": "小水井",

    # === Ludibrium (Toy City) ===
    "Ludibrium": "玩具城",
    "Ludibrium Village": "玩具城村庄",
    "Ludibrium Weapon Store": "玩具城武器店",
    "Ludibrium General Store": "玩具城杂货店",
    "Ludibrium Hair Salon": "玩具城美发店",
    "Ludibrium Plastic Surgery": "玩具城整形医院",
    "Ludibrium Skin Care": "玩具城护肤中心",
    "Ludibrium Pet Walkway": "玩具城宠物散步道",
    "Ludibrium Ticketing Place": "玩具城售票处",
    "Toy Factory &lt;Process 1&gt; Zone 1": "玩具工厂&lt;工序1&gt;区域1",
    "Toy Factory &lt;Process 1&gt; Zone 2": "玩具工厂&lt;工序1&gt;区域2",
    "Toy Factory &lt;Process 1&gt; Zone 3": "玩具工厂&lt;工序1&gt;区域3",
    "Toy Factory &lt;Process 1&gt; Zone 5": "玩具工厂&lt;工序1&gt;区域5",
    "Toy Factory &lt;Process 1&gt; Zone 6": "玩具工厂&lt;工序1&gt;区域6",
    "Toy Factory &lt;Process 2&gt; Zone 1": "玩具工厂&lt;工序2&gt;区域1",
    "Toy Factory &lt;Process 2&gt; Zone 2": "玩具工厂&lt;工序2&gt;区域2",
    "Toy Factory &lt;Process 2&gt; Zone 3": "玩具工厂&lt;工序2&gt;区域3",
    "Toy Factory &lt;Process 2&gt; Zone 4": "玩具工厂&lt;工序2&gt;区域4",
    "Toy Factory &lt;Aparatus Room&gt;": "玩具工厂&lt;机械室&gt;",
    "Toy Factory &lt;Main Process 1&gt;": "玩具工厂&lt;主工序1&gt;",
    "Toy Factory &lt;Main Process 2&gt;": "玩具工厂&lt;主工序2&gt;",
    "Terrace Hall": "露台大厅",
    "Eos Tower Entrance": "艾奥斯塔入口",
    "Eos Tower 1st Floor": "艾奥斯塔1层",
    "Eos Tower 2nd Floor": "艾奥斯塔2层",
    "Eos Tower 3rd Floor": "艾奥斯塔3层",
    "Eos Tower 4th Floor": "艾奥斯塔4层",
    "Eos Tower 5th Floor": "艾奥斯塔5层",
    "Eos Tower 6th Floor": "艾奥斯塔6层",
    "Eos Tower 7th Floor": "艾奥斯塔7层",
    "Eos Tower 8th Floor": "艾奥斯塔8层",
    "Eos Tower 9th Floor": "艾奥斯塔9层",
    "Eos Tower 10th Floor": "艾奥斯塔10层",
    "Eos Tower 11th - 30th Floor": "艾奥斯塔11-30层",
    "Eos Tower 31st Floor": "艾奥斯塔31层",
    "Eos Tower 32nd Floor": "艾奥斯塔32层",
    "Eos Tower 33rd Floor": "艾奥斯塔33层",
    "Eos Tower 34th Floor": "艾奥斯塔34层",
    "Eos Tower 35th Floor": "艾奥斯塔35层",
    "Eos Tower 36th - 65th Floor": "艾奥斯塔36-65层",
    "Eos Tower 66th Floor": "艾奥斯塔66层",
    "Eos Tower 67th Floor": "艾奥斯塔67层",
    "Eos Tower 68th Floor": "艾奥斯塔68层",
    "Eos Tower 69th Floor": "艾奥斯塔69层",
    "Eos Tower 70th Floor": "艾奥斯塔70层",
    "Eos Tower 71st - 90th Floor": "艾奥斯塔71-90层",
    "Eos Tower 76th - 90th Floor (For Deletion)": "艾奥斯塔76-90层(待删除)",
    "Eos Tower 91st Floor": "艾奥斯塔91层",
    "Eos Tower 91st Floor (For Deletion)": "艾奥斯塔91层(待删除)",
    "Eos Tower 92nd Floor": "艾奥斯塔92层",
    "Eos Tower 92nd Floor (For Deletion)": "艾奥斯塔92层(待删除)",
    "Eos Tower 93rd Floor": "艾奥斯塔93层",
    "Eos Tower 93rd Floor (For Deletion)": "艾奥斯塔93层(待删除)",
    "Eos Tower 94th Floor": "艾奥斯塔94层",
    "Eos Tower 94th Floor (For Deletion)": "艾奥斯塔94层(待删除)",
    "Eos Tower 95th Floor": "艾奥斯塔95层",
    "Eos Tower 95th Floor (For Deletion)": "艾奥斯塔95层(待删除)",
    "Eos Tower 96th Floor": "艾奥斯塔96层",
    "Eos Tower 96th Floor (For Deletion)": "艾奥斯塔96层(待删除)",
    "Eos Tower 97th Floor": "艾奥斯塔97层",
    "Eos Tower 97th Floor (For Deletion)": "艾奥斯塔97层(待删除)",
    "Eos Tower 98th Floor": "艾奥斯塔98层",
    "Eos Tower 98th Floor (For Deletion)": "艾奥斯塔98层(待删除)",
    "Eos Tower 99th Floor": "艾奥斯塔99层",
    "Eos Tower 99th Floor (For Deletion)": "艾奥斯塔99层(待删除)",
    "Eos Tower 100th Floor": "艾奥斯塔100层",
    "Eos Tower 100th Floor (For Deletion)": "艾奥斯塔100层(待删除)",
    "Eos Tower 101st Floor &lt;Exit Map&gt;": "艾奥斯塔101层&lt;出口地图&gt;",
    "Eos Tower 101st Floor (For Deletion)": "艾奥斯塔101层(待删除)",
    "Helios Tower Entrance": "赫利奥斯塔入口",
    "Helios Tower &lt;2nd Floor&gt;": "赫利奥斯塔&lt;2层&gt;",
    "Helios Tower &lt;99th Floor&gt;": "赫利奥斯塔&lt;99层&gt;",
    "Helios Tower &lt;Library&gt;": "赫利奥斯塔&lt;图书馆&gt;",
    "Helios Tower (100th Floor)": "赫利奥斯塔(100层)",
    "Elevator &lt;To Ludibrium&gt;": "电梯 &lt;开往玩具城&gt;",
    "Elevator &lt;To Korean Folk Town&gt;": "电梯 &lt;开往童话村&gt;",
    "Origin of Clocktower": "钟楼之源",
    "Path of Time": "时间之路",
    "The Path of Time &lt;1&gt;": "时间之路&lt;1&gt;",
    "The Path of Time &lt;2&gt;": "时间之路&lt;2&gt;",
    "The Path of Time &lt;3&gt;": "时间之路&lt;3&gt;",
    "The Path of Time &lt;4&gt;": "时间之路&lt;4&gt;",
    "Forgotten Path of Time&lt;1&gt;": "被遗忘的时间之路&lt;1&gt;",
    "Forgotten Path of Time&lt;2&gt;": "被遗忘的时间之路&lt;2&gt;",
    "Forgotten Path of Time&lt;3&gt;": "被遗忘的时间之路&lt;3&gt;",
    "Forgotten Path of Time&lt;4&gt;": "被遗忘的时间之路&lt;4&gt;",
    "Warped Path of Time&lt;1&gt;": "扭曲的时间之路&lt;1&gt;",
    "Warped Path of Time&lt;2&gt;": "扭曲的时间之路&lt;2&gt;",
    "Warped Path of Time&lt;3&gt;": "扭曲的时间之路&lt;3&gt;",
    "Warped Path of Time&lt;4&gt;": "扭曲的时间之路&lt;4&gt;",
    "Lost Time": "失去的时间",
    "Lost Time &lt;1&gt;": "失去的时间&lt;1&gt;",
    "Lost Time &lt;2&gt;": "失去的时间&lt;2&gt;",
    "Twisted Time": "扭曲的时间",
    "Unbalanced Time": "失衡的时间",
    "Forbidden Time": "被禁止的时间",
    "Forgotten Passage": "被遗忘的通道",
    "Warped Passage": "扭曲的通道",
    "Broken Corridor": "破碎的走廊",
    "Gloomy Corridor 1": "阴暗走廊1",
    "Gloomy Corridor 2": "阴暗走廊2",
    "Corridor 1": "走廊1",
    "Corridor 2": "走廊2",
    "Whirlpool of Time": "时间漩涡",
    "Crack in Time": "时间的裂缝",
    "Time Control Room": "时间控制室",
    "Deep Inside the Clocktower": "钟楼深处",
    "The Center Hall": "中央大厅",

    # === Korean Folk Town ===
    "Korean Folk Town": "童话村",
    "Manager Karl's House": "管理者卡尔的家",
    "Mason's House": "梅森的家",
    "Tae Sang's House": "太相的家",
    "Ito's House": "伊豆的家",
    "Korin's House": "可琳的家",
    "Chloe's House": "可洛伊的家",
    "Rina's House": "莉娜的家",
    "Yaku's House": "亚库的家",
    "Kumo's House": "久保的家",
    "Tara and Sarah's House": "塔拉和莎拉的家",
    "Cliff's Hut": "克利夫的小屋",
    "House of Lolo": "洛洛之家",
    "House of Pouch": "小袋之家",
    "House of Puch": "小布之家",
    "Pam's House": "帕姆的家",
    "An Old, Empty House": "一座空旧的房屋",
    "General Store": "杂货店",
    "Fox Ridge": "狐狸岭",
    "Kappa Creek Forest": "河童溪流森林",
    "Tiger Forest I": "老虎森林I",
    "Tiger Forest II": "老虎森林II",
    "Tiger Ridge": "老虎岭",
    "Goblin Forest 1": "哥布林森林1",
    "Goblin Forest 2": "哥布林森林2",
    "Goblin House": "哥布林之家",
    "Haunted House": "鬼屋",
    "The Room of Tragedy": "悲剧之房",
    "Room of Suffering": "痛苦之房",
    "Room of Trials 1": "试炼之房1",
    "Room of Trials 2": "试炼之房2",

    # === Omega Sector ===
    "Omega Sector": "地球防御本部",
    "Command Center": "指挥中心",
    "HQ": "总部",
    "Mateon Field": "马特昂战场",
    "Mecateon Field": "麦卡顿战场",
    "Plateon Field": "普拉顿战场",
    "Barnard Field": "巴纳德战场",
    "Kulan Field I": "库兰战场I",
    "Kulan Field II": "库兰战场II",
    "Kulan Field III": "库兰战场III",
    "Kulan Field IV": "库兰战场IV",
    "Kulan Field V": "库兰战场V",
    "Boswell Field I": "博斯韦尔战场I",
    "Boswell Field II": "博斯韦尔战场II",
    "Boswell Field III": "博斯韦尔战场III",
    "Boswell Field IV": "博斯韦尔战场IV",
    "Boswell Field V": "博斯韦尔战场V",
    "Boswell Field VI": "博斯韦尔战场VI",
    "Dogon's HQ": "多贡总部",
    "Entrance to Dogon's HQ": "多贡总部入口",
    "Silo": "发射井",
    "Critical Error": "严重错误",

    # === Leafre ===
    "Leafre": "神木村",
    "Leafre : East Forest": "神木村：东方森林",
    "West Leafre Forest": "神木村西方森林",
    "Leafre Station Entrance": "神木村售票口入口",
    "Way to Minar Forest": "前往米纳尔森林之路",
    "Minar Forest : East Border": "米纳尔森林：东部边界",
    "Minar Forest : West Border": "米纳尔森林：西部边界",
    "Entrance to Dragon Forest": "龙之森林入口",
    "Dragon Forest I": "龙之森林I",
    "Dragon Forest II": "龙之森林II",
    "Dragon Forest III": "龙之森林III",
    "Entrance to Dragon Nest": "龙之巢穴入口",
    "Sky Forest : The Trail": "天空森林：小径",
    "Entrance to Sky Forest": "天空森林入口",
    "Deep in the Sky Forest": "天空森林深处",
    "Where the Sky Forest Ends": "天空森林尽头",
    "Entrance to Sky Nest": "天空巢穴入口",
    "Sky Nest I": "天空巢穴I",
    "Sky Nest II": "天空巢穴II",
    "Blue Wyvern's Nest": "蓝色飞龙之巢",
    "Red Wyvern's Nest": "红色飞龙之巢",
    "Wyvern Canyon": "飞龙峡谷",
    "Dangerous Dragon Nest": "危险的龙之巢穴",
    "The Dragon Canyon": "龙之峡谷",
    "Leviathan's Canyon": "利维坦峡谷",
    "The Area of Red Kentaurus": "红色半人马领地",
    "The Area of Blue Kentaurus": "蓝色半人马领地",
    "The Area of Black Kentaurus": "黑色半人马领地",
    "The Round Table of Kentaurus": "半人马圆桌",
    "Newt Secured Zone": "纽特安全区",
    "Destroyed Dragon Nest": "被毁的龙之巢穴",
    "Peak of the Big Nest": "大巢穴之巅",
    "Below the Dangerous Nest": "危险巢穴下方",
    "The Hidden Dragon Tomb I": "隐藏的龙墓I",
    "The Hidden Dragon Tomb II": "隐藏的龙墓II",
    "Nest of a Dead Dragon": "死龙之巢",
    "Valley of the Antelope": "羚羊之谷",
    "Crimson Sky 1 ": "绯红天空1",
    "Crimson Sky 2": "绯红天空2",
    "Crimson Sky Dock": "绯红天空码头",
    "Crimson Sky Edge": "绯红天空边缘",
    "Crimson Sky Nest": "绯红天空巢穴",
    "Crimson Sky Nest Entrance": "绯红天空巢穴入口",
    "Crimson Sky Resurrection Site ": "绯红天空复活点",
    "Manon's Forest": "玛侬之森",
    "Griffey Forest": "格里菲之森",
    "The Dragon Nest Left Behind": "遗留的龙之巢穴",
    "Entrance to Horntail's Cave": "暗黑龙王洞穴入口",
    "Horntail's Cave": "暗黑龙王洞穴",
    "Nine Spirit's Nest": "九灵之巢",
    "Chaos Horntail's Cave": "混沌暗黑龙王洞穴",
    "Leafre in Flames 1": "燃烧的神木村1",
    "Leafre in Flames 2": "燃烧的神木村2",
    "Leafre in Flames 3": "燃烧的神木村3",
    "Leafre in Flames 4": "燃烧的神木村4",
    "Leafre in Flames 5": "燃烧的神木村5",
    "Leafre in Flames 6": "燃烧的神木村6",
    "Cave of Life - Entrance": "生命之穴 - 入口",
    "Cave of Choice": "选择之穴",
    "Cave of Light": "光明之穴",
    "Cave of Darkness": "黑暗之穴",
    "Cave : The Road in Between": "洞穴：中间之路",
    "Cave Entrance": "洞穴入口",
    "Cave Exit": "洞穴出口",
    "The Hidden Cave": "隐藏的洞穴",
    "Room of Maze": "迷宫之间",
    "1st Room of Maze": "迷宫第一间",
    "2nd Room of Maze": "迷宫第二间",
    "3rd Room of Maze": "迷宫第三间",
    "4th Room of Maze": "迷宫第四间",
    "5th Room of Maze": "迷宫第五间",
    "Forest of Training 1": "修炼之森1",
    "Forest of Training 2": "修炼之森2",
    "Forest of Training 3": "修炼之森3",
    "Forest of Training 4": "修炼之森4",
    "Rough Wilderness": "荒芜原野",
    "Rough Canyon": "崎岖峡谷",

    # === Mu Lung / Herb Town ===
    "Mu Lung": "武陵",
    "Mu Lung General Store": "武陵杂货店",
    "Mu Lung Hair Salon": "武陵美发店",
    "Mu Lung Temple": "武陵寺院",
    "Practice Field : Beginner": "修炼场：初级",
    "Practice Field : Easy Level": "修炼场：简单",
    "Practice Field : Normal Level": "修炼场：普通",
    "Practice Field : Advanced Level": "修炼场：高级",
    "Virtuous Forest": "善行森林",
    "Fuzzy Forest": "毛茸茸森林",
    "Secret Grove": "秘密小树林",
    "Overlooked Area": "被忽略的区域",
    "Haunted Mansion": "鬼屋",
    "Bellamoa's Cave": "贝拉莫亚之穴",

    # === Herb Town ===
    "Herb Town": "百草堂",
    "10-Year-Old Herb Garden": "十年草药园",
    "50-Year-Old Herb Garden": "五十年草药园",
    "60-Year-Old Herb Garden": "六十年草药园",
    "80-Year-Old Herb Garden": "八十年草药园",
    "100-Year-Old Herb Garden": "百年草药园",
    "Inside the Inn": "客栈内部",

    # === Ariant ===
    "Ariant": "阿里安特",
    "Ariant Castle": "阿里安特城堡",
    "The Town of Ariant": "阿里安特镇",
    "Ariant Station Platform": "阿里安特站台",
    "Outside North Entrance of Ariant": "阿里安特北门外",
    "Outside East Entrance of Ariant": "阿里安特东门外",
    "Outside the West Entrance of Ariant": "阿里安特西门外",
    "Town Hall": "市政厅",
    "Royal Cactus Desert": "皇家仙人掌沙漠",
    "White Rock Desert": "白岩沙漠",
    "North Desert Road 1": "北方沙漠之路1",
    "North Desert Road 2": "北方沙漠之路2",
    "Burning Hills": "燃烧山丘",
    "Sahel 1": "萨赫勒1",
    "Sahel 2": "萨赫勒2",
    "Sahel 3": "萨赫勒3",
    "Cactus Desert 1": "仙人掌沙漠1",
    "Cactus Desert 2": "仙人掌沙漠2",
    "Dry Desert": "干燥沙漠",
    "The Desert of Red Sand": "红沙沙漠",
    "The Scorching Desert": "灼热沙漠",
    "The Desert of Serenity": "宁静沙漠",
    "The Desert of Dreams": "梦想沙漠",
    "The Ruins of Desert Nomads": "沙漠游牧民废墟",
    "Hill of Sandstorms": "沙暴山丘",
    "The Giant of the Sunset": "落日巨人",
    "Two Palm Trees": "两棵棕榈树",
    "Rocky Hill": "岩石山丘",
    "Desolate Rocky Road": "荒凉的岩路",
    "Desolate Hills": "荒凉山丘",
    "Lonely Rocky Road": "孤寂的岩路",
    "Young Cactus Desert": "幼仙人掌沙漠",
    "Red Scorpion's Lair": "红蝎子巢穴",
    "The Sharp Unknown": "尖锐的未知",
    "Canyon : Crossroad": "峡谷：十字路",
    "Canyon : East Road": "峡谷：东路",
    "Canyon : West Road": "峡谷：西路",
    "Steep Hill": "陡峭山丘",
    "Suspicious Hill": "可疑的山丘",
    "Authorized Personnel Only": "仅限授权人员",
    "Off-Limits": "禁止入内",
    "Palace Hallway": "宫殿走廊",
    "Audience Room Corridor": "会客厅走廊",
    "Audience Room": "会客厅",
    "King's Room": "国王的房间",
    "Castle Garden": "城堡花园",
    "Imperial Villa": "皇家别墅",
    "Daimyo's Chambers": "大名的房间",
    "Inside the Inn": "旅馆内部",
    "Tent of the Entertainers": "艺人的帐篷",
    "Pier on the Beach": "海滩码头",
    "Sand Castle Playground": "沙堡游乐场",
    "Weapon &amp; Armor Shop": "武器防具店",
    "Altar of Darkness": "黑暗祭坛",

    # === Magatia ===
    "Magatia": "马加提亚",
    "Alcadno Society": "阿尔卡诺学会",
    "Zenumist Society": "杰尼斯托学会",
    "Home of the Missing Alchemist": "失踪炼金术师的家",
    "Lab - Center Gate": "实验室 - 中央大门",
    "Lab - 1st Floor Hallway": "实验室 - 1层走廊",
    "Lab - 2nd Floor Hallway": "实验室 - 2层走廊",
    "Lab - Area A-1": "实验室 - A-1区域",
    "Lab - Area A-3": "实验室 - A-3区域",
    "Lab - Area B-1": "实验室 - B-1区域",
    "Lab - Area B-3": "实验室 - B-3区域",
    "Lab - Area C-1": "实验室 - C-1区域",
    "Lab - Area C-2": "实验室 - C-2区域",
    "Lab - Area C-3": "实验室 - C-3区域",
    "Lab - Secret Basement Path": "实验室 - 秘密地下通道",
    "Lab - Unit 101": "实验室 - 101号室",
    "Lab - Unit 102": "实验室 - 102号室",
    "Lab - Unit 103": "实验室 - 103号室",
    "Lab - Unit 201": "实验室 - 201号室",
    "Lab - Unit 202": "实验室 - 202号室",
    "Lab - Unit 203": "实验室 - 203号室",
    "Alcadno Exit": "阿尔卡诺出口",
    "Secret Alcadno Passage": "秘密阿尔卡诺通道",
    "Alcadno - Hidden Room &lt;Exit Map&gt;": "阿尔卡诺 - 隐藏房间 &lt;出口地图&gt;",
    "Secret Zenumist Passage 1": "秘密杰尼斯托通道1",
    "Secret Zenumist Passage 2": "秘密杰尼斯托通道2",
    "Secret Zenumist Prison": "秘密杰尼斯托监狱",
    "Zenumist - Hidden Room &lt;Exit Map&gt;": "杰尼斯托 - 隐藏房间 &lt;出口地图&gt;",
    "The Dangerous Cave": "危险的洞穴",
    "The Unknown Underground Passage": "未知的地下通道",
    "Mt. Gollisco Map": "戈里斯科山地图",
    "First Drill Hall": "第一训练场",
    "Second Drill Hall": "第二训练场",

    # === Temple of Time ===
    "Temple of Time": "时间神殿",
    "Temple of Time Entrance": "时间神殿入口",
    "Temple of Time Corridor 1": "时间神殿走廊1",
    "Temple of Time Corridor 2": "时间神殿走廊2",
    "Memory Lane 1": "记忆之路1",
    "Memory Lane 2": "记忆之路2",
    "Memory Lane 3": "记忆之路3",
    "Memory Lane 4": "记忆之路4",
    "Memory Lane 5": "记忆之路5",
    "Road of Regrets 1": "后悔之路1",
    "Road of Regrets 2": "后悔之路2",
    "Road of Regrets 3": "后悔之路3",
    "Road of Regrets 4": "后悔之路4",
    "Road of Regrets 5": "后悔之路5",
    "Road to Oblivion 1": "忘却之路1",
    "Road to Oblivion 2": "忘却之路2",
    "Road to Oblivion 3": "忘却之路3",
    "Road to Oblivion 4": "忘却之路4",
    "Road to Oblivion 5": "忘却之路5",
    "Resting Spot of Memory": "记忆的休息处",
    "Resting Spot of Memory 2": "记忆的休息处2",
    "Resting Spot of Memory 3": "记忆的休息处3",
    "Resting Spot of Memory 4": "记忆的休息处4",
    "Resting Spot of Regret": "后悔的休息处",
    "Resting Spot of Regret 1": "后悔的休息处1",
    "Resting Spot of Regret 3": "后悔的休息处3",
    "Resting Spot of Regret 4": "后悔的休息处4",
    "Resting Spot of Oblivion": "忘却的休息处",
    "Resting Spot of Oblivion 1": "忘却的休息处1",
    "Resting Spot of Oblivion 2": "忘却的休息处2",
    "Resting Spot of Oblivion3": "忘却的休息处3",
    "Way to Temple of Time": "前往时间神殿之路",
    "Three Doors": "三扇门",
    "Memory Keeper's Room": "记忆守护者之屋",
    "Record Keeper's Room": "记录守护者之屋",
    "Temple Ruins": "神殿废墟",
    "Distorted Temple of Time 1": "扭曲的时间神殿1",
    "Distorted Temple of Time 2": "扭曲的时间神殿2",
    "Crossroad of Time": "时间的十字路",
    "Spatial Distortion": "空间扭曲",
    "Dimensional Schism": "次元裂缝",
    "Back In Time": "回到过去",

    # === Gate to the Future ===
    "Gate to the Future": "通往未来之门",
    "Henesys Ruins": "射手村废墟",
    "Henesys Ruins Market": "射手村废墟市场",
    "Henesys Ruins Park": "射手村废墟公园",
    "Hill North of Henesys Ruins": "射手村废墟北丘",
    "Six Path Crossway Ruins": "六岔路口废墟",
    "Dark Ereve": "黑暗圣地",
    "Ereve Forked Road": "圣地岔路口",
    "Cygnus's Chamber": "希格娜斯之室",
    "Cygnus Garden": "希格娜斯花园",
    "Cygnus Rear Garden": "希格娜斯后花园",
    "Knight District 1": "骑士区域1",
    "Knight District 2": "骑士区域2",
    "Knight District 3": "骑士区域3",
    "Knight District 4": "骑士区域4",
    "Knights' Chamber 1": "骑士之室1",
    "Knights' Chamber 2": "骑士之室2",
    "Knights' Chamber 3": "骑士之室3",
    "Knights' Chamber 4": "骑士之室4",
    "Knights' Chamber 5": "骑士之室5",
    "Stronghold Entrance": "要塞入口",
    "Hall of Honor": "荣誉之厅",
    "Twilight Perion": "黄昏勇士部落",
    "Warrior Grounds": "战士的训练场",
    "Burning Past": "燃烧的过去",
    "Frozen Past": "冰冻的过去",
    "Forgotten Twilight": "被遗忘的黄昏",
    "Tempest Grave": "暴风之墓",
    "Between Twilight and Daybreak": "黄昏与黎明之间",
    "Deserted Southern Ridge": "荒凉的南方山脊",

    # === Lion King's Castle ===
    "The Lion King's Castle": "狮王之城",
    "Lion King's Castle": "狮王之城",
    "First Drill Hall": "第一训练场",
    "Second Drill Hall": "第二训练场",
    "Northern Barracks": "北方营房",
    "Southern Road": "南方之路",
    "Southeastern Barracks": "东南营房",
    "Southwestern Barracks": "西南营房",
    "Northeastern Road": "东北之路",
    "Northwestern Road": "西北之路",
    "Forsaken Excavation Site 1": "被遗弃的发掘地1",
    "Forsaken Excavation Site 2": "被遗弃的发掘地2",
    "Forsaken Excavation Site 3": "被遗弃的发掘地3",
    "Forsaken Excavation Site 4": "被遗弃的发掘地4",
    "Knight District 1": "骑士区域1",

    # === Zakum related ===
    "Zakum's Altar": "扎昆祭坛",
    "Entrance to Chaos Zakum Altar": "混沌扎昆祭坛入口",
    "Chaos Zakum's Altar": "混沌扎昆祭坛",
    "The Door to Chaos Zakum": "混沌扎昆之门",
    "Entrance to Black Mountain": "黑山入口",
    "Black Mountain &lt;Corner&gt;": "黑山&lt;角落&gt;",
    "Black Mountain &lt;Valley&gt;": "黑山&lt;山谷&gt;",
    "Top of Black Mountain": "黑山之顶",
    "Adobis's Mission I": "阿多比斯的任务I",
    "Crumbling Zakum's Altar": "崩塌的扎昆祭坛",
    "Unknown Dead Mine": "未知的死亡矿坑",
    "Area 1-1": "区域1-1",
    "Area 1-2": "区域1-2",
    "Area 2-1": "区域2-1",
    "Area 3-1": "区域3-1",
    "Area 3-2": "区域3-2",
    "Area 4-1": "区域4-1",
    "Area 4-2": "区域4-2",
    "Area 5-1": "区域5-1",
    "Area 6-1": "区域6-1",
    "Area 7-1": "区域7-1",
    "Area 7-2": "区域7-2",
    "Area 8-1": "区域8-1",
    "Area 8-2": "区域8-2",
    "Area 9-1": "区域9-1",
    "Area 9-2": "区域9-2",
    "Area 10-1": "区域10-1",
    "Area 10-2": "区域10-2",
    "Area 11-1": "区域11-1",
    "Area 12-1": "区域12-1",
    "Area 13-1": "区域13-1",
    "Area 14-1": "区域14-1",
    "Area 16 &lt;A Dead Mine Somewhere&gt;": "区域16 &lt;某处的死亡矿坑&gt;",
    "Area 16-1": "区域16-1",
    "Area 16-2": "区域16-2",
    "Area 16-3": "区域16-3",
    "Area 16-4": "区域16-4",
    "Area 16-5": "区域16-5",
    "Area 16-6": "区域16-6",

    # === Chryse ===
    "Path to Chryse": "前往克瑞塞之路",
    "Road to Chryse": "前往克瑞塞之路",
    "Outside of Chryse 1": "克瑞塞外部1",
    "Outside of Chryse 2": "克瑞塞外部2",
    "Outside of Chryse 3": "克瑞塞外部3",
    "Chryse Hideout": "克瑞塞据点",
    "Entrance to Ravana's Altar": "罗波那祭坛入口",
    "Ravana's Altar Tunnel": "罗波那祭坛通道",
    "Ravana's Golden Altar": "罗波那黄金祭坛",

    # === Fantasy Theme ===
    "Fantasy Theme World &lt;Main Gate&gt;": "梦幻主题世界&lt;正门&gt;",
    "Fantasy Station &lt;1&gt;": "梦幻车站&lt;1&gt;",
    "Fantasy Station &lt;2&gt;": "梦幻车站&lt;2&gt;",
    "Extreme Station &lt;1&gt;": "极限车站&lt;1&gt;",
    "Extreme Station &lt;2&gt;": "极限车站&lt;2&gt;",
    "Extreme Station &lt;3&gt;": "极限车站&lt;3&gt;",
    "Funky Station &lt;1&gt;": "芬奇车站&lt;1&gt;",
    "Funky Station &lt;2&gt;": "芬奇车站&lt;2&gt;",
    "Funky Station &lt;3&gt;": "芬奇车站&lt;3&gt;",
    "Fantasty Animal Show &lt;Entrance&gt;": "梦幻动物秀&lt;入口&gt;",
    "Fantasty Animal Show &lt;Venue&gt;": "梦幻动物秀&lt;会场&gt;",

    # === Neo City ===
    "&lt;Year 2021&gt; Average Town Entrance": "&lt;2021年&gt; 普通城镇入口",
    "&lt;Year 2021&gt; Average Town Outskirt": "&lt;2021年&gt; 普通城镇郊外",
    "&lt;Year 2021&gt; Average Town Playground": "&lt;2021年&gt; 普通城镇游乐场",
    "&lt;Year 2099&gt; Midnight Harbor Entrance": "&lt;2099年&gt; 午夜港口入口",
    "&lt;Year 2099&gt; Midnight Harbor Loading Dock": "&lt;2099年&gt; 午夜港口装卸场",
    "&lt;Year 2099&gt; Midnight Harbor Pier": "&lt;2099年&gt; 午夜港口码头",
    "&lt;Year 2099&gt; Midnight Harbor Warehouse": "&lt;2099年&gt; 午夜港口仓库",
    "&lt;Year 2215&gt; Bombed City Center Overpass": "&lt;2215年&gt; 轰炸城市中心天桥",
    "&lt;Year 2215&gt; Bombed City Center Retail District": "&lt;2215年&gt; 轰炸城市中心商业区",
    "&lt;Year 2215&gt; Bombed City Center Shopping District": "&lt;2215年&gt; 轰炸城市中心购物区",
    "&lt;Year 2215&gt; Bombed City Center Square": "&lt;2215年&gt; 轰炸城市中心广场",
    "&lt;Year 2216&gt; Ruined City Center": "&lt;2216年&gt; 废墟城市中心",
    "&lt;Year 2216&gt; Ruined City Construction Site": "&lt;2216年&gt; 废墟城市工地",
    "&lt;Year 2216&gt; Ruined City Intersection": "&lt;2216年&gt; 废墟城市交叉口",
    "&lt;Year 2216&gt; Ruined City Land Mark": "&lt;2216年&gt; 废墟城市地标",
    "&lt;Year 2227&gt; Dangerous City Center": "&lt;2227年&gt; 危险城市中心",
    "&lt;Year 2227&gt; Dangerous City Construction Site": "&lt;2227年&gt; 危险城市工地",
    "&lt;Year 2227&gt; Dangerous City Intersection": "&lt;2227年&gt; 危险城市交叉口",
    "&lt;Year 2230&gt; Dangerous Tower Emergency Exit": "&lt;2230年&gt; 危险塔楼紧急出口",
    "&lt;Year 2230&gt; Dangerous Tower Lobby": "&lt;2230年&gt; 危险塔楼大厅",
    "&lt;Year 2230&gt; Dangerous Tower Penthouse": "&lt;2230年&gt; 危险塔楼顶层",
    "&lt;Year 2230&gt; Dangerous Tower Ventilator": "&lt;2230年&gt; 危险塔楼通风口",
    "&lt;Year 2503&gt; Air Battleship Area A": "&lt;2503年&gt; 空中战舰A区",
    "&lt;Year 2503&gt; Air Battleship Area B": "&lt;2503年&gt; 空中战舰B区",
    "&lt;Year 2503&gt; Air Battleship Bow": "&lt;2503年&gt; 空中战舰船首",
    "&lt;Year 2503&gt; Air Battleship Stern": "&lt;2503年&gt; 空中战舰船尾",
    "Tera Forest Time Gate": "泰拉森林时间之门",
    "Old Tree in Tera Forest": "泰拉森林的古树",
    "Residential Area 1": "住宅区1",
    "Residential Area 2": "住宅区2",
    "Residential Area 3": "住宅区3",
    "Residential Area 4": "住宅区4",
    "Residential Area 5": "住宅区5",
    "Residential Area 6": "住宅区6",

    # === Colossus ===
    "Colossus Dangerous Road": "巨人危险之路",
    "Colossus East Road 1": "巨人东路1",
    "Colossus East Road 2": "巨人东路2",
    "Colossus East Road 3": "巨人东路3",
    "Colossus West Road 1": "巨人西路1",
    "Colossus West Road 2": "巨人西路2",
    "Colossus West Road 3": "巨人西路3",
    "Inside the Stone Colossus 1": "石巨人体内1",
    "Inside the Stone Colossus 2": "石巨人体内2",
    "Inside the Stone Colossus 3": "石巨人体内3",
    "Stone Colossus Arm": "石巨人手臂",
    "Stone Colossus Heart": "石巨人之心",
    "Stone Colossus Torso 1": "石巨人躯干1",
    "Stone Colossus Torso 2": "石巨人躯干2",
    "Stone Colossus Torso 3": "石巨人躯干3",

    # === Azwan / Kritias ===
    "Azwan Obelisk": "阿兹万方尖碑",
    "Azwan Refuge Zone": "阿兹万避难区",
    "Hilla's Tower": "希拉之塔",
    "Hilla's Tower Entrance": "希拉之塔入口",
    "Kritias": "克里提亚斯",
    "Ranheim Academy": "兰海姆学院",

    # === Golden Temple ===
    "Golden Temple": "黄金寺院",

    # === Coke Town ===
    "Coke Town": "可乐小镇",
    "Coke Town Sundry Goods Shop": "可乐小镇杂货店",
    "Coke ValleyI": "可乐山谷I",
    "Coke ValleyII": "可乐山谷II",
    "Coke ValleyIII": "可乐山谷III",
    "Coke ValleyIV": "可乐山谷IV",
    "Coke Ski Camp": "可乐滑雪场",
    "Coke Ski Camp B1648": "可乐滑雪场B1648",
    "Empty House in Coke Town": "可乐小镇的空屋",

    # === Sakura Castle ===
    "Sakura Castle Front Gate": "樱花城正门",
    "Sakura Castle Garden 1": "樱花城花园1",
    "Sakura Castle Garden 2": "樱花城花园2",
    "Sakura Castle Garden 3": "樱花城花园3",
    "Sakura Castle Garden 4": "樱花城花园4",
    "Sakura Castle Outskirts": "樱花城郊外",
    "Tsukino Tower 1st Floor": "月野塔1层",
    "Tsukino Tower 2nd Floor": "月野塔2层",
    "Tsukino Tower 3rd Floor": "月野塔3层",
    "Tsukino Tower 4th Floor": "月野塔4层",
    "Tsukino Tower 5th Floor": "月野塔5层",

    # === Pirate Ship / Island ===
    "Pillage of Treasure Island": "宝藏岛掠夺",
    "Red-Nose Pirate Den 1": "红鼻海盗窝1",
    "Red-Nose Pirate Den 2": "红鼻海盗窝2",
    "Red-Nose Pirate Den 3": "红鼻海盗窝3",
    "Over the Pirate Ship &lt;Exit Map&gt;": "海盗船上方 &lt;出口地图&gt;",
    "To the Slumbering Dragon Island ": "前往沉睡龙岛",
    "Santa's House": "圣诞老人之家",

    # === Azwan ===
    "Spirit Zone Limbo": "灵魂区域边缘",
    "Abode of the Soulless": "无魂者之居",
    "Somewhere in the Temple": "神殿某处",
    "Ascetic Room 1": "苦行房1",
    "Ascetic Room 2": "苦行房2",

    # === Veritas ===
    "Veritas": "真理之地",

    # === Dragon Nest / Boss areas ===
    "Battlefield of Fire and Darkness": "火与暗的战场",
    "Battlefield of Fire and Water": "火与水的战场",
    "Battlefield of Resurrection": "复活的战场",
    "Battlefield of Water and Darkness": "水与暗的战场",
    "Front of Arkarium's Altar": "阿卡伊农祭坛前方",
    "Arkarium's Altar": "阿卡伊农祭坛",
    "Black Mage's Main Corridor": "黑魔法师主走廊",
    "Black Magician's Lab": "黑魔法师实验室",
    "Foyer of Darkness": "黑暗前厅",
    "Hallowed Ground": "圣地",
    "Room of Suffering": "苦难之房",

    # === Misc map areas ===
    "Abandoned Temple": "废弃的寺庙",
    "Aerial Prison": "空中监狱",
    "An Old, Empty House": "一座空旧的房屋",
    "Attic": "阁楼",
    "Back to the Leafre Past": "回到过去的神木村",
    "Battle Exit Map": "战斗出口地图",
    "Beetle Forest": "甲虫森林",
    "Breath of Lava &lt;Level 1&gt;": "熔岩气息 &lt;第1层&gt;",
    "Breath of Lava &lt;Level 2&gt;": "熔岩气息 &lt;第2层&gt;",
    "Cave of the Deceased": "亡者之穴",
    "Challenging Xerxes": "挑战泽克西斯",
    "Chief's House": "村长之家",
    "Chino's Lift: The Road Down": "奇诺的升降机：下坡路",
    "Chino's Lift: The Road Up": "奇诺的升降机：上坡路",
    "Chino's Station": "奇诺站",
    "Coliseum Corridor 1": "斗技场走廊1",
    "Coliseum Corridor 2": "斗技场走廊2",
    "Coliseum Corridor 3": "斗技场走廊3",
    "Coliseum Entrance": "斗技场入口",
    "Inside the Coliseum": "斗技场内部",
    "Road to the Coliseum 1": "通往斗技场之路1",
    "Road to the Coliseum 2": "通往斗技场之路2",
    "Road to the Coliseum 3": "通往斗技场之路3",
    "Corrupted Magic Forest 1": "腐蚀魔法森林1",
    "Corrupted Magic Forest 2": "腐蚀魔法森林2",
    "Corrupted Magic Forest 3": "腐蚀魔法森林3",
    "Counseling Room": "咨询室",
    "Cranky Forest": "暴躁森林",
    "Creepy Humming Forest Trail": "诡异嗡嗡森林小径",
    "Crystal Gorge": "水晶峡谷",
    "Defeat Monsters": "击败怪物",
    "Dreamy Forest Trail": "梦幻森林小径",
    "Drummer Bunny's Lair": "鼓手兔子的巢穴",
    "Empty House I": "空屋I",
    "Empty House II": "空屋II",
    "Explorer Base": "探险者基地",
    "Fiery Ravine": "炽热峡谷",
    "Fiery Rocky Hills": "炽热岩石丘陵",
    "Foggy Forest": "迷雾森林",
    "Forest : Crossroad": "森林：十字路",
    "Forest of Darkness 1": "黑暗森林1",
    "Forest of Laments 1": "哀叹之森1",
    "Forest of Laments 2": "哀叹之森2",
    "Forest of Laments 3": "哀叹之森3",
    "Forest of Laments 4": "哀叹之森4",
    "Forest of Laments 5": "哀叹之森5",
    "Forest of Pain 1": "痛苦之森1",
    "Forest of Pain 2": "痛苦之森2",
    "Forest of Pain 3": "痛苦之森3",
    "Forest of Pain 4": "痛苦之森4",
    "Forest of Pain 5": "痛苦之森5",
    "Forest of Sorrows 1": "悲伤之森1",
    "Forest of Sorrows 2": "悲伤之森2",
    "Forest of Sorrows 3": "悲伤之森3",
    "Forest of Sorrows 4": "悲伤之森4",
    "Forest of Sorrows 5": "悲伤之森5",
    "Forest of the Priest": "祭司之森",
    "Freezing Forest 1": "冰冻森林1",
    "Freezing Forest 2": "冰冻森林2",
    "Frilled Field": "褶边田地",
    "Gale Pleateau": "狂风高原",
    "Ghost Mansion": "幽灵公馆",
    "Gray's Prairie": "格雷草原",
    "Guardian Room 1": "守护者之间1",
    "Guardian Room 2": "守护者之间2",
    "Hidden Tower": "隐藏之塔",
    "Isolated Forest": "孤立的森林",
    "Isolated Swamp": "孤立的沼泽",
    "Lush Forest": "茂密森林",
    "Mutant Tiguru Forest": "变异提古鲁森林",
    "Mutant Tino Forest": "变异提诺森林",
    "Mutant Tiru Forest": "变异提鲁森林",
    "Neglected Strolling Path": "被忽视的散步小路",
    "Old Swamp": "旧沼泽",
    "Past of the Verdure": "翠绿之过去",
    "Path of Darkness 1": "黑暗之路1",
    "Path of Darkness 2": "黑暗之路2",
    "Roof of the Resurrection Tower": "复活塔屋顶",
    "Safety Zone": "安全区域",
    "Scorching Forest 1": "灼热森林1",
    "Scorching Forest 2": "灼热森林2",
    "Scrubby Garden": "灌木花园",
    "Sinister Inner Lot": "阴险的内部地块",
    "Snake Area": "蛇的区域",
    "Small Alley": "小巷",
    "Snow Soul's Resting Place": "雪之灵魂安息处",
    "Dark Spore Hill": "黑暗孢子丘",
    "Darkness Forest 2": "黑暗森林2",
    "Swarm Habitat 1": "虫群栖息地1",
    "Swarm Habitat 2": "虫群栖息地2",
    "Swarm Habitat 3": "虫群栖息地3",
    "Swarm Stronghold": "虫群要塞",
    "Territory of Wandering Bear": "流浪熊领地",
    "The Burning Forest": "燃烧森林",
    "The Cave of Trial I": "试炼洞穴I",
    "The Cave of Trial II": "试炼洞穴II",
    "The Restoring Memory": "恢复的记忆",
    "Top of Chino's Station": "奇诺站顶部",
    "Tunnel": "隧道",
    "Warning! Alien Sightings Area": "警告！外星人出没区域",
    "Weird Room": "奇怪的房间",
    "Wild Bear Area 1": "野熊区域1",
    "Wild Bear Area 2": "野熊区域2",
    "Wild Bear Area 3": "野熊区域3",
    "Weathered Rocky Zone": "风化的岩石地带",
    "Ruins in Flames": "燃烧的废墟",
    "Twilight of Gods": "诸神的黄昏",
    "Lawless Zone 1": "无法地带1",
    "Lawless Zone 2": "无法地带2",
    "Lawless Zone 3": "无法地带3",
    "Kupo's Ride: The Road Down": "库波的缆车：下坡路",
    "Kupo's Ride: The Road Up": "库波的缆车：上坡路",
    "Kupo's Station": "库波站",
    "Mayor": "市政厅",

    # === Battle modes ===
    "Attack Mode Large Battlefield (Easy)": "攻击模式大型战场(简单)",
    "Attack Mode Large Battlefield (Hard)": "攻击模式大型战场(困难)",
    "Attack Mode Large Battlefield (Hell)": "攻击模式大型战场(地狱)",
    "Attack Mode Large Battlefield (Normal)": "攻击模式大型战场(普通)",
    "Attack Mode Small Battlefield (Easy)": "攻击模式小型战场(简单)",
    "Attack Mode Small Battlefield (Hard)": "攻击模式小型战场(困难)",
    "Attack Mode Small Battlefield (Hell)": "攻击模式小型战场(地狱)",
    "Attack Mode Small Battlefield (Normal)": "攻击模式小型战场(普通)",
    "Defense Mode Large Battlefield (Easy)": "防御模式大型战场(简单)",
    "Defense Mode Large Battlefield (Hard)": "防御模式大型战场(困难)",
    "Defense Mode Large Battlefield (Hell)": "防御模式大型战场(地狱)",
    "Defense Mode Large Battlefield (Normal)": "防御模式大型战场(普通)",
    "Defense Mode Small Battlefield (Easy)": "防御模式小型战场(简单)",
    "Defense Mode Small Battlefield (Hard)": "防御模式小型战场(困难)",
    "Defense Mode Small Battlefield (Hell)": "防御模式小型战场(地狱)",
    "Defense Mode Small Battlefield (Normal)": "防御模式小型战场(普通)",
    "Occupy Mode Large Battlefield (Easy)": "占领模式大型战场(简单)",
    "Occupy Mode Large Battlefield (Hard)": "占领模式大型战场(困难)",
    "Occupy Mode Large Battlefield (Hell)": "占领模式大型战场(地狱)",
    "Occupy Mode Large Battlefield (Normal)": "占领模式大型战场(普通)",
    "Occupy Mode Lobby": "占领模式大厅",
    "Occupy Mode Small Battlefield (Easy)": "占领模式小型战场(简单)",
    "Occupy Mode Small Battlefield (Hard)": "占领模式小型战场(困难)",
    "Occupy Mode Small Battlefield (Hell)": "占领模式小型战场(地狱)",
    "Occupy Mode Small Battlefield (Normal)": "占领模式小型战场(普通)",
    "Supply Mode Battlefield": "补给模式战场",
    "Supply Mode Large Battlefield": "补给模式大型战场",

    # === The Forest That Disappeared ===
    "The Forest That Disappeared": "消失的森林",

    # === Sorcerer's Room ===
    "Sorcerer's Room ": "术士之室",

    # === Dead Mine ===
    "Dead Mine 1": "死亡矿坑1",
    "Dead Mine 2": "死亡矿坑2",
    "Dead Mine 3": "死亡矿坑3",
    "Dead Mine 4": "死亡矿坑4",
    "Dead Mine 5": "死亡矿坑5",
    "Dead Mine 6": "死亡矿坑6",
    "Dead Mine 7": "死亡矿坑7",

    # === Deep Place of Temple ===
    "The Cave of Trial I": "试炼洞穴I",
    "The Cave of Trial II": "试炼洞穴II",

    # === Field of rabbit ===
    "Rabbit Field 1": "兔子草原1",
    "Rabbit Field 2": "兔子草原2",
    "Rabbit Field 3": "兔子草原3",

    # === Misc missing ===
    "Area 15-1": "区域15-1",
    "Armory 1": "武器库1",
    "Armory 2": "武器库2",
    "Fevered Land": "炽热之地",
    "Forked Road : East Sea": "岔路口：东海",
    "Forked Road : West Sea": "岔路口：西海",
    "Moon Ridge": "月岭",
    "Time Lane": "时间车道",
    "Zoo": "动物园",
    "Tribal Refugee Camp": "部落难民营",
    "Happy Village": "幸福村",
    "Forest of Coke Golem": "可乐石人森林",
}


MAPDESC = {
    "A toy town located above Ludus Lake. It's built on top of two towers. You can ride the Airship to move to different areas. \n\n#cConnected areas\n - Orbis Station": "位于露迪斯湖上方的玩具小镇。建在两座塔之上。可以乘坐飞艇前往不同区域。\n\n#c相连区域\n - 天空之城站台",
    "A special facility built to protect Maple World from alien invasions. It's located at the foot of Eos Tower. \n\n#cConnected areas\n - Ludibrium": "为保护冒险岛世界免受外星人入侵而建造的特殊设施。位于艾奥斯塔脚下。\n\n#c相连区域\n - 玩具城",
    "A town inhabited by characters from Korean folk tales. It's located at the foot of Helios Tower. \n\n#cConnected areas\n - Ludibrium": "居住着韩国民间故事人物的村庄。位于赫利奥斯塔脚下。\n\n#c相连区域\n - 玩具城",
    "An underwater city located deep in the ocean. You can use the Dolphin Taxi or the ocean paths to move to different areas. \n\n#cConnected areas\n - El Nath \n - Korean Folk Town \n - Herb Town": "位于海洋深处的海底城市。可以乘坐海豚出租车或通过海洋通道前往不同区域。\n\n#c相连区域\n - 冰封雪域\n - 童话村\n - 百草堂",
    "A town of nature-loving Halflingers. The Halflingers maintain a symbiotic relationship with the Dragons. You can use the station to move to different areas. \n\n#cConnected areas\n - Orbis Station \n - Temple of Time Entrance": "热爱自然的半灵族村庄。半灵族与龙保持共生关系。可以使用车站前往不同区域。\n\n#c相连区域\n - 天空之城站台\n - 时间神殿入口",
    "A town veiled in fog, located in Mu Lung Garden. It's inhabited by Pandas training to become Sages. You can ride the Crane to move to different areas.\n\n#cConnected areas\n - Orbis \n - Herb Town": "位于武陵桃源中雾气弥漫的村庄。居住着修行的熊猫。可以乘坐仙鹤前往不同区域。\n\n#c相连区域\n - 天空之城\n - 百草堂",
    "A town floating above the lake in Mu Lung Garden. Many award-winning herbs are cultivated here. Walk or ride the Taxi to move to different areas.\n\n#cConnected areas\n - Mu Lung \n - Aquarium": "漂浮在武陵桃源湖面上的村庄。这里种植着许多获奖草药。可以步行或乘坐出租车前往不同区域。\n\n#c相连区域\n - 武陵\n - 水族馆",
    "A town centered around a legendary oasis in the middle of the desert. You can ride the Genie or walk to move to different areas. \n\n#cConnected areas\n - Orbis \n - Magatia": "以沙漠中央传说中的绿洲为中心的村庄。可以乘坐精灵或步行前往不同区域。\n\n#c相连区域\n - 天空之城\n - 马加提亚",
    "A desert town whose culture revolves around the study of Alchemy. Two alchemist societies, Zenumist and Alcadno, are in conflict there. \n\n#cConnected areas\n - Ariant": "以炼金术研究为核心文化的沙漠城镇。杰尼斯托和阿尔卡诺两大炼金术学会在此对峙。\n\n#c相连区域\n - 阿里安特",
    "The temple where the Goddess of Time resides. The past, present, and future all exist in this place. You can transform into a dragon and fly out to different areas. \n\n#cConnected areas\n - Leafre": "时间女神居住的神殿。过去、现在和未来同时存在于此地。可以变身为龙飞往不同区域。\n\n#c相连区域\n - 神木村",
    "An ancient kingdom of magic that was believed to be wiped off the face of Maple World centuries ago. Hosts Ranheim Academy and the floating Palace Trueffet. You can use the streets or the Dimensional Portal in the academy to move to different areas.": "被认为是数百年前从冒险岛世界消失的古老魔法王国。拥有兰海姆学院和浮空宫殿特鲁费。可以通过街道或学院中的次元传送门前往不同区域。",
}


def translate_value(val, field_name=None):
    """Translate a single value using the dictionaries."""
    # Skip already-translated Chinese values
    if any('一' <= c <= '鿿' for c in val):
        return val
    # Check mapDesc first (longest keys)
    if field_name in ('mapDesc',) and val in MAPDESC:
        return MAPDESC[val]
    # General mapDesc lookup
    if val in MAPDESC:
        return MAPDESC[val]
    # Check streetName first (smaller dict)
    if field_name == 'streetName' and val in STREET:
        return STREET[val]
    # Check mapName
    if field_name == 'mapName' and val in MAPNAME:
        return MAPNAME[val]
    # General lookup
    if val in STREET:
        return STREET[val]
    if val in MAPNAME:
        return MAPNAME[val]
    return None


def translate_entry(inner_xml, eid):
    """Translate all values within an entry's inner XML."""
    def replace_value(match):
        full = match.group(0)
        fname_match = re.search(r'name="(\w+)"', full)
        val_match = re.search(r'value="([^"]*)"', full)
        if not fname_match or not val_match:
            return full
        fname = fname_match.group(1)
        old_val = val_match.group(1)
        new_val = translate_value(old_val, fname)
        if new_val and new_val != old_val:
            return full.replace(f'value="{old_val}"', f'value="{new_val}"')
        return full

    # Handle multi-line value attributes: <string name="..." \n value="..." />
    result = re.sub(
        r'<string\s+name="[^"]*"\s*\n\s*value="[^"]*"\s*/>',
        replace_value,
        inner_xml
    )
    # Handle single-line: <string name="..." value="..." />
    result = re.sub(
        r'<string\s+name="[^"]*"\s+value="[^"]*"\s*/>',
        replace_value,
        result
    )
    return result


def main():
    # Parse both files
    def parse_entries(filename):
        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()
        # Get ordered list of IDs and their content
        entries = []
        for m in re.finditer(r'<imgdir name="(\d+)">(.*?)</imgdir>', content, re.DOTALL):
            eid = m.group(1)
            inner = m.group(2)
            entries.append((eid, inner))
        return entries

    orig_entries = parse_entries(f'{BASE}/ossyria.xml')
    trans_entries = parse_entries(f'{BASE}/ossyria_c.xml')

    # Build dict of already-translated entries from ossyria_c.xml
    trans_dict = {}
    for eid, inner in trans_entries:
        trans_dict[eid] = inner

    # Get original order
    orig_order = [eid for eid, _ in orig_entries]
    orig_dict = {eid: inner for eid, inner in orig_entries}

    # Find missing IDs
    missing_ids = sorted(set(orig_dict.keys()) - set(trans_dict.keys()), key=int)
    print(f'Missing entries: {len(missing_ids)}')

    # Only translate MISSING entries from original source
    untranslated = set()
    for eid in missing_ids:
        inner = orig_dict[eid]
        translated_inner = translate_entry(inner, eid)
        # Check for untranslated English values
        for val_match in re.finditer(r'value="([^"]*)"', translated_inner):
            val = val_match.group(1)
            if re.search(r'[a-zA-Z]{3,}', val) and not val.startswith('#'):
                untranslated.add(val)
        trans_dict[eid] = translated_inner

    if untranslated:
        print(f'\nUntranslated values ({len(untranslated)}):')
        for v in sorted(untranslated):
            print(f'  {v}')

    # Build output in original order
    lines = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<imgdir name="Map.img">',
        '    <imgdir name="ossyria">',
    ]

    for eid in orig_order:
        inner = trans_dict.get(eid, '')
        if not inner:
            print(f'  WARNING: ID {eid} not found in translated dict!')
            continue
        lines.append(f'        <imgdir name="{eid}">')
        # Add inner lines with proper indentation
        for line in inner.strip().split('\n'):
            stripped = line.strip()
            if stripped:
                # Handle multi-line value strings
                if stripped.startswith('value='):
                    lines.append(f'            {stripped}')
                else:
                    lines.append(f'            {stripped}')
        lines.append('        </imgdir>')

    lines.append('    </imgdir>')
    lines.append('</imgdir>')

    output = '\n'.join(lines) + '\n'
    with open(f'{BASE}/ossyria_c.xml', 'w', encoding='utf-8') as f:
        f.write(output)

    print(f'\nDone! Wrote {len(orig_order)} entries to ossyria_c.xml')
    print(f'Line count: {len(lines)}')


if __name__ == '__main__':
    main()
