# -*- coding: utf-8 -*-
import re

translations = {
    " Monster Carnival": " 怪物嘉年华",
    "1st Match ": "第1场比赛 ",
    "2nd Job Advancement": "2转考场",
    "2nd Match ": "第2场比赛 ",
    "3000 Days Memories Hall": "3000天回忆大厅",
    "3rd Job Advancement": "3转考场",
    "3rd Match": "第3场比赛",
    "4th Job Advancement": "4转考场",
    "4th Match ": "第4场比赛 ",
    "5th Match ": "第5场比赛 ",
    "8th Anniversary Event": "8周年庆典",
    "A Crack on the Wall": "墙壁裂缝",
    "A Dark Place": "黑暗之地",
    "A Secret Door to the Aerial Prison": "通往空中监狱的密门",
    "Abandoned Cave ": "废弃洞穴 ",
    "Abandoned Graveyard": "废弃墓地",
    "Abandoned Hideout Entrance": "废弃据点入口",
    "Abandoned Hideout": "废弃据点",
    "Abandoned Subway Station": "废弃地铁站",
    "Abandoned Tower &lt;Stage 2&gt;": "废弃塔楼 &lt;第2阶段&gt;",
    "Abandoned Tower &lt;Stage 3&gt;": "废弃塔楼 &lt;第3阶段&gt;",
    "Abandoned Tower &lt;Stage 4&gt;": "废弃塔楼 &lt;第4阶段&gt;",
    "Abandoned Tower &lt;Stage 5&gt;": "废弃塔楼 &lt;第5阶段&gt;",
    "Abandoned Tower&lt;Bonus&gt;": "废弃塔楼&lt;奖励&gt;",
    "Abandoned Tower&lt;Determine to adventure&gt;": "废弃塔楼&lt;冒险决心&gt;",
    "Abandoned Tower&lt;End of Journey&gt;": "废弃塔楼&lt;旅途终点&gt;",
    "Abandoned Tower&lt;Stage 1&gt;": "废弃塔楼&lt;第1阶段&gt;",
    "Abandoned Tower&lt;Stage 2&gt;": "废弃塔楼&lt;第2阶段&gt;",
    "Abandoned Tower&lt;Stage 3&gt;": "废弃塔楼&lt;第3阶段&gt;",
    "Abandoned Tower&lt;Stage 5&gt;": "废弃塔楼&lt;第5阶段&gt;",
    "Abyssal Cave": "深渊洞穴",
    "Advanced Secret Herb Patch": "高级秘密药草田",
    "Advanced Secret Mine": "高级秘密矿山",
    "Advancement Testing Grounds": "转职试验场",
    "Advent of the Great Spirit": "伟大精灵降临",
    "Aerial Prison": "空中监狱",
    "Afrien's Memory ": "阿夫里恩的记忆 ",
    "After the Battle": "战后",
    "Agent HQ": "特工总部",
    "Alcadno Society 1": "阿尔卡诺协会1",
    "Alcadno Society 2": "阿尔卡诺协会2",
    "Alcadno Society 3": "阿尔卡诺协会3",
    "Alcaster's Laboratory": "阿尔卡斯特的实验室",
    "Alchemy Lab": "炼金术实验室",
    "Altar of Darkness": "黑暗祭坛",
    "Alternate Edelstein Park": "平行埃德尔斯坦公园",
    "Amateur Monster Battle Lobby": "业余怪物对战大厅",
    "Ancient Ice Cave": "远古冰洞",
    "Angelic Buster Charm Explosion": "天使破坏者魅力爆发",
    "Angelic Buster Training End": "天使破坏者训练结束",
    "Ani's Jail": "阿尼的牢笼",
    "Another World : Practice Field": "异世界：练习场",
    "Aqua Road Ferry": "水下世界渡轮",
    "Ardentmill": "热烈磨坊",
    "Area 1": "区域1",
    "Area 2": "区域2",
    "Area 3": "区域3",
    "Ariant Back Street": "阿里安特后街",
    "Ariant Castle &lt;King's Room&gt;": "阿里安特城堡 &lt;国王房间&gt;",
    "Ariant Coliseum": "阿里安特竞技场",
    "Ariant Desert": "阿里安特沙漠",
    "Ariant Studio  ": "阿里安特摄影棚  ",
    "Ariant Studio": "阿里安特摄影棚",
    "Ariant Treasure Vault Entrance": "阿里安特宝库入口",
    "Ariant Treasure Vault": "阿里安特宝库",
    "Aromatic Zombie Mushmom Forest": "芳香僵尸蘑菇森林",
    "Art Room": "美术室",
    "Ash-Covered Land's End": "灰烬覆盖的大地尽头",
    "Attic": "阁楼",
    "Audience Room": "觐见室",
    "Audish's Ambush": "奥迪什的伏击",
    "Authority of the Captain": "船长的威严",
    "Auto Security Area": "自动安全区域",
    "Axe Stump Stomping Grounds": "斧头树桩践踏场",
    "Azwan Refugee Zone": "阿兹万难民区",
    "Azwan": "阿兹万",
    "B1": "B1",
    "B2": "B2",
    "B3": "B3",
    "Back Alley of Mu Lung Training Center": "武陵训练中心后巷",
    "Back Yard  ": "后院  ",
    "Back of Space Mine  ": "太空矿山后方  ",
    "Back to Town": "回城",
    "Balrog's Cave within a Dream": "梦境中的巴尔洛格洞穴",
    "Bart's Room": "巴特的房间",
    "Battle Against Maha": "与玛哈的战斗",
    "Battle Arena 1 Entrance": "战斗竞技场1入口",
    "Battle Arena 1": "战斗竞技场1",
    "Battle Arena 2 Entrance": "战斗竞技场2入口",
    "Battle Arena 2": "战斗竞技场2",
    "Battle Arena 3 Entrance": "战斗竞技场3入口",
    "Battle Arena 3": "战斗竞技场3",
    "Battle Arena Exit": "战斗竞技场出口",
    "Battle Arena Lobby": "战斗竞技场大厅",
    "Battle Monster Hideout": "战斗怪物据点",
    "Battle Playback": "战斗回放",
    "Battle Square": "战斗广场",
    "Battleworn Mountain": "战火纷飞的山脉",
    "Beanstalk Climb  ": "魔豆攀爬  ",
    "Bedroom": "卧室",
    "Before the Final Battle": "最终决战前",
    "Beginner Monster Battle Lobby": "初级怪物对战大厅",
    "Beginning of the Maze…": "迷宫的起点…",
    "Behind the Mine": "矿山背后",
    "Behind the Stronghold ": "据点后方 ",
    "Bellflower Hill": "桔梗花山丘",
    "Below Zombie Mushmom Hill": "僵尸蘑菇山丘下方",
    "Besieged Path of the Glowcaves": "荧光洞穴被围攻之路",
    "Big Bad Wolf's Victory ": "大灰狼的胜利 ",
    "Birk's Hideout": "伯克的据点",
    "Bizarre Alien Dimension 1": "奇异外星维度1",
    "Bizarre Alien Dimension 2": "奇异外星维度2",
    "Bizarre Alien Dimension 3": "奇异外星维度3",
    "Bizarre Alien Dimension 4": "奇异外星维度4",
    "Bizarre Alien Dimension 5": "奇异外星维度5",
    "Bizzaro Central Hall": "比扎罗中央大厅",
    "Black Crow's Domain": "黑鸦的领地",
    "Black Dragon Hometown": "黑龙故乡",
    "Black Mage's Antechamber": "黑魔法师的前厅",
    "Black Mage's Main Corridor 1": "黑魔法师的主走廊1",
    "Black Mage's Main Corridor 2": "黑魔法师的主走廊2",
    "Black Mage's Main Corridor": "黑魔法师的主走廊",
    "Black Mage's Memories": "黑魔法师的记忆",
    "Black Mage's Temple": "黑魔法师的神殿",
    "Black Mountain Hill": "黑山丘陵",
    "Black Road": "黑色之路",
    "Black Terrace": "黑色露台",
    "Black Wings' Hideout": "黑翼的据点",
    "Blooming Forest Backstreet": "繁花森林后街",
    "Blooming Forest": "繁花森林",
    "Bonus Stage": "奖励关卡",
    "Booby Trap! Laboratory Jail": "陷阱！实验室牢房",
    "Bowman Instructional School in Danger ": "危机中的弓箭手教练学校 ",
    "Bowman Instructional School": "弓箭手教练学校",
    "Bowman Test Site": "弓箭手考场",
    "Bowman Training Center": "弓箭手训练中心",
    "Bowman's Golem Garden": "弓箭手的石头人花园",
    "Burning Forest 1": "燃烧森林1",
    "Burning Forest 2": "燃烧森林2",
    "Burning Forest 3": "燃烧森林3",
    "Carnival Field &lt;Battle Field&gt;": "嘉年华场地 &lt;战场&gt;",
    "Carnival Field &lt;Lobby&gt;": "嘉年华场地 &lt;大厅&gt;",
    "Carnival Field &lt;Resurrection&gt;": "嘉年华场地 &lt;复活&gt;",
    "Carnival Field &lt;The Defeated&gt;": "嘉年华场地 &lt;败者&gt;",
    "Carnival Field &lt;Victorious&gt;": "嘉年华场地 &lt;胜者&gt;",
    "Carnival Field 1 &lt;Lobby&gt;": "嘉年华场地1 &lt;大厅&gt;",
    "Carnival Field 1&lt;Battlefield&gt;": "嘉年华场地1&lt;战场&gt;",
    "Carnival Field 1&lt;Lobby&gt;": "嘉年华场地1&lt;大厅&gt;",
    "Carnival Field 2 &lt;Lobby&gt;": "嘉年华场地2 &lt;大厅&gt;",
    "Carnival Field 2&lt;Battlefield&gt;": "嘉年华场地2&lt;战场&gt;",
    "Carnival Field 2&lt;Lobby&gt;": "嘉年华场地2&lt;大厅&gt;",
    "Carnival Field 3 &lt;Lobby&gt;": "嘉年华场地3 &lt;大厅&gt;",
    "Carnival Field 3&lt;Battlefield&gt;": "嘉年华场地3&lt;战场&gt;",
    "Carnival Field 3&lt;Lobby&gt;": "嘉年华场地3&lt;大厅&gt;",
    "Carnival Field 4 &lt;Lobby&gt;": "嘉年华场地4 &lt;大厅&gt;",
    "Carnival Field 5 &lt;Lobby&gt;": "嘉年华场地5 &lt;大厅&gt;",
    "Carnival Field 6 &lt;Lobby&gt;": "嘉年华场地6 &lt;大厅&gt;",
    "Cassandra's Shore": "卡桑德拉的海岸",
    "Castle Back Alley": "城堡后巷",
    "Castle Entrance": "城堡入口",
    "Castle Hallway": "城堡走廊",
    "Castle Main Hall": "城堡正厅",
    "Castle Party Hall": "城堡派对厅",
    "Castle Safe Zone": "城堡安全区",
    "Cave of Black Witches": "黑女巫洞穴",
    "Cave of Silence": "寂静洞穴",
    "Center Banquet": "中央宴会厅",
    "Center Lab": "中央实验室",
    "Central Clocktower Center": "中央钟楼中心",
    "Cheese Storage": "奶酪仓库",
    "Chumji's Front Yard": "春吉的前院",
    "Clandestine Ruins": "隐秘遗迹",
    "Clash of the Xenoroids": "异形机器人冲突",
    "Classified Lab": "机密实验室",
    "Classroom Under Construction": "施工中的教室",
    "Close to the Wind": "乘风而行",
    "Closed Lab": "封闭实验室",
    "Coco Island": "可可岛",
    "Cold Cave": "冰冷洞穴",
    "Cole's Mine": "科尔的矿山",
    "Coliseum Exit": "竞技场出口",
    "Coliseum Waiting Area": "竞技场等候区",
    "Coliseum": "竞技场",
    "Colossal Root": "巨根",
    "Conference Room of the Alliance": "联盟会议室",
    "Conference Side Room": "会议侧室",
    "Confusing Time": "混乱时间",
    "Corridor": "走廊",
    "Craggy Top Battleground": "崎岖山顶战场",
    "Cursed Ellinia Forest": "被诅咒的魔法密林",
    "Cursed Ice Moor": "被诅咒的冰原",
    "Cygnus Knights  ": "冒险骑士团  ",
    "Cygnus Knights ": "冒险骑士团 ",
    "Cygnus Knights": "冒险骑士团",
    "Dahlia Garden": "大丽花园",
    "Danger! Makeshift Airport": "危险！临时机场",
    "Dangerous Cave": "危险洞穴",
    "Dangerous Forest Alley": "危险森林小巷",
    "Dangerous Forest Entrance": "危险森林入口",
    "Dangerous Forest": "危险森林",
    "Dangerous Hide-and-Seek": "危险捉迷藏",
    "Dangerous Info Shop": "危险情报商店",
    "Dangerous Library": "危险图书馆",
    "Dangerous Power Plant": "危险发电厂",
    "Dangerous Rocky Mountain": "危险岩石山",
    "Dangerous Roof of the First Tower": "第一座塔的危险屋顶",
    "Dangerous Sea 1": "危险海域1",
    "Dangerous Sea 2": "危险海域2",
    "Dangerous Swamp": "危险沼泽",
    "Dangerously Isolated Forest": "危险的孤立森林",
    "Dark Griffey Forest": "黑暗狮鹫森林",
    "Dark Lab 1": "黑暗实验室1",
    "Dark Lab 2": "黑暗实验室2",
    "Dark Lab": "黑暗实验室",
    "Dark Lord's Practice Field": "黑暗领主的练习场",
    "Dark Shaft": "黑暗竖井",
    "Dark Tower 1": "黑暗之塔1",
    "Dark Tower 2": "黑暗之塔2",
    "Dark Tower 3": "黑暗之塔3",
    "Dark Tower 4": "黑暗之塔4",
    "Dark Tower 5": "黑暗之塔5",
    "Dark Tower 6": "黑暗之塔6",
    "Darkness in the Tower": "塔中的黑暗",
    "Darkness": "黑暗",
    "Daytime Dolphin Island": "白天海豚岛",
    "Dead End Forest": "死胡同森林",
    "Dead Tree Forest": "枯树森林",
    "Decaying Snowfield Forest": "衰败雪原森林",
    "Deep Dark Sea Grave": "深邃黑暗海底坟墓",
    "Deep Inside the Mossy Tree Forest": "青苔树林深处",
    "Demon Slayer's Childhood Home": "恶魔猎手童年之家",
    "Demonslayer Logo": "恶魔猎手标志",
    "Den of Wolven Stink": "狼臭兽穴",
    "Depressing Audience Room": "令人沮丧的觐见室",
    "Desert Road": "沙漠之路",
    "Desolate Desert 1": "荒凉沙漠1",
    "Desolate Desert 2": "荒凉沙漠2",
    "Destiny's Call": "命运召唤",
    "Destroyed Temple of Time Entrance": "被破坏的时间神殿入口",
    "Deteriorated Forest": "衰退森林",
    "Dimensional World": "次元世界",
    "Dining Chambers": "餐室",
    "Doll's House": "人偶之家",
    "Door to the Sharenian Castle": "通往沙雷尼安城堡的门",
    "Dragon Forest": "龙之森林",
    "Dragon Nest Maze": "龙巢迷宫",
    "Dragon Nest": "龙巢",
    "Dragon VS Dragon": "龙对龙",
    "Dran's Lab": "德兰的实验室",
    "Dream Forest ": "梦幻森林 ",
    "Dream Forest Entrance": "梦幻森林入口",
    "Dream Forest Trail ": "梦幻森林小径 ",
    "Dream World": "梦幻世界",
    "Dual Wield Dojo": "双持道场",
    "Dusty Platform": "积尘月台",
    "East Pantheon": "万神殿东门",
    "Eastern Besieged Henesys": "被围攻的射手村东部",
    "Edea Shout": "艾迪亚呐喊",
    "Edelstein Outskirts 1": "埃德尔斯坦郊外1",
    "Edelstein Outskirts 2": "埃德尔斯坦郊外2",
    "Edelstein Outskirts": "埃德尔斯坦郊外",
    "Edelstein": "埃德尔斯坦",
    "Eleanor's Room": "埃莉诺的房间",
    "Eliminate Pirates!": "消灭海盗！",
    "Eliza's Garden": "伊丽莎的花园",
    "Eliza's Shrine": "伊丽莎的神龛",
    "Ellin's Forest": "艾琳的森林",
    "Ellinia": "魔法密林",
    "Elluel": "埃鲁尔",
    "Empress Road": "女皇之路",
    "Empty Bowman Instructional School": "空无一人的弓箭手教练学校",
    "Empty Classroom": "空教室",
    "Empty House": "空房子",
    "Empty Platform": "空月台",
    "End of the Maze": "迷宫终点",
    "Entrance - Snow Man's Land": "入口 - 雪人领地",
    "Entrance to Center Lab": "中央实验室入口",
    "Entrance to Gelimer's Lab": "格里梅尔实验室入口",
    "Entrance to MV's Lair": "MV巢穴入口",
    "Entrance to Snakerot Jungle": "蛇腐丛林入口",
    "Entrance to the Drill Hall": "训练场入口",
    "Entrance to the Remains": "遗迹入口",
    "Entry Testing Grounds": "入团试验场",
    "Ereve Garden": "埃雷夫花园",
    "Ereve Grand Pavilion": "埃雷夫大阁",
    "Ereve Strolling Path": "埃雷夫散步道",
    "Ereve Studio  ": "埃雷夫摄影棚  ",
    "Ereve": "埃雷夫",
    "Ergoth's Throne": "厄尔戈斯的王座",
    "Evolution Lab": "进化实验室",
    "Evolution System": "进化系统",
    "Evolution Underground": "进化地下",
    "Excavation Site": "发掘现场",
    "Exclusive Training Center": "专属训练中心",
    "Exit - Cheese Storage": "出口 - 奶酪仓库",
    "Exit - Snow Man's Land": "出口 - 雪人领地",
    "Exit": "出口",
    "Exiting the Practice Field": "离开练习场",
    "Expert Secret Herb Patch": "专家秘密药草田",
    "Expert Secret Mine": "专家秘密矿山",
    "Extraction Room 1": "提炼室1",
    "Extraction Room 2": "提炼室2",
    "Fairy Forest Center": "精灵森林中心",
    "Fairy Forest": "精灵森林",
    "Fairytale Land  ": "童话村  ",
    "Fairytale Land ": "童话村 ",
    "Fairytale Land Entrance  ": "童话村入口  ",
    "Fairytale Land Exit  ": "童话村出口  ",
    "Fairytale Land": "童话村",
    "Fallen Mast": "倒下的桅杆",
    "Falling Rock Zone": "落石区域",
    "Falling Zone": "坠落区域",
    "Family Studio Waiting Room  ": "家庭摄影棚等候室  ",
    "Fanzy's Testing Grounds 1": "范齐的试验场1",
    "Fanzy's Testing Grounds 2": "范齐的试验场2",
    "Fanzy's Testing Grounds 3": "范齐的试验场3",
    "Fanzy's Testing Grounds 4": "范齐的试验场4",
    "Fenced Street  ": "围栏街道  ",
    "Festive Yard": "节日庭院",
    "Field of Refreshing Watermelons": "清爽西瓜田",
    "Field of Sweet Watermelons": "甜蜜西瓜田",
    "Field of Tasty Watermelons": "美味西瓜田",
    "Fiery Temple of Time": "火热的时间神殿",
    "Final Battle": "最终决战",
    "Final Gateway Pirate Ship": "最终关卡海盗船",
    "Find the Black Crow!": "找到黑鸦！",
    "First Time Together &lt;1st Stage&gt;": "初次相聚 &lt;第1阶段&gt;",
    "First Time Together &lt;2nd Stage&gt;": "初次相聚 &lt;第2阶段&gt;",
    "First Time Together &lt;3rd Stage&gt;": "初次相聚 &lt;第3阶段&gt;",
    "First Time Together &lt;4th Stage&gt;": "初次相聚 &lt;第4阶段&gt;",
    "First Time Together &lt;Bonus&gt;": "初次相聚 &lt;奖励&gt;",
    "First Time Together &lt;Exit Map&gt;": "初次相聚 &lt;出口地图&gt;",
    "First Time Together &lt;Exit&gt;": "初次相聚 &lt;出口&gt;",
    "First Time Together &lt;Last Stage&gt;": "初次相聚 &lt;最终阶段&gt;",
    "Fog-Covered Path": "雾气弥漫的道路",
    "Forbidden Time": "禁忌时间",
    "Forecastle": "前甲板",
    "Forest Edge": "森林边缘",
    "Forest Entrance": "森林入口",
    "Forest of Bedazzlement": "迷幻森林",
    "Forest of Endurance": "忍耐之森",
    "Forest of Haze": "薄雾森林",
    "Forest of Poison Haze": "毒雾森林",
    "Forest of Poison": "毒之森林",
    "Forest of Tenacity": "坚韧之森",
    "Forest of Whispering Trees": "低语之森",
    "Forest of the Dead": "死亡之森",
    "Forest of the Ghost Priest": "鬼 priest 之森",
    "Forest's Empty Lot": "森林空地",
    "Forgotten Laboratory": "被遗忘的实验室",
    "Forgotten Shrine": "被遗忘的神社",
    "Forked Road: Dangerous Sea &lt;Exit Map&gt;": "岔路：危险海域 &lt;出口地图&gt;",
    "Former Dark Lord's Room": "前任黑暗领主的房间",
    "Forming of the Alliance": "联盟的组建",
    "Fountain of the Wiseman": "智者之泉",
    "Fragrant Yard of Moon Flowers": "月光花飘香的庭院",
    "Frame Room": "框架房间",
    "Francis's Room": "弗朗西斯的房间",
    "Free Market Entrance": "自由市场入口",
    "Free Market": "自由市场",
    "Free Market&lt;1&gt;": "自由市场&lt;1&gt;",
    "Free Market&lt;10&gt;": "自由市场&lt;10&gt;",
    "Free Market&lt;11&gt;": "自由市场&lt;11&gt;",
    "Free Market&lt;12&gt;": "自由市场&lt;12&gt;",
    "Free Market&lt;13&gt;": "自由市场&lt;13&gt;",
    "Free Market&lt;14&gt;": "自由市场&lt;14&gt;",
    "Free Market&lt;15&gt;": "自由市场&lt;15&gt;",
    "Free Market&lt;16&gt;": "自由市场&lt;16&gt;",
    "Free Market&lt;17&gt;": "自由市场&lt;17&gt;",
    "Free Market&lt;18&gt;": "自由市场&lt;18&gt;",
    "Free Market&lt;19&gt;": "自由市场&lt;19&gt;",
    "Free Market&lt;2&gt;": "自由市场&lt;2&gt;",
    "Free Market&lt;20&gt;": "自由市场&lt;20&gt;",
    "Free Market&lt;21&gt;": "自由市场&lt;21&gt;",
    "Free Market&lt;22&gt;": "自由市场&lt;22&gt;",
    "Free Market&lt;3&gt;": "自由市场&lt;3&gt;",
    "Free Market&lt;4&gt;": "自由市场&lt;4&gt;",
    "Free Market&lt;5&gt;": "自由市场&lt;5&gt;",
    "Free Market&lt;6&gt;": "自由市场&lt;6&gt;",
    "Free Market&lt;7&gt;": "自由市场&lt;7&gt;",
    "Free Market&lt;8&gt;": "自由市场&lt;8&gt;",
    "Free Market&lt;9&gt;": "自由市场&lt;9&gt;",
    "Free-for-all": "自由对战",
    "Freezer's Nest": "冰冻兽的巢穴",
    "Fresh Start": "新的开始",
    "Frog House ": "青蛙之家 ",
    "Front Yard Wreckage": "前院废墟",
    "Frosty Glacial Gorge": "霜冻冰川峡谷",
    "Frozen Battleground": "冰封战场",
    "Frozen Fairy Forest": "冰封精灵森林",
    "Frozen Temple of Time": "冰封的时间神殿",
    "Funkmageddon Alley Exit": "放克末日小巷出口",
    "Funkmageddon Alley": "放克末日小巷",
    "Future Henesys": "未来射手村",
    "Gaga's Rescue Success?!  ": "嘎嘎的救援成功？！  ",
    "Gallery Entrance": "画廊入口",
    "Game of Yut Exit": "尤茨游戏出口",
    "Game of Yut Session": "尤茨游戏进行中",
    "Game of Yut Waiting Room": "尤茨游戏等候室",
    "Gawyllacs's Chamber": "加维拉克斯的房间",
    "Gelimer's Trap": "格里梅尔的陷阱",
    "General Store Attic": "杂货店阁楼",
    "General Store Yard": "杂货店庭院",
    "Ghost Ship Navigation Room": "幽灵船驾驶室",
    "Gloomy Forest": "阴暗森林",
    "Glowing Maze of Mushroom": "发光蘑菇迷宫",
    "Glowing Mushroom's Room": "发光蘑菇的房间",
    "Gold Richie's Maze": "金里奇的迷宫",
    "Gold Richie's Old Storage Room": "金里奇的旧仓库",
    "Gold Richie's Storage Room": "金里奇的仓库",
    "Gold Richie's Treasure Vault": "金里奇的宝库",
    "Gold Richie's Vault Exit": "金里奇的宝库出口",
    "Golem Temple": "石头人神殿",
    "Golem's Temple Entrance ": "石头人神殿入口 ",
    "Grand Battle": "大乱斗",
    "Gray's Hideout": "格雷的据点",
    "Great Temple Interior": "大神殿内部",
    "Guarded Mansion": "守卫宅邸",
    "Guest Room 3": "客房3",
    "Guest Room": "客房",
    "Guild Union Camp": "公会联盟营地",
    "Gusty Peak - Chrome's Tent": "狂风山峰 - 克罗姆的帐篷",
    "Gym": "健身房",
    "Hall of the Knight": "骑士大厅",
    "Hallowed Ground": "圣地",
    "Happy Days": "快乐时光",
    "Harmony": "和谐",
    "Harp's Hideout": "哈普的据点",
    "Hatchery": "孵化场",
    "Haunted Mansion": "鬼屋",
    "Head Blacksmith's Shop": "首席铁匠铺",
    "Heart of Lava": "熔岩之心",
    "Helena's Bowman Instructional School": "海伦娜的弓箭手教练学校",
    "Helios Tower Library": "太阳塔图书馆",
    "Heliseum Outskirts": "赫利西乌姆郊外",
    "Heliseum Sky": "赫利西乌姆天空",
    "Henesys Mystic Field": "射手村神秘领域",
    "Henesys": "射手村",
    "Herb Town Pier": "百草堂码头",
    "Hero's Gauntlet Active": "英雄挑战赛进行中",
    "Hero's Gauntlet Exit": "英雄挑战赛出口",
    "Hero's Gauntlet Waiting Area": "英雄挑战赛等候区",
    "Hero's Memory  ": "英雄的记忆  ",
    "Hidden Balcony": "隐藏阳台",
    "Hidden Chamber": "密室",
    "Hidden Field": "隐藏领域",
    "Hidden Forbidden Lab": "隐藏的禁闭实验室",
    "Hidden Laboratory": "隐藏实验室",
    "Hidden Path": "隐藏小径",
    "Hidden Relic": "隐藏遗迹",
    "Hidden Street  ": "隐藏街道  ",
    "Hidden Street ": "隐藏街道 ",
    "Hidden Street": "隐藏街道",
    "Hidden Tower Entrance &lt;Exit Map&gt;": "隐藏之塔入口 &lt;出口地图&gt;",
    "Hidden Tower": "隐藏之塔",
    "Hidden Training Center": "隐藏训练中心",
    "Hidden Treasure Vault": "隐藏宝库",
    "High! Low!": "高！低！",
    "Hilla's Altar within a Dream": "梦境中的希拉祭坛",
    "Hoblin's Hideout": "霍布林的据点",
    "Hole of the Moon": "月之洞",
    "Home Room": "教室",
    "Homestead Yard": "家园庭院",
    "Horntail's Cave within a Dream": "梦境中的暗黑龙王洞穴",
    "Hot Desert": "炎热沙漠",
    "Housekeeping Room": "杂物间",
    "Hsalf's Chamber": "哈萨尔夫的房间",
    "Hunting Ad Balloon": "狩猎广告气球",
    "Hunting House": "猎人之家",
    "Hut in the Swamp": "沼泽中的小屋",
    "Ice Cliff": "冰崖",
    "Ice Curse Forest": "冰咒森林",
    "Ice Gorge": "冰峡",
    "Ice Knight": "冰骑士",
    "Ice Ravine 1 ": "冰裂谷1 ",
    "Ice Ravine 1": "冰裂谷1",
    "Ice Ravine 2 ": "冰裂谷2 ",
    "Ice Ravine 2": "冰裂谷2",
    "Ice Ravine 3": "冰裂谷3",
    "Ice Ravine 4": "冰裂谷4",
    "Ice Ravine 5": "冰裂谷5",
    "Ice Ravine Backstreet": "冰裂谷后街",
    "Ice Ravine Entrance": "冰裂谷入口",
    "Ice Ravine": "冰裂谷",
    "Igloo Moor": "冰屋荒原",
    "Illustration": "插图",
    "Initiation": "入会仪式",
    "Inner Cursed Ellinia Forest": "被诅咒的魔法密林深处",
    "Innerscape": "内在空间",
    "Inside Snakerot Jungle": "蛇腐丛林内部",
    "Inside the Lab": "实验室内部",
    "Intermediate Secret Herb Patch": "中级秘密药草田",
    "Intermediate Secret Mine": "中级秘密矿山",
    "Intruder Search Warrant 1": "入侵者搜查令1",
    "Intruder Search Warrant 2": "入侵者搜查令2",
    "Intruder Search Warrant 3": "入侵者搜查令3",
    "Jaguar Habitat": "美洲豹栖息地",
    "Jeppi's Hideout": "杰皮的据点",
    "Jewel Pop": "宝石消消乐",
    "Jin's Room": "杰恩的房间",
    "Job Advancement": "转职",
    "Jr. Yeti Habitat": "小雪人栖息地",
    "Jumping Board Leading to Jump Stand": "通往跳跃台的跳板",
    "Kaiser's Awakening": "凯撒的觉醒",
    "Kenta's Breeding Room": "肯塔的培育室",
    "Kerning City": "废弃都市",
    "Kerning Square": "废弃都市广场",
    "King's Chamber": "国王的寝宫",
    "King's Corridor": "国王的走廊",
    "King's Hideout": "国王的藏身处",
    "King's Room": "国王的房间",
    "Kitchen Exit": "厨房出口",
    "Knight Stronghold": "骑士据点",
    "Knights' Chamber": "骑士的房间",
    "Korean Folk Town": "东方神州",
    "Krunkpocalypse Alley Exit": "克伦克末日小巷出口",
    "Krunkpocalypse Alley": "克伦克末日小巷",
    "Kyrin's Training Room": "Kyrin的训练室",
    "Lab - Area A-4": "实验室 - A-4区",
    "Lab - Unit 101": "实验室 - 101单元",
    "Lab - Unit 102": "实验室 - 102单元",
    "Lab - Unit 103": "实验室 - 103单元",
    "Lab - Unit 104": "实验室 - 104单元",
    "Lab Entrance": "实验室入口",
    "Lab Exit 1": "实验室出口1",
    "Lab Exit 2": "实验室出口2",
    "Lab Exit 3": "实验室出口3",
    "Lab Exit": "实验室出口",
    "Lab Tunnel": "实验室隧道",
    "Laboratory Tunnel": "实验室通道",
    "Laboratory": "实验室",
    "Lania's Front Yard": "拉妮亚的前院",
    "Lania's Home": "拉妮亚的家",
    "Last Chance": "最后机会",
    "Last Platform": "最后月台",
    "Last Resting Spot": "最后的歇脚处",
    "Last Trap": "最后的陷阱",
    "Leafre Forest's Edge": "神木村森林边缘",
    "Leafre Mystic Field": "神木村神秘领域",
    "Leafre Treasure Vault Entrance": "神木村宝库入口",
    "Leafre Treasure Vault": "神木村宝库",
    "Leave Game of Yut": "离开尤茨游戏",
    "Library Vault": "图书馆地下室",
    "Library": "图书馆",
    "Limbert's General Store": "林伯特的杂货店",
    "Line 2 Area 3": "2号线3区",
    "Link 1": "连接路1",
    "Link 2": "连接路2",
    "Link 3": "连接路3",
    "Link 4": "连接路4",
    "Link 5": "连接路5",
    "Link 6": "连接路6",
    "Link 7": "连接路7",
    "Link 8": "连接路8",
    "Link 9": "连接路9",
    "Lion King's Castle": "狮子王之城",
    "Lion King's Tower": "狮子王之塔",
    "Little Forest Edge": "小森林边缘",
    "Little Lamb's Courage  ": "小羊的勇气  ",
    "Little Lamb's Defeat  ": "小羊的失败  ",
    "Little Lamb's Victory  ": "小羊的胜利  ",
    "Living Bellflower Root Patch": "活桔梗根田",
    "Lobby": "大厅",
    "Logo": "标志",
    "Looking for Delli 1": "寻找德利1",
    "Looking for Delli 2": "寻找德利2",
    "Looking for Delli 3": "寻找德利3",
    "Lost Forest ": "迷路森林 ",
    "Lost Forest Entrance ": "迷路森林入口 ",
    "Lost Forest Trail ": "迷路森林小径 ",
    "Ludibrium Studio ": "玩具城摄影棚 ",
    "Ludibrium Studio": "玩具城摄影棚",
    "Ludibrium": "玩具城",
    "Lunar World": "月之世界",
    "Lush Forest": "茂密森林",
    "Magatia Desert": "魔法密林沙漠",
    "Magatia Studio  ": "玛加提亚摄影棚  ",
    "Magatia Studio": "玛加提亚摄影棚",
    "Magatia Waterway": "玛加提亚水路",
    "Magic Library": "魔法图书馆",
    "Magical Halloween Garden": "魔法万圣节花园",
    "Magician Test Site": "魔法师考场",
    "Magician Training Center": "魔法师训练中心",
    "Magician's Forest": "魔法师之森",
    "Magnus's Ambush": "麦格纳斯的伏击",
    "Magpie Nest": "喜鹊巢",
    "Manon's Dark Forest": "曼龙的黑暗森林",
    "Maple 7th Day Market": "枫叶七日集市",
    "Maple Bingo Exit": "枫叶宾果游戏出口",
    "Maple Bingo Waiting Area": "枫叶宾果游戏等候区",
    "Maple Bingo in Play": "枫叶宾果游戏进行中",
    "Maple Bingo": "枫叶宾果游戏",
    "Maple Castle Party Waiting Area": "枫叶城堡派对等候区",
    "Maple Castle Party Zone": "枫叶城堡派对区",
    "Maple Castle Waiting Area": "枫叶城堡等候区",
    "Maple Castle": "枫叶城堡",
    "Maple Hill": "枫叶山丘",
    "Maple Immigration Information Desk": "枫叶移民咨询台",
    "Maple School": "枫叶学校",
    "Maple Sports Field - After the game ": "枫叶运动场 - 赛后 ",
    "Maple Sports Field - Before the game": "枫叶运动场 - 赛前",
    "Maple Sports Field - During the game": "枫叶运动场 - 比赛中",
    "Maple Studio  ": "枫叶摄影棚  ",
    "Maple Tree Forest Exit": "枫树林出口",
    "Maple Tree Forest": "枫树林",
    "Maple World": "冒险岛世界",
    "Marble Room": "大理石房间",
    "Margana's Chamber": "玛加纳的房间",
    "Mask Room": "面具房间",
    "Maze Exit": "迷宫出口",
    "Maze of Erosion": "侵蚀迷宫",
    "Maze of Exploration": "探索迷宫",
    "Maze of Golden Fruit": "金色果实迷宫",
    "Maze of Mushroom": "蘑菇迷宫",
    "Maze of Numbers": "数字迷宫",
    "Maze of the Golden Key": "金钥匙迷宫",
    "Memories of the Past": "过去的记忆",
    "Mesodizer X Robot Control Room": "美索达泽X机器人控制室",
    "Mesoranger Operations HQ": "游侠作战总部",
    "Middle Path": "中间道路",
    "Middle of the Dangerous Sea": "危险海域中央",
    "Mine Depths": "矿山深处",
    "Mine Entrance": "矿山入口",
    "Mini Bean Hunting Ground": "迷你豆猎场",
    "Mini Herb Town": "迷你百草堂",
    "Monkey Direction": "猴子方向",
    "Monster Arena Battleground": "怪物竞技场战场",
    "Monster Carnival": "怪物嘉年华",
    "Monster Park Extreme": "极限怪物公园",
    "Monster Park": "怪物公园",
    "Monster's Maze": "怪物迷宫",
    "Moon Bunny &lt;Exit Map&gt;": "月兔 &lt;出口地图&gt;",
    "Moon Bunny Playground": "月兔游乐场",
    "Moon Corner  ": "月之角落  ",
    "Moonlight Thief Clash": "月夜盗贼对决",
    "Moonlight Thief Getaway": "月夜盗贼逃跑",
    "Moonlight Village": "月夜村",
    "Moonlight Yard": "月光庭院",
    "Moose's Practice Field": "穆斯练习场",
    "Mossy Tree Forest": "青苔树林",
    "Mouth of the Forest": "森林之口",
    "Mu Lung Clouds": "武陵云端",
    "Mu Lung Dojo 10th Floor": "武陵道场10层",
    "Mu Lung Dojo 11th Floor": "武陵道场11层",
    "Mu Lung Dojo 12th Floor": "武陵道场12层",
    "Mu Lung Dojo 13th Floor": "武陵道场13层",
    "Mu Lung Dojo 14th Floor": "武陵道场14层",
    "Mu Lung Dojo 15th Floor": "武陵道场15层",
    "Mu Lung Dojo 16th Floor": "武陵道场16层",
    "Mu Lung Dojo 17th Floor": "武陵道场17层",
    "Mu Lung Dojo 18th Floor": "武陵道场18层",
    "Mu Lung Dojo 19th Floor": "武陵道场19层",
    "Mu Lung Dojo 1st Floor": "武陵道场1层",
    "Mu Lung Dojo 20th Floor": "武陵道场20层",
    "Mu Lung Dojo 21st Floor": "武陵道场21层",
    "Mu Lung Dojo 22nd Floor": "武陵道场22层",
    "Mu Lung Dojo 23rd Floor": "武陵道场23层",
    "Mu Lung Dojo 24th Floor": "武陵道场24层",
    "Mu Lung Dojo 25th Floor": "武陵道场25层",
    "Mu Lung Dojo 26th Floor": "武陵道场26层",
    "Mu Lung Dojo 27th Floor": "武陵道场27层",
    "Mu Lung Dojo 28th Floor": "武陵道场28层",
    "Mu Lung Dojo 29th Floor": "武陵道场29层",
    "Mu Lung Dojo 2nd Floor": "武陵道场2层",
    "Mu Lung Dojo 30th Floor": "武陵道场30层",
    "Mu Lung Dojo 31st Floor": "武陵道场31层",
    "Mu Lung Dojo 32nd Floor": "武陵道场32层",
    "Mu Lung Dojo 33rd Floor": "武陵道场33层",
    "Mu Lung Dojo 34th Floor": "武陵道场34层",
    "Mu Lung Dojo 35th Floor": "武陵道场35层",
    "Mu Lung Dojo 36th Floor": "武陵道场36层",
    "Mu Lung Dojo 37th Floor": "武陵道场37层",
    "Mu Lung Dojo 38th Floor": "武陵道场38层",
    "Mu Lung Dojo 39th Floor": "武陵道场39层",
    "Mu Lung Dojo 3rd Floor": "武陵道场3层",
    "Mu Lung Dojo 40th Floor": "武陵道场40层",
    "Mu Lung Dojo 41st Floor": "武陵道场41层",
    "Mu Lung Dojo 42nd Floor": "武陵道场42层",
    "Mu Lung Dojo 43rd Floor": "武陵道场43层",
    "Mu Lung Dojo 44th Floor": "武陵道场44层",
    "Mu Lung Dojo 45th Floor": "武陵道场45层",
    "Mu Lung Dojo 46th Floor": "武陵道场46层",
    "Mu Lung Dojo 47th Floor": "武陵道场47层",
    "Mu Lung Dojo 4th Floor": "武陵道场4层",
    "Mu Lung Dojo 5th Floor": "武陵道场5层",
    "Mu Lung Dojo 6th Floor": "武陵道场6层",
    "Mu Lung Dojo 7th Floor": "武陵道场7层",
    "Mu Lung Dojo 8th Floor": "武陵道场8层",
    "Mu Lung Dojo 9th Floor": "武陵道场9层",
    "Mu Lung Dojo Entrance": "武陵道场入口",
    "Mu Lung Dojo Exit": "武陵道场出口",
    "Mu Lung Dojo Hall": "武陵道场大厅",
    "Mu Lung Dojo Rooftop": "武陵道场天台",
    "Mu Lung Dojo": "武陵道场",
    "Mu Lung Studio  ": "武陵摄影棚  ",
    "Mu Lung Studio": "武陵摄影棚",
    "Mu Young's Storage": "慕阳的仓库",
    "Muirhat's Room": "缪哈特的房间",
    "Mushroom Castle Wall": "蘑菇城堡墙壁",
    "Music Room": "音乐室",
    "Mysterious Lab": "神秘实验室",
    "Mysterious Mine": "神秘矿山",
    "Nautilus Coast": "诺特勒斯海岸",
    "Near Edelstein": "埃德尔斯坦附近",
    "Near the Ice Ravine Graves": "冰裂谷墓地附近",
    "Nearby Edelstein Park Fountain 1": "埃德尔斯坦公园喷泉附近1",
    "Nearby Edelstein Park Fountain 2": "埃德尔斯坦公园喷泉附近2",
    "Nearby Edelstein Park Fountain 3": "埃德尔斯坦公园喷泉附近3",
    "Nearby Edelstein Park Fountain 4": "埃德尔斯坦公园喷泉附近4",
    "Nearby Edelstein Park Fountain 5": "埃德尔斯坦公园喷泉附近5",
    "Neglected Park": "荒废公园",
    "Neglected Rocky Mountain": "荒废岩石山",
    "Neinheart's Job Introduction  ": "内哈尔特的职业介绍  ",
    "Neinheart's Testing Grounds": "内哈尔特的试验场",
    "Nest of a Baby Bird": "雏鸟之巢",
    "Nett's Pyramid": "耐特的金字塔",
    "New Twilight Perion": "新暮色勇士部落",
    "New Weapon Development Research Center": "新武器开发研究中心",
    "Next Classroom": "下一间教室",
    "Nightime Dolphin Island": "夜晚海豚岛",
    "Novice Secret Herb Patch": "初级秘密药草田",
    "Novice Secret Mine": "初级秘密矿山",
    "Occupied Elven Forest": "被占领的精灵森林",
    "Ocean Cave End": "海洋洞穴尽头",
    "Ocean Cave Escape! ": "海洋洞穴逃脱！ ",
    "Ocean Cave Escape!!  ": "海洋洞穴逃脱！！  ",
    "Ocean Cave Escape!!!  ": "海洋洞穴逃脱！！！  ",
    "Office": "办公室",
    "Omega Sector": "地球防御本部",
    "Ominous Cave": "不祥洞穴",
    "On Voyage": "航行中",
    "On the Way to the Pirate Ship": "前往海盗船途中",
    "On the Way to the Practice Field": "前往练习场途中",
    "Opening": "开场",
    "Orbis Studio  ": "天空之城摄影棚  ",
    "Orbis Studio": "天空之城摄影棚",
    "Orbis Treasure Vault Entrance": "天空之城宝库入口",
    "Orbis Treasure Vault": "天空之城宝库",
    "Orchid's Room": "兰的房间",
    "Origin of the Clock Tower": "时钟塔的起源",
    "Otherworld Battleground": "异界战场",
    "Outer Forest Exit": "外部森林出口",
    "Outside Blacksmith's Shop": "铁匠铺外面",
    "Outside": "外面",
    "Pantheon Clinic": "万神殿诊所",
    "Pantheon Mystic Field": "万神殿神秘领域",
    "Pantheon Outskirts": "万神殿郊外",
    "Pantheon": "万神殿",
    "Park Corner": "公园角落",
    "Party Quest Entrance": "组队任务入口",
    "Party Quest Entry &lt;Advanced&gt;": "组队任务入场 &lt;高级&gt;",
    "Party Quest Entry &lt;Intermediate&gt;": "组队任务入场 &lt;中级&gt;",
    "Path of the Glowcaves": "荧光洞穴之路",
    "Path to Snow Man's Land": "通往雪人领地的路",
    "Path to the Aerial Prison": "通往空中监狱之路",
    "Path to the Breeding Room": "通往培育室之路",
    "Peacetime Edelstein": "和平时期的埃德尔斯坦",
    "Peach Monkey Forest": "桃猴森林",
    "Pharmacy": "药房",
    "Phoenix's Nest": "凤凰巢",
    "Picture World": "图画世界",
    "Pig Town": "猪猪小镇",
    "Pigmy that lays Golden Eggs": "下金蛋的矮猪",
    "Pink Bean's Party": "粉色豆豆的派对",
    "Pink Bean's Temple within a Dream": "梦境中的粉色豆豆神殿",
    "Piranha Habitat": "食人鱼栖息地",
    "Pirate Hideout": "海盗据点",
    "Pirate Ship On its Way Out": "驶出的海盗船",
    "Pirate Test Site": "海盗考场",
    "Pirate Training Center": "海盗训练中心",
    "Pirate Treasure Vault ": "海盗宝库 ",
    "Pirates' Deck": "海盗甲板",
    "Pixiemom Park": "精灵妈妈公园",
    "Platform - Train 999": "月台 - 999号列车",
    "Play Magnus Video": "播放麦格纳斯视频",
    "Playground of Lupin Leading to Jump Stand": "通往跳跃台的猴子游乐场",
    "Playground of Moon Bunnies": "月兔游乐场",
    "Poisoned Forest": "毒之森林",
    "Port Road": "港口之路",
    "Power B. Fore's Borrowed Training Center ": "波尔·B·福尔的借用训练中心 ",
    "Power B. Fore's Spore Training Center": "波尔·B·福尔的孢子训练中心",
    "Power Plant Lobby": "发电厂大厅",
    "Power Plant Security": "发电厂安保区",
    "Power Plant": "发电厂",
    "Power of Magnus": "麦格纳斯的力量",
    "Pre-Entrance": "预入口",
    "Premium Carnival Field 1 &lt;Lobby&gt; ": "高级嘉年华场地1 &lt;大厅&gt; ",
    "Premium Carnival Field 2 &lt;Lobby&gt;": "高级嘉年华场地2 &lt;大厅&gt;",
    "Premium Carnival Field 3 &lt;Lobby&gt;": "高级嘉年华场地3 &lt;大厅&gt;",
    "Premium Road": "高级道路",
    "Present Ereve": "现在的埃雷夫",
    "Present Henesys": "现在的射手村",
    "Primrose Hill": "报春花山丘",
    "Principal's Office": "校长室",
    "Prison Guard's Room": "狱卒的房间",
    "Prison": "监狱",
    "Prizes": "奖品",
    "Protect Tylus": "保护泰勒斯",
    "Protecting Tylus : Complete": "保护泰勒斯：完成",
    "Pulpwood Field Active": "纸浆田进行中",
    "Pulpwood Field Waiting Area": "纸浆田等候区",
    "Pumpkin Patch": "南瓜地",
    "Puppeteer's Cave": "傀儡师的洞穴",
    "Puppeteer's Hidden Cave": "傀儡师的隐藏洞穴",
    "Puppeteer's Room": "傀儡师的房间",
    "Puppeteer's Secret Passage": "傀儡师的秘密通道",
    "Pygmy Grass Field": "矮草田",
    "Pyramid Dunes": "金字塔沙丘",
    "Queensheart Forest": "女王之心森林",
    "Quiet Ereve": "宁静的埃雷夫",
    "Quiet Walk": "安静散步",
    "Radiant Crystal Passageway": "光辉水晶通道",
    "Rainbow Snail's Maze": "彩虹蜗牛的迷宫",
    "Ranch Backstreet ": "牧场后街 ",
    "Ranch Entrance  ": "牧场入口  ",
    "Ranch Entrance": "牧场入口",
    "Ravana's Golden Altar": "拉瓦纳的金色祭坛",
    "Razor Sharp Cliff": "锋利悬崖",
    "Ready to Leave": "准备出发",
    "Rear Palace Corridor": "后宫走廊",
    "Recent Elluel": "近期的埃鲁尔",
    "Recent Perion": "近期的勇士部落",
    "Recruit Training Grounds 1": "新兵训练场1",
    "Recruit Training Grounds 2": "新兵训练场2",
    "Recruit Training Grounds 3": "新兵训练场3",
    "Red Desert": "红色沙漠",
    "Red Nirg's Chamber": "红色尼尔格的房间",
    "Rellik's Chamber": "雷里克的房间",
    "Rescue Gaga! ": "拯救嘎嘎！ ",
    "Research Command": "研究指挥部",
    "Resting Spot I": "休息点一",
    "Resting Spot II": "休息点二",
    "Resting Spot III": "休息点三",
    "Resting Spot IV": "休息点四",
    "Resting Spot of Memory 3": "记忆休息点3",
    "Returning Adventurer's Training Center": "回归冒险家训练中心",
    "Returning Path": "回归之路",
    "Ribbon Pig's Maze": "丝带猪的迷宫",
    "Rider's Field": "骑手原野",
    "Rien": "里恩",
    "Rising Star Hall": "新星大厅",
    "Road to the Fortress": "通往要塞之路",
    "Road to the Mine 1": "通往矿山之路1",
    "Rocket Land": "火箭乐园",
    "Rocket Launch": "火箭发射",
    "Rocket Start": "火箭起航",
    "Romeo and Juliet": "罗密欧与朱丽叶",
    "Room of Courage": "勇气之室",
    "Room of Faith": "信念之室",
    "Room of Glory": "荣耀之室",
    "Room of Justice": "正义之室",
    "Room of Pledge": "誓约之室",
    "Room of Thanatos": "萨纳托斯之室",
    "Root Abyss": "根源深渊",
    "Round Up!": "集合！",
    "Royal Chamber": "皇家寝室",
    "Ruined City": "废墟城市",
    "Safe - 1st Entrance": "保险库 - 第1入口",
    "Safe - 2nd Entrance ": "保险库 - 第2入口 ",
    "Saffron's Herb Field": "藏红花的药草田",
    "Save Delli!": "拯救德利！",
    "Scene Change 0": "场景切换0",
    "Scene Change 1": "场景切换1",
    "Scene Change 2": "场景切换2",
    "Scene Change": "场景切换",
    "School Roof": "学校天台",
    "Scorching Sand Desert": "灼热沙沙漠",
    "Sea of Fog": "迷雾之海",
    "Sea of Silence": "寂静之海",
    "Seal Room 1": "封印室1",
    "Seal Room 2": "封印室2",
    "Sealed Garden": "被封印的花园",
    "Sealed Temple": "被封印的神殿",
    "Secluded Corner in the Park": "公园隐秘角落",
    "Secluded Park": "隐秘公园",
    "Secluded Strolling Path": "幽静散步道",
    "Second Chance": "第二次机会",
    "Second Drill Hall": "第二训练场",
    "Secret Corridor": "秘密走廊",
    "Secret Factory": "秘密工厂",
    "Secret Laboratory": "秘密实验室",
    "Secret Library": "秘密图书馆",
    "Secret Meeting Place": "秘密会面地点",
    "Secret Passage": "秘密通道",
    "Secret Pirate Hideout": "秘密海盗据点",
    "Secret Place": "秘密地点",
    "Secret Plaza 1": "秘密广场1",
    "Secret Room": "密室",
    "Secret Shrine": "秘密神社",
    "Secret Square": "秘密广场",
    "Secret Storage Room": "秘密仓库",
    "Shades of the Pyramid": "金字塔的阴影",
    "Shady Hair Salon": "阴暗美发店",
    "Sharen III's Grave": "沙雷三世的坟墓",
    "Sharen III's Treasure Wearhouse": "沙雷三世的宝物仓库",
    "Sharenian Castle Gate": "沙雷尼安城门",
    "Sharenian": "沙雷尼安",
    "Sheep Ranch  ": "牧羊场  ",
    "Sheep Ranch": "牧羊场",
    "Shinsoo's Refuge": "神兽的避难所",
    "Shiny Temple of Time": "闪耀的时间神殿",
    "Shiny Yard of Moon Flowers": "闪耀月光花庭院",
    "Ship Stern": "船尾",
    "Shipwrecked Ghost Ship": "遇难幽灵船",
    "Shortcut": "捷径",
    "Shulynch's First Training Ground": "舒林奇的第一训练场",
    "Shulynch's Second Training Ground": "舒林奇的第二训练场",
    "Silent Crusade Safe House": "沉默远征队安全屋",
    "Silent Jungle ": "寂静丛林 ",
    "Silent Sea": "寂静之海",
    "Silent Yard of Moon Flowers": "寂静月光花庭院",
    "Silo": "导弹井",
    "Six Path Crossway": "六岔路口",
    "Sky Forest Training Center": "天空森林训练中心",
    "Sky Nest": "天空之巢",
    "Sky Road Outskirts": "天空之路郊外",
    "Sky Road": "天空之路",
    "Sky Terrace": "天空露台",
    "Sleepywood Showdown": "射手村对决",
    "Sleepywood": "射手村",
    "Slumbering Dragon Island ": "沉睡龙之岛 ",
    "Small Bridge": "小桥",
    "Small Oasis": "小绿洲",
    "Snail's Maze": "蜗牛的迷宫",
    "Snow Island": "雪岛",
    "Snow Man's Land": "雪人领地",
    "SnowFro's Lair": "雪霜的巢穴",
    "Snowy Forest": "雪林",
    "Snowy Mountain Area": "雪山区域",
    "So Gong's Room": "小公的房间",
    "Soul Talk Point": "灵魂对话点",
    "South Secret Forest": "南方秘密森林",
    "Space Gaga  ": "太空嘎嘎  ",
    "Space Mine  ": "太空矿山  ",
    "Spaceship Crash Site": "飞船坠毁现场",
    "Spaceship Dimensional Crack": "飞船次元裂缝",
    "Spaceship Entrance": "飞船入口",
    "Special Floor of Mu Lung Training Center": "武陵训练中心特别楼层",
    "Special Lab": "特别实验室",
    "Spiegelmann's Gonzo Gallery": "斯皮尔曼的古怪画廊",
    "Spiegelmann's Guest House": "斯皮尔曼的客房",
    "Spiegelmann's Hidey Hole": "斯皮尔曼的藏身处",
    "Spiegelmann's Office": "斯皮尔曼的办公室",
    "Spiegelmann's Workshop": "斯皮尔曼的工作室",
    "Spinel's Forest": "斯皮内尔的森林",
    "Spinel's Room": "斯皮内尔的房间",
    "Spirit Tree Nest": "精灵树之巢",
    "Spirit Valley": "精灵谷",
    "Spirits' Playground": "精灵的游乐场",
    "Staff Room": "职员室",
    "Stage 1 &lt;Mano&gt;": "第1关 &lt;玛诺&gt;",
    "Stage 1": "第1关",
    "Stage 10 &lt;Dyle&gt;": "第10关 &lt;迪尔&gt;",
    "Stage 11 &lt;Zeno&gt;": "第11关 &lt;泽诺&gt;",
    "Stage 12 &lt;Nona-Tailed Fox&gt;": "第12关 &lt;九尾狐&gt;",
    "Stage 13 &lt;Lord Pirate&gt;": "第13关 &lt;海盗王&gt;",
    "Stage 14 &lt;Tae Roon&gt;": "第14关 &lt;泰伦&gt;",
    "Stage 15 &lt;Papa Pixie&gt;": "第15关 &lt;皮皮爸爸&gt;",
    "Stage 16 &lt;Priest Cat&gt;": "第16关 &lt;祭祀猫&gt;",
    "Stage 17 &lt;Jr. Balrog&gt;": "第17关 &lt;小巴洛古&gt;",
    "Stage 18 &lt;Frankenroid&gt;": "第18关 &lt;弗兰肯机器人&gt;",
    "Stage 19 &lt;Eliza&gt;": "第19关 &lt;伊丽莎&gt;",
    "Stage 19 &lt;Elliza&gt;": "第19关 &lt;伊丽莎&gt;",
    "Stage 2 &lt;Stumpy&gt;": "第2关 &lt;树桩&gt;",
    "Stage 2": "第2关",
    "Stage 20 &lt;Chimera&gt;": "第20关 &lt;奇美拉&gt;",
    "Stage 21 &lt;Snowman&gt;": "第21关 &lt;雪人&gt;",
    "Stage 22 &lt;Crimson Balrog&gt;": "第22关 &lt;巴洛古&gt;",
    "Stage 23 &lt;Manon&gt;": "第23关 &lt;曼龙&gt;",
    "Stage 24 &lt;Griffey&gt;": "第24关 &lt;狮鹫&gt;",
    "Stage 25 &lt;Leviathan&gt;": "第25关 &lt;利维坦&gt;",
    "Stage 26 &lt;Papulatus&gt;": "第26关 &lt;皮埃尔&gt;",
    "Stage 27 &lt;Pianus&gt;": "第27关 &lt;比艾努斯&gt;",
    "Stage 3 &lt;Deo&gt;": "第3关 &lt;迪奥&gt;",
    "Stage 3": "第3关",
    "Stage 4 &lt;King Slime&gt;": "第4关 &lt;大王章鱼&gt;",
    "Stage 4": "第4关",
    "Stage 5 &lt;Faust&gt;": "第5关 &lt;浮士德&gt;",
    "Stage 5": "第5关",
    "Stage 6 &lt;King Clang&gt;": "第6关 &lt;大王响螺&gt;",
    "Stage 6": "第6关",
    "Stage 7 &lt;Alishar&gt;": "第7关 &lt;阿丽莎&gt;",
    "Stage 7": "第7关",
    "Stage 8 &lt;Timer&gt;": "第8关 &lt;泰玛&gt;",
    "Stage 9 &lt;Mushmom&gt;": "第9关 &lt;蘑菇妈妈&gt;",
    "Station to Ereve": "前往埃雷夫的站台",
    "Stone Colossus": "石头巨像",
    "Strange Area": "奇异区域",
    "Strange Knights' Chamber": "奇怪的骑士房间",
    "Strange Path": "奇异小径",
    "Strange Swamp": "奇异沼泽",
    "Strategy Room 1": "作战室1",
    "Strategy Room 2": "作战室2",
    "Strategy Room 3": "作战室3",
    "Strategy Room 4": "作战室4",
    "Strategy Room 5": "作战室5",
    "Streetlight Row Corner Alley": "路灯排角巷",
    "Studio Entrance": "摄影棚入口",
    "Studio Made of Cookies  ": "饼干做的摄影棚  ",
    "Subway Supply Depot": "地铁站补给所",
    "Sundry Laboratory": "杂项实验室",
    "Supply Warehouse": "补给仓库",
    "Surl's Water Cellar": "苏尔的水窖",
    "Survivalism Challenge Lobby": "生存挑战大厅",
    "Suspicious Airship": "可疑飞艇",
    "Suspicious Cave Alley": "可疑洞穴小巷",
    "Suspicious Laboratory": "可疑实验室",
    "Tae Sang's Back Yard": "泰桑的后院",
    "Tangyoon's Cauldron": "唐云的大锅",
    "Tangyoon's Kitchen": "唐云的厨房",
    "Team Match": "团队赛",
    "Teaser": "预告",
    "Temple of Darkness Corridor": "黑暗神殿走廊",
    "Temple of Darkness": "黑暗神殿",
    "Temple of Oblivion": "忘却之神殿",
    "Temple of Time Corridor 1": "时间神殿走廊1",
    "Temple of Time Corridor 2": "时间神殿走廊2",
    "Temple of Time Corridor": "时间神殿走廊",
    "Temple of the Past 1": "过去之神殿1",
    "Temple of the Past 2": "过去之神殿2",
    "Temporary Airport": "临时机场",
    "Temporary Harbor ": "临时港口 ",
    "Test Room": "测试房间",
    "The 1st Drill Hall": "第一训练场",
    "The 2nd Monster Carnival": "第2届怪物嘉年华",
    "The 3rd Drill Hall": "第三训练场",
    "The 4th Drill Hall": "第四训练场",
    "The Area of Wild Hog": "野猪领地",
    "The Captain's Dignity": "船长的尊严",
    "The Cursed Forest": "被诅咒的森林",
    "The Dark Gallery": "黑暗画廊",
    "The Forgotten Darkness": "被遗忘的黑暗",
    "The Frenzy": "疯狂",
    "The Lair of MV": "MV的巢穴",
    "The Nautilus - Stable": "诺特勒斯 - 马厩",
    "The Nautilus Hideout Room": "诺特勒斯隐藏室",
    "The Nightmare": "噩梦",
    "The Reunion": "重逢",
    "The Top of the Sky Nest": "天空之巢顶端",
    "Thief Hideout": "盗贼据点",
    "Thief Test Site": "盗贼考场",
    "Thief Training Center": "盗贼训练中心",
    "Thieves' Hideout": "盗贼们的藏身处",
    "Thieves' Marsh": "盗贼沼泽",
    "Thieving Moon Bunny's Hideout Entrance": "偷窃月兔的据点入口",
    "Thieving Moon Bunny's Hideout": "偷窃月兔的据点",
    "Thornbush Leading to Jump Stand": "通往跳跃台的荆棘丛",
    "Through the Head of the Ship!": "穿过船头！",
    "Timu's Forest": "蒂穆的森林",
    "Tino's Forest": "蒂诺的森林",
    "Tiru Forest": "蒂鲁森林",
    "Tiru's Forest": "蒂鲁的森林",
    "Tiv's Forest": "蒂夫的森林",
    "Tomb of Pharaoh Yeti ": "法老雪人之墓 ",
    "Tomb of Pharaoh Yeti": "法老雪人之墓",
    "Tower of Goddess &lt;Blessing of Goddess&gt;": "女神之塔 &lt;女神的祝福&gt;",
    "Tower of Goddess &lt;Center Tower&gt;": "女神之塔 &lt;中央塔&gt;",
    "Tower of Goddess &lt;Entrance&gt;": "女神之塔 &lt;入口&gt;",
    "Tower of Goddess &lt;Garden&gt;": "女神之塔 &lt;花园&gt;",
    "Tower of Goddess &lt;Jail I&gt;": "女神之塔 &lt;监狱一&gt;",
    "Tower of Goddess &lt;Jail II&gt;": "女神之塔 &lt;监狱二&gt;",
    "Tower of Goddess &lt;Jail III&gt;": "女神之塔 &lt;监狱三&gt;",
    "Tower of Goddess &lt;Jail Storage1&gt;": "女神之塔 &lt;监狱仓库1&gt;",
    "Tower of Goddess &lt;Jail Storage2&gt;": "女神之塔 &lt;监狱仓库2&gt;",
    "Tower of Goddess &lt;Jail-Storage 3&gt;": "女神之塔 &lt;监狱仓库3&gt;",
    "Tower of Goddess &lt;Lobby&gt;": "女神之塔 &lt;大厅&gt;",
    "Tower of Goddess &lt;On the Way Out&gt;": "女神之塔 &lt;下行之路&gt;",
    "Tower of Goddess &lt;On the Way Up&gt;": "女神之塔 &lt;上行之路&gt;",
    "Tower of Goddess &lt;Room 301&gt;": "女神之塔 &lt;301号室&gt;",
    "Tower of Goddess &lt;Room 302&gt;": "女神之塔 &lt;302号室&gt;",
    "Tower of Goddess &lt;Room 303&gt;": "女神之塔 &lt;303号室&gt;",
    "Tower of Goddess &lt;Room 304&gt;": "女神之塔 &lt;304号室&gt;",
    "Tower of Goddess &lt;Room of Darkness&gt;": "女神之塔 &lt;黑暗之室&gt;",
    "Tower of Goddess &lt;Sealed Room&gt;": "女神之塔 &lt;封印之室&gt;",
    "Tower of Goddess &lt;Storage&gt;": "女神之塔 &lt;仓库&gt;",
    "Tower of Goddess &lt;The Room of the Guilty&gt;": "女神之塔 &lt;罪人之室&gt;",
    "Tower of Goddess &lt;Treasure Storage&gt;": "女神之塔 &lt;宝物仓库&gt;",
    "Tower of Goddess &lt;Walkway&gt;": "女神之塔 &lt;走廊&gt;",
    "Tower's Maze": "塔之迷宫",
    "Tower's Trap": "塔之陷阱",
    "Toy Factory Back Room": "玩具工厂后厅",
    "Toy Factory&lt;Sector 4&gt;": "玩具工厂&lt;第四区域&gt;",
    "Traces of Yulete": "尤莱特的痕迹",
    "Train in Repair": "修理中的列车",
    "Training Ground 1": "训练场1",
    "Training Ground 2": "训练场2",
    "Training Ground 3": "训练场3",
    "Training Monster Pens 1": "训练怪兽圈1",
    "Training Monster Pens 2": "训练怪兽圈2",
    "Training Ridge": "训练山脊",
    "Training Room A": "训练室A",
    "Training Room B": "训练室B",
    "Training Room C": "训练室C",
    "Training Room D": "训练室D",
    "Training Room E": "训练室E",
    "Training Room H": "训练室H",
    "Training Room Storage": "训练室仓库",
    "Travel's End": "旅途终点",
    "Treasure Dungeon": "宝物地下城",
    "Treasure Room of Queen": "女王的宝物室",
    "Treatment Room": "治疗室",
    "Tutorial 0 ": "教程0 ",
    "Tutorial 0": "教程0",
    "Tutorial 1 ": "教程1 ",
    "Tutorial 2": "教程2",
    "Tutorial Room": "教程房间",
    "Twin Maze": "双胞胎迷宫",
    "Tynerum Altar": "泰纳鲁姆祭坛",
    "Ulrika Gang Hideout": "乌尔丽卡帮据点",
    "Ulrika's Hideout": "乌尔丽卡的据点",
    "Under the High Branch": "高枝之下",
    "Under the Moon": "月下",
    "Underground Base": "地下基地",
    "Underground Waterway": "地下水路",
    "Unique Road": "独特的道路",
    "Unpleasant Lab": "令人不快的实验室",
    "Utah's Pig Farm": "犹他的养猪场",
    "Valerie's Blustery Beach": "瓦莱丽的大风海滩",
    "Valley Depths": "山谷深处",
    "Valley Entrance": "山谷入口",
    "Valley of the Guard": "守卫之谷",
    "Veritas": "真理之地",
    "Victoria Road": "维多利亚大道",
    "Victorious Shout": "胜利呐喊",
    "Video": "视频",
    "Vision": "幻景",
    "Waist Deck": "腰甲板",
    "Waiting Area": "等候区",
    "Warped Dimension": "扭曲的次元",
    "Warrior Test Site": "战士考场",
    "Warrior Training Center": "战士训练中心",
    "Warriors' Territory": "战士领地",
    "Watchman's Tower": "守卫之塔",
    "Watermelon Field Exit": "西瓜田出口",
    "Waterway Maze": "水路迷宫",
    "Way to the Beach": "通往海滩的路",
    "Wayward Captain's Cabin": "任性船长的船舱",
    "Weaving Battle Active": "编织之战进行中",
    "Weaving Battle Arena": "编织之战竞技场",
    "Weird Room": "怪异房间",
    "Where Snow Rose Grows": "雪玫瑰生长之地",
    "White-Out Mountain": "白茫茫的山脉",
    "Wild Plant Habitat": "野生植物栖息地",
    "Wine Cellar": "酒窖",
    "Witch Cat and the Gingerbread House  ": "魔女猫和姜饼屋  ",
    "Witch Tower  ": "魔女之塔  ",
    "Witch Tower ": "魔女之塔 ",
    "Witch Tower 1st Floor  ": "魔女之塔1层  ",
    "Witch Tower 1st Floor ": "魔女之塔1层 ",
    "Witch Tower 2nd Floor  ": "魔女之塔2层  ",
    "Witch Tower 2nd Floor ": "魔女之塔2层 ",
    "Witch Tower 3rd Floor  ": "魔女之塔3层  ",
    "Witch Tower Entrance ": "魔女之塔入口 ",
    "Witch Tower": "魔女之塔",
    "Witch's Grave Site  ": "魔女的墓地  ",
    "Witch's Snowfield": "魔女的雪原",
    "Wolf's Agony": "狼的痛苦",
    "Wolf's Defeat  ": "狼的失败  ",
    "Wolf's Treachery  ": "狼的背叛  ",
    "Wounded Soldier's Camp": "伤兵营",
    "Wu Yang Giving Thanks": "吴阳的感恩",
    "Yulete's Lab 1": "尤莱特的实验室1",
    "Yulete's Lab 2": "尤莱特的实验室2",
    "Yulete's Lab 3": "尤莱特的实验室3",
    "Yulete's Lab": "尤莱特的实验室",
    "Yulete's Office": "尤莱特的办公室",
    "Zakum's Cave within a Dream": "梦境中的扎昆洞穴",
    "Zeno's Field": "泽诺的原野",
}

# Stage X: pattern translations
stage_translations = {
    "Stage 1: Auto Security Area 1": "第1关：自动安全区域1",
    "Stage 1: Azwan Battleground": "第1关：阿兹万战场",
    "Stage 1: Black Mountain Hill 1": "第1关：黑山丘陵1",
    "Stage 1: Castle Entrance": "第1关：城堡入口",
    "Stage 1: Cave of Darkness 1": "第1关：黑暗洞穴1",
    "Stage 1: Clandestine Ruins 1": "第1关：隐秘遗迹1",
    "Stage 1: Dangerously Isolated Forest 1": "第1关：危险的孤立森林1",
    "Stage 1: Dead Tree Forest 1": "第1关：枯树森林1",
    "Stage 1: Entrance to Dragon Forest": "第1关：龙之森林入口",
    "Stage 1: Forbidden Time 1": "第1关：禁忌时间1",
    "Stage 1: Golem's Temple 1": "第1关：石头人神殿1",
    "Stage 1: Hidden Field 1": "第1关：隐藏领域1",
    "Stage 1: Kelp Forest 1": "第1关：海带森林1",
    "Stage 1: Kerning Square 1": "第1关：废弃都市广场1",
    "Stage 1: Mossy Tree Forest 1": "第1关：青苔树林1",
    "Stage 1: Otherworld Battleground 1": "第1关：异界战场1",
    "Stage 1: Road of Regrets 1": "第1关：后悔之路1",
    "Stage 1: Ruined City 1": "第1关：废墟城市1",
    "Stage 1: Scorching Sand Desert 1": "第1关：灼热沙沙漠1",
    "Stage 1: Secret Pirate Hideout 1": "第1关：秘密海盗据点1",
    "Stage 1: Sky Forest Training Center 1": "第1关：天空森林训练中心1",
    "Stage 1: Snowy Mountain 1": "第1关：雪山1",
    "Stage 1: Spirit Valley 1": "第1关：精灵谷1",
    "Stage 1: Stronghold Entrance": "第1关：据点入口",
    "Stage 2: Auto Security Area 2": "第2关：自动安全区域2",
    "Stage 2: Azwan Battleground": "第2关：阿兹万战场",
    "Stage 2: Black Mountain Hill 2": "第2关：黑山丘陵2",
    "Stage 2: Cave of Darkness 2": "第2关：黑暗洞穴2",
    "Stage 2: Clandestine Ruins 2": "第2关：隐秘遗迹2",
    "Stage 2: Dangerously Isolated Forest 2": "第2关：危险的孤立森林2",
    "Stage 2: Dead Tree Forest 2": "第2关：枯树森林2",
    "Stage 2: Dragon Forest 1": "第2关：龙之森林1",
    "Stage 2: Forbidden Time 2": "第2关：禁忌时间2",
    "Stage 2: Golem's Temple 2": "第2关：石头人神殿2",
    "Stage 2: Hidden Field 2": "第2关：隐藏领域2",
    "Stage 2: Kelp Forest 2": "第2关：海带森林2",
    "Stage 2: Kerning Square 2": "第2关：废弃都市广场2",
    "Stage 2: Knights Secret Area": "第2关：骑士秘密区域",
    "Stage 2: Mossy Tree Forest 2": "第2关：青苔树林2",
    "Stage 2: Otherworld Battleground 2": "第2关：异界战场2",
    "Stage 2: Road of Regrets 2": "第2关：后悔之路2",
    "Stage 2: Ruined City 2": "第2关：废墟城市2",
    "Stage 2: Scorching Sand Desert 2": "第2关：灼热沙沙漠2",
    "Stage 2: Secret Pirate Hideout 2": "第2关：秘密海盗据点2",
    "Stage 2: Sky Forest Training Center 2": "第2关：天空森林训练中心2",
    "Stage 2: Snowy Mountain 2": "第2关：雪山2",
    "Stage 2: Spirit Valley 2": "第2关：精灵谷2",
    "Stage 2: Under the Castle Walls": "第2关：城墙之下",
    "Stage 3: Air Battleship Bow 3": "第3关：空中战舰舰首3",
    "Stage 3: Auto Security Area 3": "第3关：自动安全区域3",
    "Stage 3: Azwan Battleground": "第3关：阿兹万战场",
    "Stage 3: Black Mountain Hill 3": "第3关：黑山丘陵3",
    "Stage 3: Cave of Darkness 3": "第3关：黑暗洞穴3",
    "Stage 3: Clandestine Ruins 3": "第3关：隐秘遗迹3",
    "Stage 3: Dangerously Isolated Forest 3": "第3关：危险的孤立森林3",
    "Stage 3: Dead Tree Forest 3": "第3关：枯树森林3",
    "Stage 3: Dragon Forest 2": "第3关：龙之森林2",
    "Stage 3: Forbidden Time 3": "第3关：禁忌时间3",
    "Stage 3: Golem's Temple 3": "第3关：石头人神殿3",
    "Stage 3: Hidden Field 3": "第3关：隐藏领域3",
    "Stage 3: Ice Valley 1": "第3关：冰谷1",
    "Stage 3: Kelp Forest 3": "第3关：海带森林3",
    "Stage 3: Kerning Square 3": "第3关：废弃都市广场3",
    "Stage 3: Knights Drill Hall": "第3关：骑士训练场",
    "Stage 3: Mossy Tree Forest 3": "第3关：青苔树林3",
    "Stage 3: Otherworld Battleground 3": "第3关：异界战场3",
    "Stage 3: Road of Regrets 3": "第3关：后悔之路3",
    "Stage 3: Scorching Sand Desert 3": "第3关：灼热沙沙漠3",
    "Stage 3: Secret Pirate Hideout 3": "第3关：秘密海盗据点3",
    "Stage 3: Short Castle Wall": "第3关：矮城墙",
    "Stage 3: Sky Forest Training Center 3": "第3关：天空森林训练中心3",
    "Stage 3: Spirit Valley 3": "第3关：精灵谷3",
    "Stage 4: Air Battleship Area A": "第4关：空中战舰A区",
    "Stage 4: Auto Security Area 4": "第4关：自动安全区域4",
    "Stage 4: Black Mountain Hill 4": "第4关：黑山丘陵4",
    "Stage 4: Clandestine Ruins 4": "第4关：隐秘遗迹4",
    "Stage 4: Dangerously Isolated Forest 4": "第4关：危险的孤立森林4",
    "Stage 4: Dark Temple Entrance": "第4关：黑暗神殿入口",
    "Stage 4: Dead Mine 1": "第4关：废弃矿山1",
    "Stage 4: Deep in the Sky Forest": "第4关：天空森林深处",
    "Stage 4: Dragon Forest 3": "第4关：龙之森林3",
    "Stage 4: Forbidden Time 4": "第4关：禁忌时间4",
    "Stage 4: Golem's Temple 4": "第4关：石头人神殿4",
    "Stage 4: Gray's Hideout 1": "第4关：格雷的据点1",
    "Stage 4: Ice Valley 2": "第4关：冰谷2",
    "Stage 4: Kelp Forest 4": "第4关：海带森林4",
    "Stage 4: Kerning Square 4": "第4关：废弃都市广场4",
    "Stage 4: Knights Armory": "第4关：骑士军械库",
    "Stage 4: Mossy Tree Forest 4": "第4关：青苔树林4",
    "Stage 4: Otherworld Battleground 4": "第4关：异界战场4",
    "Stage 4: Road to Oblivion 1": "第4关：忘却之路1",
    "Stage 4: Scorching Sand Desert 4": "第4关：灼热沙沙漠4",
    "Stage 4: Secret Pirate Hideout 4": "第4关：秘密海盗据点4",
    "Stage 4: Spirit Valley 4": "第4关：精灵谷4",
    "Stage 4: Tall Castle Wall": "第4关：高城墙",
    "Stage 5: Auto Security Area 5": "第5关：自动安全区域5",
    "Stage 5: Clandestine Ruins 5": "第5关：隐秘遗迹5",
    "Stage 5: Corridor of Darkness": "第5关：黑暗走廊",
    "Stage 5: Dangerously Isolated Forest 5": "第5关：危险的孤立森林5",
    "Stage 5: Dead Mine 2": "第5关：废弃矿山2",
    "Stage 5: Dragon Forest 4": "第5关：龙之森林4",
    "Stage 5: Foggy Sky Forest": "第5关：雾蒙蒙的天空森林",
    "Stage 5: Forbidden Time 5": "第5关：禁忌时间5",
    "Stage 5: Golem's Temple 5": "第5关：石头人神殿5",
    "Stage 5: Gray's Hideout 2": "第5关：格雷的据点2",
    "Stage 5: Haunted House 1": "第5关：鬼屋1",
    "Stage 5: Kerning Square Rooftop": "第5关：废弃都市广场天台",
    "Stage 5: Knights Chamber": "第5关：骑士之室",
    "Stage 5: Mossy Tree Forest 5": "第5关：青苔树林5",
    "Stage 5: Otherworld Battleground 5": "第5关：异界战场5",
    "Stage 5: Road to Oblivion 2": "第5关：忘却之路2",
    "Stage 5: Road to the Ice Cave": "第5关：通往冰洞之路",
    "Stage 5: Scorching Sand Desert 5": "第5关：灼热沙沙漠5",
    "Stage 5: Secret Pirate Hideout 5": "第5关：秘密海盗据点5",
    "Stage 5: Spirit Valley 5": "第5关：精灵谷5",
    "Stage 5: Turban Shell Hill": "第5关：贝壳山丘",
    "Stage 5: Watchman's Tower": "第5关：守卫之塔",
    "Stage 6: Air Battleship Area C": "第6关：空中战舰C区",
    "Stage 6: Ani's Tower": "第6关：阿尼之塔",
    "Stage 6: Clandestine Ruins 6": "第6关：隐秘遗迹6",
    "Stage 6: Dangerously Isolated Forest 6": "第6关：危险的孤立森林6",
    "Stage 6: Deep Inside the Mossy Tree Forest": "第6关：青苔树林深处",
    "Stage 6: Dragon Nest": "第6关：龙巢",
    "Stage 6: Forbidden Time 6": "第6关：禁忌时间6",
    "Stage 6: Gray's Hideout 3": "第6关：格雷的据点3",
    "Stage 6: Hall of Honor": "第6关：荣誉大厅",
    "Stage 6: Haunted House 2": "第6关：鬼屋2",
    "Stage 6: Hidden Stone Chamber": "第6关：隐藏石室",
    "Stage 6: Ice Cave": "第6关：冰洞",
    "Stage 6: Inside the Thick Fog": "第6关：浓雾之中",
    "Stage 6: Otherworld Battleground 6": "第6关：异界战场6",
    "Stage 6: Scorching Sand Desert 6": "第6关：灼热沙沙漠6",
    "Stage 6: Secret Laboratory": "第6关：秘密实验室",
    "Stage 6: Secret Pirate Hideout 6": "第6关：秘密海盗据点6",
    "Stage 6: Silent Sea": "第6关：寂静之海",
    "Stage 6: Spirit Valley 6": "第6关：精灵谷6",
    "Stage 6: Temple of Darkness": "第6关：黑暗神殿",
    "Stage 6: Temple of Oblivion": "第6关：忘却之神殿",
    "Stage 6: The Cave of Trial": "第6关：试炼之洞",
    "Stage 6: Underground Construction Site": "第6关：地下工地",
    "Stage5: Air Battleship Area B": "第5关：空中战舰B区",
}

translations.update(stage_translations)

# Read file
with open(r'E:\github\MapleStoryV146\Service\SpiritMS\wz\String.wz\map\needT.xml', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace each translation (longest first to avoid partial matches)
for eng in sorted(translations.keys(), key=len, reverse=True):
    chn = translations[eng]
    content = content.replace('value="' + eng + '"', 'value="' + chn + '"')

# Write output
with open(r'E:\github\MapleStoryV146\Service\SpiritMS\wz\String.wz\map\needT.xml', 'w', encoding='utf-8') as f:
    f.write(content)

# Check for remaining English values
import re
remaining = set(re.findall(r'value="([A-Z][^"]*)"', content))
if remaining:
    print(f"Remaining untranslated ({len(remaining)}):")
    for r in sorted(remaining):
        print(f'    "{r}"')
else:
    print("All values translated successfully!")
